;;; auto-complete-octave.el --- 

;; Copyright 2009 Yen-Chin,Lee
;;
;; Author: coldnew
;; Version: $Id: auto-complete-octave.el,v 0.1 2009/07/14 07:33:43  Exp $
;; Keywords: Octave auto-complete
;; X-URL: http://www.emacswiki.org/emacs/auto-complete-octave.el

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

;;; Commentary:

;; This is for GNU Octave 3.2.0

;; Put this file into your load-path and the following into your ~/.emacs:
;;   (require 'auto-complete-octave)

;;; Code:

(provide 'auto-complete-octave)
(eval-when-compile
  (require 'cl)
  (require 'auto-complete))


;;;;##########################################################################
;;;;  User Options, Variables
;;;;##########################################################################
(defvar ac-octave-sources
  '(ac-source-octave-keywords))


(defface ac-octave-candidate-face
  '((t (:background "sandybrown" :foreground "black")))
  "Face for octave candidate menu."
  :group 'auto-complete)

(defface ac-octave-selection-face
  '((t (:background "coral3" :foreground "white")))
  "Face for the octave selected candidate."
  :group 'auto-complete)


(ac-define-dictionary-source
 ac-source-octave-keywords
'(
;; Octave function
;; a -----------------------------------------------------------------
	"aa2int" "ademodce" "ans" "arithmetic_encode" "atanh"
	"abs" "adsmax" "any" "arma_rnd" "atexit"
	"accumarray" "airy" "apkconst" "arrayfun" "au"
	"acos" "all" "append" "aryule" "auload"
	"acosd" "allchild" "append_save" "asci" "auplot"
	"acosh" "amd" "apply" "asctime" "ausave"
	"acot" "amdemod" "applylut" "asec" "autocor"
	"acotd" "aminolookup" "ar_psd" "asecd" "autocov"
	"acoth" "ammod" "arburg" "asech" "autoload"
	"acsc" "amodce" "arch_fit" "asin" "autoreg_matrix"
	"acscd" "ancestor" "arch_rnd" "asind" "autumn"
	"acsch" "and" "arch_test" "asinh" "available_backends"
	"add_input_event_hook" "anderson_darling_cdf" "area" "assert" "average_moments"
	"addlistener" "anderson_darling_test" "arg" "assignin" "awgn"
	"addpath" "angle" "argnames" "atan" "axes"
	"addproperty" "anova" "argv" "atan2" "axis"
	"addtodate" "anovan" "arithmetic_decode" "atand"
;; b -----------------------------------------------------------------
	"backend" "bessel" "betainc" "bincoeff" "bitmax" "bolling" "busdate"
	"balance" "besselh" "betainv" "binocdf" "bitor" "bone" "busdays"
	"bar" "besseli" "betaln" "binoinv" "bitrevorder" "box" "butter"
	"barh" "besselj" "betapdf" "binomial_cdf" "bitset" "boxcar" "buttord"
	"barthannwin" "besselk" "betarnd" "binomial_inv" "bitshift" "boxplot" "bwarea"
	"bartlett" "bessely" "betastat" "binomial_pdf" "bitxor" "break" "bwborder"
	"bartlett_test" "bestblk" "bfgsmin" "binomial_rnd" "blackman" "brighten" "bwdist"
	"base2dec" "beta" "bfgsmin_example" "binopdf" "blackmanharris" "bsc" "bweuler"
	"base64decode" "beta_cdf" "bi2de" "binornd" "blackmannuttall" "bscchannel" "bwhitmiss"
	"base64encode" "beta_inv" "bicg" "binostat" "blanks" "bsxfun" "bwmorph"
	"battery" "beta_pdf" "bicgstab" "bitand" "blkdiag" "buffer" "bwperim"
	"bchpoly" "beta_rnd" "bicubic" "bitcmp" "blkproc" "bug_report" "bwselect"
	"beep" "betacdf" "bilinear" "biterr" "bmpwrite" "builtin" "bzip2"
	"beep_on_error" "betai" "bin2dec" "bitget" "bohmanwin" "bunzip2"
	""
;; c -----------------------------------------------------------------
	"calendar" "chisqouttest" "colstyle" "copyfile"
	"canonicalize_file_name" "chisquare_cdf" "columns" "cor"
	"cart2pol" "chisquare_inv" "com2str" "cor_test"
	"cart2sph" "chisquare_pdf" "combs" "cordflt2"
	"case" "chisquare_rnd" "comet" "corr2"
	"caseread" "chisquare_test_homogeneity" "comma" "corrcoef"
	"casewrite" "chisquare_test_independence" "command_line_path" "cos"
	"cast" "chol" "common_size" "cosd"
	"cat" "chol2inv" "comms" "cosets"
	"catch" "choldelete" "commutation_matrix" "cosh"
	"catmullrom" "cholinsert" "compan" "cosint"
	"cauchy_cdf" "cholinv" "compand" "cot"
	"cauchy_inv" "cholshift" "compare_versions" "cotd"
	"cauchy_pdf" "cholupdate" "compass" "coth"
	"cauchy_rnd" "circshift" "complement" "cov"
	"caxis" "cla" "completion_append_char" "cplxpair"
	"cceps" "clabel" "completion_matches" "cplxreal"
	"ccolamd" "class" "complex" "cpsd"
	"cd" "clc" "computer" "cputime"
	"cdiff" "clear" "concat" "crash_dumps_octave_core"
	"ceil" "clearplot" "cond" "create_lookup_table"
	"cell" "cleave" "condeig" "create_set"
	"cell2mat" "clf" "condentr_seq" "cross"
	"cell2struct" "clg" "condest" "csape"
	"celldisp" "clip" "conditionalentropy_XY" "csapi"
	"cellfun" "clock" "conditionalentropy_YX" "csc"
	"cellidx" "cloglog" "confirm_recursive_rmdir" "cscd"
	"cellslices" "close" "conj" "csch"
	"cellstr" "closereq" "conndef" "csd"
	"center" "cmorwavf" "continue" "cstrcat"
	"cgs" "cmpermute" "contour" "cstrcmp"
	"char" "cmunique" "contour3" "csv2latex"
	"chdir" "cochrancdf" "contourc" "csvread"
	"cheb" "cochraninv" "contourf" "csvwrite"
	"cheb1ord" "cochrantest" "contrast" "csymamd"
	"cheb2ord" "cohere" "conv" "ctime"
	"chebwin" "col2im" "conv2" "ctranspose"
	"cheby1" "colamd" "convhull" "cummax"
	"cheby2" "colfilt" "convhulln" "cummin"
	"chi2cdf" "colloc" "convmtx" "cumprod"
	"chi2inv" "colon" "convn" "cumsum"
	"chi2pdf" "colorbar" "cool" "cumtrapz"
	"chi2rnd" "colorgradient" "copper" "cut"
	"chi2stat" "colormap" "copulacdf" "cylinder"
	"chirp" "colperm" "copulapdf" "czt"
;; d -----------------------------------------------------------------
	"d2_min" "dbnext" "dec2bin" "dftmtx" "dlmwrite"
	"daspk" "dbquit" "dec2hex" "diag" "dmperm"
	"daspk_options" "dbstack" "decimate" "diary" "dmult"
	"dasrt" "dbstatus" "decode" "diff" "do"
	"dasrt_options" "dbstep" "deconv" "diffpara" "do_string_escapes"
	"dassl" "dbstop" "default_save_options" "diffuse" "doc"
	"dassl_options" "dbtype" "deintrlv" "dilate" "doc_cache_file"
	"date" "dbup" "del2" "dir" "dos"
	"dateaxis" "dbwhere" "delaunay" "dirac" "dot"
	"datefind" "dct" "delaunay3" "diric" "double"
	"datenum" "dct2" "delaunayn" "discrete_cdf" "downsample"
	"datesplit" "dctmtx" "delete" "discrete_inv" "drawnow"
	"datestr" "ddmat" "dellistener" "discrete_pdf" "dsearch"
	"datetick" "de2bi" "delta_method" "discrete_rnd" "dsearchn"
	"datevec" "deal" "demo" "disp" "dst"
	"day" "deblank" "demodmap" "dispatch" "dump_prefs"
	"daysact" "debug" "deriche" "display" "dup2"
	"dbclear" "debug_on_error" "deriv" "dixoncdf" "duplication_matrix"
	"dbcont" "debug_on_interrupt" "det" "dixoninv" "durbinlevinson"
	"dbdown" "debug_on_warning" "detrend" "dixontest" "dwt"
	"dblquad" "dec2base" "dfdp" "dlmread" "dxfwrite"
;; e -----------------------------------------------------------------
	"e" "empirical_pdf" "errno" "expinv"
	"easter" "empirical_rnd" "errno_list" "expm"
	"echo" "encode" "error" "expm1"
	"echo_executing_commands" "end" "error_text" "exponential_cdf"
	"edge" "end_try_catch" "errorbar" "exponential_inv"
	"edit" "end_unwind_protect" "etime" "exponential_pdf"
	"edit_history" "endfor" "etree" "exponential_rnd"
	"editdistance" "endfunction" "etreeplot" "exppdf"
	"effrr" "endgrent" "eval" "exprnd"
	"egolaydec" "endif" "evalin" "expstat"
	"egolayenc" "endpwent" "example" "eye"
	"egolaygen" "endswitch" "example_netcdf" "eyediagram"
	"eig" "endwhile" "example_opendap" "ezcontour"
	"eigs" "entropy" "example_optiminterp" "ezcontourf"
	"ellip" "eomdate" "exec" "ezmesh"
	"ellipdemo" "eomday" "exist" "ezmeshc"
	"ellipj" "eps" "exit" "ezplot"
	"ellipke" "eq" "exp" "ezplot3"
	"ellipord" "erf" "expcdf" "ezpolar"
	"ellipsoid" "erfc" "expdemo" "ezsurf"
	"else" "erfcinv" "expfit" "ezsurfc"
	"elseif" "erfcx" "expint"
	"empirical_cdf" "erfinv" "expint_E1"
	"empirical_inv" "erode" "expint_Ei"
;; f -----------------------------------------------------------------
	"f_cdf" "feval" "file_in_path" "fix" "fnmatch" "frnd"
	"f_inv" "fexist" "fileattrib" "fixed_point_format" "fnplt" "fscanf"
	"f_pdf" "ff2n" "filemarker" "fixedpoint" "fnval" "fseek"
	"f_rnd" "fflush" "fileparts" "flag" "fopen" "fsolve"
	"f_test_regression" "fft" "filesep" "flattopwin" "for" "fsort"
	"factor" "fft2" "fill" "flipdim" "fork" "fspecial"
	"factorial" "fftconv" "filter" "fliplr" "format" "fstat"
	"fail" "fftconv2" "filter2" "flipud" "formula" "ftell"
	"false" "fftfilt" "filtfilt" "float" "fpdf" "full"
	"fbusdate" "fftn" "filtic" "floor" "fplot" "fullfact"
	"fcdf" "fftshift" "find" "flops" "fprintf" "fullfile"
	"fclear" "fftw" "find_dir_in_path" "fltk_backend" "fputs" "func2str"
	"fclose" "fgetl" "findall" "fmdemod" "fracshift" "function"
	"fcnchk" "fgets" "findobj" "fmin" "fractdiff" "functions"
	"fcntl" "fht" "findstr" "fminbnd" "fread" "funm"
	"fdisp" "fibodeco" "findsym" "fmins" "freport" "fwrite"
	"feather" "fiboenco" "finite" "fminsearch" "freqs" "fzero"
	"feedback" "fibosplitstream" "finv" "fminunc" "freqs_plot"
	"feof" "fieldnames" "fir1" "fmmod" "freqz"
	"ferror" "figure" "fir2" "fmod" "freqz_plot"
	"fetch" "file_in_loadpath" "firls" "fnder" "frewind"
;; g -----------------------------------------------------------------
	"gamcdf" "gen2par" "getid" "gmonopuls"
	"gamfit" "gen_doc_cache" "getpgrp" "gmtime"
	"gaminv" "genpath" "getpid" "gnuplot_binary"
	"gamlike" "genqamdemod" "getppid" "gnuplot_drawnow"
	"gamma" "genqammod" "getpwent" "golombdeco"
	"gamma_cdf" "genvarname" "getpwnam" "golombenco"
	"gamma_inv" "geocdf" "getpwuid" "gplot"
	"gamma_pdf" "geoinv" "getrusage" "gradient"
	"gamma_rnd" "geomean" "getuid" "gray"
	"gammai" "geometric_cdf" "gfft" "gray2ind"
	"gammainc" "geometric_inv" "gftable" "grayslice"
	"gammaln" "geometric_pdf" "gfweight" "graythresh"
	"gampdf" "geometric_rnd" "gifft" "grep"
	"gamrnd" "geopdf" "ginput" "grid"
	"gamstat" "geornd" "gisequal" "griddata"
	"gauspuls" "geostat" "givens" "griddata3"
	"gaussian" "get" "glob" "griddatan"
	"gausswin" "get_first_help_sentence" "global" "groots"
	"gca" "get_help_text" "glpk" "grpdelay"
	"gcbf" "getegid" "glpkmex" "grubbscdf"
	"gcbo" "getenv" "gls" "grubbsinv"
	"gcd" "geteuid" "gmap40" "grubbstest"
	"gcf" "getfield" "gmm_estimate" "gt"
	"gconv" "getfields" "gmm_example" "gtext"
	"gconvmtx" "getgid" "gmm_obj" "gunzip"
	"gdeconv" "getgrent" "gmm_results" "gzip"
	"gdftmtx" "getgrgid" "gmm_variance"
	"ge" "getgrnam" "gmm_variance_inefficient"
;; h -----------------------------------------------------------------
	"hadamard" "hist2d" "hour"
	"hammgen" "histc" "housh"
	"hamming" "histeq" "hsv"
	"hankel" "histfit" "hsv2rgb"
	"hann" "" "history" "huffmandeco"
	"hanning" "history_file" "huffmandict"
	"harmmean" "history_size" "huffmanenco"
	"hartley_entropy" "history_timestamp_format_string" "hurst"
	"heaviside" "hmmestimate" "hygecdf"
	"help" "" "hmmgenerate" "hygeinv"
	"hess" "" "hmmviterbi" "hygepdf"
	"hex2dec" "hold" "" "hygernd"
	"hex2num" "holidays" "hygestat"
	"hggroup" "home" "" "hypergeometric_cdf"
	"hhigh" "horzcat" "hypergeometric_inv"
	"hidden" "hot" "hypergeometric_pdf"
	"highlow" "hotelling_test" "hypergeometric_rnd"
	"hilb" "" "hotelling_test_2" "hypot"
	"hilbert" "hough_circle"
	"hist" "" "houghtf"
;; i -----------------------------------------------------------------
	"i" "ind2gray" "irsa_genreal" "isgraph"
	"idct" "ind2rgb" "irsa_idft" "isgray"
	"idct2" "ind2sub" "irsa_isregular" "ishandle"
	"idivide" "index" "irsa_jitsp" "ishghandle"
	"idplot" "inf" "irsa_mdsp" "ishold"
	"idsim" "inferiorto" "irsa_normalize" "isieee"
	"idst" "info" "irsa_plotdft" "isind"
	"if" "info_file" "irsa_resample" "isinf"
	"ifft" "info_program" "irsa_rgenreal" "isinteger"
	"ifft2" "infoentr_seq" "is_absolute_filename" "iskeyword"
	"ifftn" "infogain_seq" "is_bool" "isletter"
	"ifftshift" "infoskeleton" "is_complex" "islist"
	"ifht" "inline" "is_duplicate_entry" "islogical"
	"ignore_function_time_stamp" "inpolygon" "is_global" "islower"
	"im2bw" "input" "is_leap_year" "ismac"
	"im2col" "inputname" "is_list" "ismatrix"
	"im2double" "int16" "is_matrix" "ismember"
	"im2uint16" "int2aa" "is_rooted_relative_filename" "ismethod"
	"im2uint8" "int2str" "is_scalar" "isna"
	"imadjust" "int32" "is_square" "isnan"
	"imag" "int64" "is_stream" "isnull"
	"image" "int8" "is_struct" "isnumeric"
	"image_viewer" "interp" "is_symmetric" "isobject"
	"imagesc" "interp1" "is_vector" "isocolors"
	"imclose" "interp1q" "isa" "isonormals"
	"imcomplement" "interp2" "isalnum" "isosurface"
	"imdilate" "interp3" "isalpha" "ispc"
	"imerode" "interpft" "isascii" "isposint"
	"imfilter" "interpn" "isbool" "isprime"
	"imfinfo" "intersect" "isbusday" "isprint"
	"imginfo" "intersection" "isbw" "ispunct"
	"imhist" "intmax" "iscell" "israwcommand"
	"immaximas" "intmin" "iscellstr" "isreal"
	"imnoise" "intrlv" "ischar" "isrgb"
	"imopen" "intwarning" "iscntrl" "isscalar"
	"impad" "inv" "iscommand" "issorted"
	"imperspectivewarp" "inverse" "iscomplex" "isspace"
	"impz" "invfreq" "isdebugmode" "issparse"
	"imread" "invfreqs" "isdefinite" "issquare"
	"imremap" "invfreqz" "isdigit" "isstr"
	"imresize" "invhilb" "isdir" "isstrprop"
	"imrotate" "inz" "isempty" "isstruct"
	"imrotate_Fourier" "ipermute" "isequal" "issymmetric"
	"imshear" "iqr" "isequalwithequalnans" "isunix"
	"imshow" "irsa_act" "isfield" "isupper"
	"imsmooth" "irsa_actcore" "isfigure" "isvarname"
	"imtophat" "irsa_check" "isfinite" "isvector"
	"imtranslate" "irsa_dft" "isfloat" "isxdigit"
	"imwrite" "irsa_dftfp" "isglobal"
;; j -----------------------------------------------------------------
	"j" "jet" "jointentropy" "jsucdf" "jsupdf"
;; k -----------------------------------------------------------------
	"kaiser" "kernel_density_nodes" "keyboard" "kruskal_wallis_test"
	"kaiserord" "kernel_example" "kill" "krylov"
	"kbhit" "kernel_optimal_bandwidth" "kolmogorov_smirnov_cdf" "krylovb"
	"kendall" "kernel_regression" "kolmogorov_smirnov_test" "kullback_leibler_distance"
	"kernel_density" "kernel_regression_cvscore" "kolmogorov_smirnov_test_2" "kurtosis"
	"kernel_density_cvscore" "kernel_regression_nodes" "kron"
;; l -----------------------------------------------------------------
	"label2rgb" "link" "" "logm"
	"laguerre" "linkage" "logncdf"
	"lambertw" "linkprop" "logninv"
	"laplace_cdf" "linspace" "lognormal_cdf"
	"laplace_inv" "list" "" "lognormal_inv"
	"laplace_pdf" "list_in_columns" "lognormal_pdf"
	"laplace_rnd" "list_primes" "lognormal_rnd"
	"lasterr" "llow" "" "lognpdf"
	"lasterror" "lloyds" "lognrnd"
	"lastwarn" "load" "" "lognstat"
	"lauchli" "loadaudio" "logsig"
	"laverage" "loadimage" "logspace"
	"lbusdate" "loadobj" "lookfor"
	"lchol" "localtime" "lookup"
	"lcm" "log" "lookup_table"
	"ldivide" "log10" "lower"
	"le" "log1p" "ls"
	"leasqr" "log2" "" "ls_command"
	"leasqrdemo" "logical" "lsode"
	"legend" "logistic_cdf" "lsode_options"
	"legendre" "logistic_inv" "lsqnonneg"
	"length" "logistic_pdf" "lstat"
	"levinson" "logistic_regression" "lt"
	"lfdif" "logistic_regression_derivatives" "lu"
	"lgamma" "logistic_regression_likelihood" "luinc"
	"license" "logistic_rnd" "lweekdate"
	"lin2mu" "logit" "lz77deco"
	"line" "" "loglog" "lz77enco"
	"line_min" "loglogerr"
;; m -----------------------------------------------------------------
	"m2xdate" "matdeintrlv" "meshgrid" "mkoctfile" "months"
	"mad" "matintrlv" "meshz" "mkpp" "more"
	"magic" "matlabroot" "methods" "mkstemp" "morlet"
	"mahalanobis" "matrix_type" "mex" "mktheta" "movavg"
	"make_absolute_filename" "max" "mexext" "mktime" "movefile"
	"makeinfo_program" "max_recursion_depth" "mexihat" "mldivide" "mpoles"
	"makelut" "mcnemar_test" "meyeraux" "mle_estimate" "mpower"
	"manova" "md5sum" "mfilename" "mle_example" "mrdivide"
	"map" "mdsmax" "min" "mle_obj" "mscohere"
	"marcumq" "mean" "min_max" "mle_obj_nodes" "mtimes"
	"marginalc" "mean2" "minimize" "mle_results" "mu2lin"
	"marginalr" "meansq" "minpol" "mle_variance" "munlock"
	"mark_as_command" "medfilt2" "minus" "mlock" "mutualinfo_seq"
	"mark_as_rawcommand" "median" "minute" "mod" "mutualinformation"
	"mat2cell" "menu" "mirr" "mode" "mvnpdf"
	"mat2gray" "mesh" "mislocked" "modmap" "mvnrnd"
	"mat2str" "meshc" "mkdir" "moment"
	"match" "meshdom" "mkfifo" "month"
;; n -----------------------------------------------------------------
	"namelengthmax" "nbininv" "ndims" "nonzeros" "nth"
	"nan" "nbinpdf" "ne" "norm" "nthroot"
	"nanmax" "nbinrnd" "negvolidx" "normal_cdf" "ntsc2rgb"
	"nanmean" "nbinstat" "nelder_mead_min" "normal_inv" "null"
	"nanmedian" "ncauer" "newff" "normal_pdf" "num2cell"
	"nanmin" "ncbyte" "newplot" "normal_rnd" "num2hex"
	"nanstd" "ncchar" "news" "normcdf" "num2str"
	"nansum" "ncdouble" "nextpow2" "normest" "numel"
	"nanvar" "ncdump" "nlfilter" "norminv" "nuttallwin"
	"nargchk" "ncfloat" "nls_estimate" "normpdf" "nweekdate"
	"nargin" "nchoosek" "nls_example" "normplot" "nze"
	"nargout" "ncint" "nls_obj" "normrnd" "nzmax"
	"nargoutchk" "nclong" "nls_obj_nodes" "normstat"
	"narysource" "ncshort" "nmsmax" "not"
	"native_float_format" "nctest" "nnz" "now"
	"nbincdf" "ndgrid" "nomrr" "nrm"
;; o -----------------------------------------------------------------
	"ocean" "odeget" "odepkg_testsuite_impltrans" "optiminterp4"
	"oct2dec" "odephas2" "odepkg_testsuite_oregonator" "optiminterpn"
	"octave_config_info" "odephas3" "odepkg_testsuite_pollution" "optimset"
	"octave_core_file_limit" "odepkg" "odepkg_testsuite_robertson" "or"
	"octave_core_file_name" "odepkg_event_handle" "odepkg_testsuite_transistor" "orderfields"
	"octave_core_file_options" "odepkg_examples_dae" "odeplot" "ordfilt2"
	"octave_tmp_file_name" "odepkg_examples_dde" "odeprint" "ordfiltn"
	"ode23" "odepkg_examples_ide" "odeset" "orient"
	"ode23d" "odepkg_examples_ode" "ols" "orth"
	"ode45" "odepkg_structure_check" "onbalvol" "otherwise"
	"ode45d" "odepkg_testsuite_calcmescd" "onenormest" "outlier"
	"ode54" "odepkg_testsuite_calcscd" "ones" "output_max_field_width"
	"ode54d" "odepkg_testsuite_chemakzo" "optimget" "output_precision"
	"ode78" "odepkg_testsuite_hires" "optiminterp1"
	"ode78d" "odepkg_testsuite_implakzo" "optiminterp2"
	"odeexamples" "odepkg_testsuite_implrober" "optiminterp3"
;; p -----------------------------------------------------------------
	"pack" "perl" "poisstat" "ppval"
	"padarray" "perms" "pol2cart" "prctile"
	"page_output_immediately" "permute" "polar" "prepad"
	"page_screen_output" "perror" "poly" "prestd"
	"pamdemod" "persistent" "poly2mask" "prettyprint"
	"pammod" "physical_constant" "poly2sym" "prettyprint_c"
	"parameterize" "pi" "poly2th" "primes"
	"paren" "pie" "poly_2_ex" "princomp"
	"pareto" "pink" "polyaffine" "print"
	"parseparams" "pinv" "polyarea" "print_empty_dimensions"
	"parzenwin" "pipe" "polyconf" "print_usage"
	"pascal" "pkg" "polyder" "printf"
	"pascal_cdf" "planerot" "polyderiv" "prism"
	"pascal_inv" "playaudio" "polyfit" "probit"
	"pascal_pdf" "plot" "polygcd" "prod"
	"pascal_rnd" "plot3" "polyint" "program_invocation_name"
	"patch" "plotmatrix" "polyinteg" "program_name"
	"path" "plotyy" "polyout" "prop_test_2"
	"pathdef" "plus" "polyreduce" "psi"
	"pathsep" "pointfig" "polystab" "pskdemod"
	"pause" "poisscdf" "polyval" "pskmod"
	"pburg" "poissinv" "polyvalm" "pulstran"
	"pcg" "poisson" "popen" "purelin"
	"pchip" "poisson_cdf" "popen2" "putenv"
	"pclose" "poisson_inv" "postpad" "puts"
	"pcolor" "poisson_moments" "poststd" "pwd"
	"pcr" "poisson_pdf" "posvolidx" "pwelch"
	"pdist" "poisson_rnd" "pow2" "pyulear"
	"peaks" "poisspdf" "power"
	"periodogram" "poissrnd" "ppplot"
;; q -----------------------------------------------------------------
	"qamdemod" "qfunc" "qqplot" "qrshift" "qtgetblk" "quadgk" "quantiz" "qz"
	"qammod" "qfuncinv" "qr" "qrupdate" "qtsetblk" "quadl" "quit" "qzhess"
	"qaskdeco" "qp" "qrdelete" "qtable" "quad" "quadv" "quiver"
	"qaskenco" "qp_kaiser" "qrinsert" "qtdecomp" "quad_options" "quantile" "quiver3"
;; R -----------------------------------------------------------------
	"radon" "read_readline_init_file" "relativeentropy" "rleenco"
	"rainbow" "readdir" "rem" "rmdir"
	"rand" "readlink" "remove_input_event_hook" "rmfield"
	"randdeintrlv" "real" "rename" "rmoutlier"
	"rande" "reallog" "renyi_entropy" "rmpath"
	"randerr" "realmax" "replot" "roicolor"
	"randg" "realmin" "repmat" "roots"
	"randint" "realpow" "resample" "rose"
	"randintrlv" "realsqrt" "reshape" "rosenbrock"
	"randn" "record" "residue" "rosser"
	"random" "rectangle_lw" "residued" "rot90"
	"randp" "rectangle_sw" "residuez" "rotdim"
	"randperm" "rectint" "resize" "rotparams"
	"randsrc" "rectpuls" "restoredefaultpath" "rotv"
	"range" "rectwin" "rethrow" "round"
	"rank" "reduce" "return" "roundb"
	"ranks" "redundancy" "reverse" "rows"
	"rat" "reedmullerdec" "rgb2gray" "rref"
	"rats" "reedmullerenc" "rgb2hsv" "rsdecof"
	"raylcdf" "reedmullergen" "rgb2ind" "rsencof"
	"raylinv" "refresh" "rgb2ntsc" "rsgenpoly"
	"raylpdf" "refreshdata" "rgbplot" "rsindex"
	"raylrnd" "regdatasmooth" "rgdtsmcore" "run"
	"raylstat" "regexp" "rgdtsmcorewrap" "run_count"
	"rceps" "regexpi" "ribbon" "run_history"
	"rcond" "regexprep" "ricedeco" "run_test"
	"rdivide" "regexptranslate" "riceenco" "rundemos"
	"re_read_readline_init_file" "regress" "rindex" "runlength"
	"read_options" "rehash" "rledeco"
;; s -----------------------------------------------------------------
	"safeprod" "silent_functions" "split" "strjust"
	"samin_example" "sim" "split_long_rows" "strmatch"
	"save" "sin" "splot" "strncmp"
	"saveMLPStruct" "sinc" "splu" "strncmpi"
	"save_header_format_string" "sind" "spmax" "strptime"
	"save_precision" "sinetone" "spmin" "strrep"
	"saveaudio" "sinewave" "spones" "strsort"
	"saveimage" "single" "spparms" "strsplit"
	"saveobj" "sinh" "spprod" "strtok"
	"savepath" "sinint" "spqr" "strtrim"
	"saving_history" "size" "sprand" "strtrunc"
	"sawtooth" "size_equal" "sprandn" "struct"
	"scale_data" "sizeof" "sprandsym" "struct2cell"
	"scanf" "skewness" "sprank" "struct_contains"
	"scatter" "sleep" "spring" "struct_elements"
	"scatter3" "slice" "sprintf" "struct_levels_to_print"
	"scatterplot" "slurp_file" "spstats" "structfun"
	"schur" "sombrero" "spsum" "strvcat"
	"scloseall" "sort" "spsumsq" "studentize"
	"scores" "sortrows" "spvcat" "sub2ind"
	"sec" "sos2tf" "spy" "subplot"
	"secd" "sos2zp" "sqp" "subsasgn"
	"sech" "sound" "sqrt" "subsindex"
	"second" "soundsc" "sqrtm" "subspace"
	"semicolon" "source" "square" "subsref"
	"semilogx" "spalloc" "squareform" "substr"
	"semilogxerr" "sparse" "squeeze" "substruct"
	"semilogy" "sparse_auto_mutate" "sscanf" "sum"
	"semilogyerr" "spatan2" "stairs" "sum_moments_nodes"
	"seqreverse" "spaugment" "stat" "summer"
	"server" "spchol" "static" "sumsq"
	"set" "spchol2inv" "statistics" "superiorto"
	"setaudio" "spcholinv" "std" "suppress_verbose_help_message"
	"setdiff" "spconvert" "std2" "surf"
	"setenv" "spcumprod" "stderr" "surface"
	"setfield" "spcumsum" "stdin" "surfc"
	"setfields" "spdet" "stdnormal_cdf" "surfl"
	"setgrent" "spdiag" "stdnormal_inv" "surfnorm"
	"setpwent" "spdiags" "stdnormal_pdf" "svd"
	"setstr" "spearman" "stdnormal_rnd" "svds"
	"setxor" "specgram" "stdout" "swapbytes"
	"sftrans" "spectral_adf" "stem" "switch"
	"sgolay" "spectral_xdf" "stem3" "syl"
	"sgolayfilt" "specular" "stft" "sylvester_matrix"
	"shading" "speed" "str2double" "sym2poly"
	"shannon_entropy" "spencer" "str2func" "symamd"
	"shannonfanodeco" "speye" "str2mat" "symbfact"
	"shannonfanodict" "spfind" "str2num" "symerr"
	"shannonfanoenco" "spfun" "strcat" "symfsolve"
	"shanwavf" "sph2cart" "strchr" "symlink"
	"shell_cmd" "sphcat" "strcmp" "symrcm"
	"shg" "sphere" "strcmpi" "symvar"
	"shift" "spinmap" "strerror" "synthesis"
	"shiftdim" "spinv" "stretchlim" "system"
	"sighup_dumps_octave_core" "spkron" "strfind" "systematize"
	"sign" "splchol" "strftime"
	"sign_test" "splice" "string_fill_char"
	"sigterm_dumps_octave_core" "spline" "strjoin"
;; t -----------------------------------------------------------------
	"t_cdf" "tempdir" "test_optiminterp_mult" "toascii" "trimmean"
	"t_inv" "tempname" "test_sncndn" "toc" "triplequad"
	"t_pdf" "terminal_size" "test_struct" "today" "triplot"
	"t_rnd" "test" "test_wpolyfit" "toeplitz" "tripuls"
	"t_test" "test_d2_min_1" "texas_lotto" "tolower" "trisurf"
	"t_test_2" "test_d2_min_2" "text" "toupper" "triu"
	"t_test_regression" "test_d2_min_3" "tf2sos" "tpdf" "trnd"
	"table" "test_ellint" "tfe" "trace" "true"
	"tabulate" "test_ellipj" "tfestimate" "train" "try"
	"tan" "test_fminunc_1" "thfm" "transpose" "tsearch"
	"tand" "test_gsvd" "thirdwednesday" "trapz" "tsearchn"
	"tanh" "test_hyperg" "tic" "trastd" "tstat"
	"tansig" "test_min_1" "tics" "treelayout" "tukeywin"
	"tar" "test_min_2" "tilde_expand" "treeplot" "tunstallcode"
	"tars" "test_min_3" "time" "triang" "type"
	"taxedrr" "test_min_4" "times" "triangle_lw" "typecast"
	"tblread" "test_minimize_1" "tinv" "triangle_sw" "typeinfo"
	"tblwrite" "test_nelder_mead_min_1" "title" "tricontour"
	"tcdf" "test_nelder_mead_min_2" "tmpfile" "tril"
	"temp_name" "test_optiminterp" "tmpnam" "trimesh"
;; u -----------------------------------------------------------------
	"u_test" "undo_string_escapes" "uniform_rnd" "unmark_rawcommand" "upfirdn"
	"uint16" "unidcdf" "unifpdf" "unmkpp" "uplus"
	"uint32" "unidinv" "unifrnd" "unpack" "upper"
	"uint64" "unidpdf" "unifstat" "unscale_parameters" "upsample"
	"uint8" "unidrnd" "union" "untar" "urlread"
	"uintlut" "unidstat" "unique" "until" "urlwrite"
	"umask" "unifcdf" "unitfeedback" "unvech" "usage"
	"uminus" "unifinv" "units" "unwind_protect" "usleep"
	"uname" "uniform_cdf" "unix" "unwind_protect_cleanup"
	"unarydec" "uniform_inv" "unlink" "unwrap"
	"unaryenc" "uniform_pdf" "unmark_command" "unzip"
;; v -----------------------------------------------------------------
	"validatestring" "var" "varargout" "vech" "version" "voronoi"
	"values" "var_test" "vec" "vectorize" "vertcat" "voronoin"
	"vander" "varargin" "vec2mat" "ver" "view"
;; w -----------------------------------------------------------------
	"waitforbuttonpress" "wblcdf" "weibinv" "welch_test" "who" "window"
	"waitpid" "wblinv" "weibpdf" "welchwin" "whos" "winter"
	"warning" "wblpdf" "weibrnd" "wgn" "whos_line_format" "wkeep"
	"warning_ids" "wblrnd" "weibull_cdf" "what" "wiener_rnd" "wpolyfit"
	"warranty" "wblstat" "weibull_inv" "which" "wienrnd" "wpolyfitdemo"
	"wavread" "weekday" "weibull_pdf" "while" "wilcoxon_test" "wrev"
	"wavwrite" "weibcdf" "weibull_rnd" "white" "wilkinson" "wsolve"
;; x -----------------------------------------------------------------
	"x2mdate" "xcorr" "xcorr2" "xcov" "xlabel" "xlim" "xlsread" "xmlwrite" "xor"
;; y -----------------------------------------------------------------
	"yahoo" "year" "yeardays" "yes_or_no" "ylabel" "ylim" "yulewalker"
;; z -----------------------------------------------------------------
	"z_test" "zagzig" "zeta" "zip" "zlim" "zp2sos" "zscore"
	"z_test_2" "zeros" "zigzag" "zlabel" "zoom" "zplane"

;; A -----------------------------------------------------------------
;; B -----------------------------------------------------------------
;; C -----------------------------------------------------------------
	"Ci"
;; D -----------------------------------------------------------------
;; E -----------------------------------------------------------------
	"EDITOR" "EXEC_PATH"
;; F -----------------------------------------------------------------
	"F_DUPFD" "F_GETFD" "F_GETFL" "F_SETFD" "F_SETFL"
;; G -----------------------------------------------------------------
;; H -----------------------------------------------------------------
;; I -----------------------------------------------------------------
	"I" "IMAGE_PATH" "Inf"
;; J -----------------------------------------------------------------
	"J"
;; K -----------------------------------------------------------------
;; L -----------------------------------------------------------------
	"LinearRegression"
;; M -----------------------------------------------------------------
;; N -----------------------------------------------------------------
	"NA" "NaN"
;; O -----------------------------------------------------------------
	"OCTAVE_HOME" "O_APPEND" "O_CREAT" "O_NONBLOCK" "O_RDWR" "O_TRUNC"
	"OCTAVE_VERSION" "O_ASYNC" "O_EXCL" "O_RDONLY" "O_SYNC" "O_WRONLY"
;; P -----------------------------------------------------------------
	"PAGER" "PAGER_FLAGS" "PS1" "PS2" "PS4" "P_tmpdir"
;; Q -----------------------------------------------------------------
;; R -----------------------------------------------------------------
;; S -----------------------------------------------------------------
	"SEEK_CUR" "SEEK_END" "SEEK_SET" "SIG" "S_ISBLK" "S_ISCHR" "S_ISDIR" "S_ISFIFO" "S_ISLNK" "S_ISREG" "S_ISSOCK" "Si"
;; T -----------------------------------------------------------------
;; U -----------------------------------------------------------------
;; V -----------------------------------------------------------------
;; W -----------------------------------------------------------------
	"WCONTINUE" "WEXITSTATUS" "WIFEXITED" "WIFSTOPPED" "WSTOPSIG" "WUNTRACED"
	"WCOREDUMP" "WIFCONTINUED" "WIFSIGNALED" "WNOHANG" "WTERMSIG"
;; X -----------------------------------------------------------------
;; Y -----------------------------------------------------------------
;; Z -----------------------------------------------------------------
;; __ -----------------------------------------------------------------
	"__accumarray_sum__" "__get__" "__magick_finfo__" "__printInputs"
	"__actual_axis_position__" "__getx" "__magick_read__" "__printLW"
	"__add_datasource__" "__glpk__" "__magick_write__" "__printLayerConnect"
	"__additional_help_message__" "__gnuplot_get_var__" "__makeinfo__" "__printLayerWeights"
	"__all_opts__" "__gnuplot_ginput__" "__marching_cube__" "__printLayers"
	"__area__" "__gnuplot_has_feature__" "__mse" "__printMLPHeader"
	"__axes_limits__" "__gnuplot_open_stream__" "__newnetwork" "__printNetworkType"
	"__axis_label__" "__gnuplot_version__" "__next_line_color__" "__printNumInputDelays"
	"__bar__" "__go_axes__" "__operators__" "__printNumInputs"
	"__bars__" "__go_axes_init__" "__parent_classes__" "__printNumLayerDelays"
	"__builtins__" "__go_close_all__" "__parser_debug_flag__" "__printNumLayers"
	"__calcjacobian" "__go_delete__" "__patch__" "__printNumOutputs"
	"__calcperf" "__go_draw_axes__" "__pathorig__" "__printNumTargets"
	"__checknetstruct" "__go_draw_figure__" "__pchip_deriv__" "__printOutputConnect"
	"__clabel__" "__go_execute_callback__" "__plr1__" "__printOutputs"
	"__contour__" "__go_figure__" "__plr2__" "__printPerformFcn"
	"__contourc__" "__go_figure_handles__" "__plt1__" "__printPerformParam"
	"__convn__" "__go_handles__" "__plt2__" "__printTargetConnect"
	"__current_scope__" "__go_hggroup__" "__plt2mm__" "__printTargets"
	"__default_plot_options__" "__go_image__" "__plt2mv__" "__printTrainFcn"
	"__delaunayn__" "__go_line__" "__plt2ss__" "__printTrainParam"
	"__display_tokens__" "__go_patch__" "__plt2sv__" "__qp__"
	"__dlogsig" "__go_surface__" "__plt2vm__" "__quantile__"
	"__dogleg__" "__go_text__" "__plt2vs__" "__quiver__"
	"__dpurelin" "__gud_mode__" "__plt2vv__" "__remove_fltk__"
	"__dsearchn__" "__img__" "__plt__" "__request_drawnow__"
	"__dtansig" "__img_via_file__" "__plt_get_axis_arg__" "__scatter__"
	"__dump_symtab_info__" "__init" "__pltopt1__" "__setx"
	"__ellip_ws" "__init_fltk__" "__pltopt__" "__sort_rows_idx__"
	"__ellip_ws_min" "__interp_cube__" "__power" "__splinen__"
	"__end__" "__isa_parent__" "__printAdaptFcn" "__stem__"
	"__errcomm__" "__isequal__" "__printAdaptParam" "__strip_html_tags__"
	"__error_text__" "__kernel_epanechnikov" "__printB" "__tbl_delim__"
	"__errplot__" "__kernel_normal" "__printBiasConnect" "__token_count__"
	"__extractpath__" "__kernel_weights" "__printBiases" "__trainlm"
	"__ezplot__" "__keywords__" "__printIW" "__version_info__"
	"__fdjac__" "__lexer_debug_flag__" "__printInitFcn" "__voronoi__"
	"__finish__" "__lin_interpn__" "__printInitParam" "__which__"
	"__fltk_maxtime__" "__line__" "__printInputConnect" "__xzip__"
	"__fltk_redraw__" "__list_functions__" "__printInputWeights"
))

(defun ac-octave-setup ()
  (setq ac-sources (append ac-octave-sources ac-sources)))

(defun ac-octave-init ()
  (add-hook 'ocatve-mode-hook 'ac-octave-setup))


;;; auto-complete-octave.el ends here
