;;; chinese-t-menu.el --- Add chinese-t menu bar -*- coding: utf-8 -*-

;; Copyright 2006 Ye Wenbin, 2011 Wei-Lun Chao
;;
;; Author: wenbinye@163.com, chaoweilun@gmail.com
;; Time-stamp: <Wei-Lun Chao 2011-02-07 00:00:00>
;; Version: $Id: chinese-t-menu.el,v 1.1 2011/02/07 00:00:00 cwl Exp cwl $
;; Keywords:
;; X-URL: not distributed yet

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version. 
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details. 
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 

;;; Commentary:

;; Put this file into your load-path and the following into your ~/.emacs:
;; (require 'chinese-t-menu)
;; (require 'english-menu)
;; (require 'mule-menu)

;;; Code:

(provide 'chinese-t-menu)
(eval-when-compile
  (require 'cl))

(defvar mule-menu-languages-list nil)
(defvar mule-menu-menu)
(add-to-list 'mule-menu-languages-list '("傳統漢語" "chinese-t-menu"))

(setq mule-menu-menu
      '((permanent
         (buffer "緩衝區"))
        ;;{{{  global
        (t
         (file "檔案"
               (new-file "存取新檔案…" :help "指定一個新檔案名稱，編輯檔案")
               (open-file "開啟檔案…" :help "讀取已存在的檔案到緩衝區")
               (dired "開啟目錄…" :help "讀取一個目錄並對目錄內的檔案進行作業")
               (insert-file "插入檔案…" :help "插入另一個檔案到目前緩衝區")
               (kill-buffer "關閉" :help "關閉目前緩衝區")
               (save-buffer "儲存" :help "儲存目前緩衝區到對應的檔案")
               (write-file "另存為…" :help "將目前緩衝區寫到另一個檔案")
               (revert-buffer "重新讀取" :help "從檔案中重新讀取到目前緩衝區")
               (recover-session "恢復對話" :help "從上次當機的對話中恢復")
               (print-buffer "列印緩衝區" :help "列印目前緩衝區，顯示頁碼標題")
               (print-region "列印區域" :help "列印標記和目前位置之間的區域")
               (ps-print-buffer-faces "使用 Postscript 列印緩衝區" :help "優質列印目前的緩衝區到 PostScript 印表機")
               (ps-print-region-faces "使用 Postscript 列印區域" :help "優質列印標記的區域到 PostScript 印表機")
               (ps-print-buffer "使用 Postscript 黑白列印緩衝區" :help "單色優質列印目前的緩衝區到 PostScript 印表機")
               (ps-print-region "使用 Postscript 黑白列印區域" :help "單色優質列印標記的區域到 PostScript 印表機")
               (split-window "分割窗格" :help "將目前選擇的窗格分割成兩個窗格")
               (one-window "取消分割" :help "使目前選擇的窗格填充整個視窗")
               (make-frame "新增視窗" :help "開啟一個新增視窗")
               (make-frame-on-display "新訊框於顯示…" :help "開啟新的訊框於另外的顯示")
               (delete-this-frame "刪除視窗" :help "刪除目前選擇的視窗")
               (exit-emacs "離開" :help "儲存未儲存的緩衝區，離開 Emacs"))
         (edit "編輯"
               (undo "撤消" :help "撤消最近一次作業")
               (cut "剪下")
               (copy "複製")
               (paste "貼上")
               (select-paste "選擇並貼上")
               (clear "清除" :help "刪除標記和目前位置之間區域內的文字")
               (mark-whole-buffer "全部選取" :help "選擇整個緩衝區")
               (search "搜尋"
                       (search-forward "向前搜尋字串" :help "搜尋轉寄用於字串")
                       (search-backward "向後搜尋字串" :help "向後搜尋用於字串")
                       (re-search-forward "向前使用正規運算式搜尋" :help "搜尋轉寄用於正規表示式")
                       (re-search-backward "向後使用正規運算式搜尋" :help "向後搜尋用於正規表示式")
                       (repeat-search-fwd "重複向前搜尋" :help "重複最後一筆搜尋轉寄")
                       (repeat-search-back "重複向後搜尋" :help "重複最後一筆向後搜尋")
                       (tags-srch "搜尋索引的檔案" :help "搜尋 regexp 於所有帶標檔案")
                       (tags-continue "繼續上一次索引搜尋" :help "繼續最後一筆標記搜尋作業")
                       (i-search "差異搜尋"
                                 (isearch-forward "向前搜尋字串" :help "向前搜尋您所輸入的字串")
                                 (isearch-backward "向後搜尋字串" :help "向後搜尋您所輸入的字串")
                                 (isearch-forward-regexp "向前使用正規運算式搜尋" :help "向前搜尋您所輸入的正規表示式")
                                 (isearch-backward-regexp "向後使用正規運算式搜尋" :help "向後搜尋您所輸入的正規表示式")))
               (replace "替換"
                        (query-replace "替換字串" :help "互動式置換字串，每次出現都提出詢問")
                        (query-replace-regexp "替換正規運算式" :help "互動式置換正規表示式，每次出現都提出詢問")
                        (tags-repl "在索引的檔案中替換" :help "互動式置換 regexp 於所有帶標檔案")
                        (tags-repl-continue "繼續上一次索引替換" :help "繼續最後一筆標記置換作業"))
               (goto "移動"
                     (go-to-line "移動到列…" :help "讀取列號並前往該列")
                     (go-to-pos "移動到位置…" :help "讀取數字 N 並前往緩衝區位置 N")
                     (beg-of-buf "移動到緩衝區開始")
                     (end-of-buf "移動到緩衝區末尾")
                     (find-tag "搜尋標記" :help "尋找定義的函式或變數")
                     (find-tag-otherw "在另一個窗格中搜尋標記" :help "在另外的視窗中尋找函式/變數定義")
                     (next-tag "搜尋下一個標記" :help "找下一個函式/變數吻合最後一筆標記名稱")
                     (next-tag-otherw "在新窗格中搜尋下一個標記" :help "在另外的視窗中找下一個函式/變數吻合最後一筆標記名稱")
                     (apropos-tags "模糊搜尋標記" :help "尋找函式/變數其名稱吻合 regexp")
                     (set-tags-name "設定標記檔案" :help "告訴標記命令該項標記所用的表格檔案"))
               (bookmark "書籤"
                         (jump "轉到書籤…")
                         (set "設定書籤…")
                         (insert "插入內容…")
                         (locate "插入路徑…")
                         (rename "重新命名書籤…")
                         (delete "刪除書籤…")
                         (edit "編輯書籤清單")
                         (save "儲存書籤")
                         (write "書籤另存為…")
                         (load "從檔案中匯入書籤…"))
               (fill "格式化" :help "在區域中填充文字以符合在左右邊界之間")
               (props "文字屬性"
                      (fc "字體"
                          (100 "預設")
                          (98 "加粗")
                          (105 "斜體")
                          (108 "粗斜體")
                          (117 "底線")
                          (111 "其他…"))
                      (fg "前景顏色"
                          (111 "其他…"))
                      (bg "背景顏色"
                          (111 "其他…"))
                      (sp "特殊屬性"
                          (114 "唯讀")
                          (118 "不可見")
                          (116 "無形的")
                          (115 "移除特殊"))
                      (ju "對齊"
                          (117 "取消填滿")
                          (108 "靠左對齊")
                          (114 "靠右對齊")
                          (98 "填滿段落")
                          (99 "置中對齊"))
                      (in "縮排"
                          (increase-left-margin "增加縮排")
                          (decrease-left-margin "減少縮排")
                          (increase-right-margin "向右增加縮排")
                          (decrease-right-margin "向右減少縮排"))
                      (rm "清除字體屬性")
                      (ra "清除文字屬性")
                      (dp "屬性說明")
                      (df "顯示字體")
                      (dc "顯示顏色")))
               (options "選項"
                  (transient-mark-mode "高亮度選取區域" :help "在作用區域中製作文字突顯顏色 (暫時性標記模式)")
                  (highlight-paren-mode "高亮度匹配的括號" :help "標示符合/不符合的括號游標所在 (顯示 Paren 模式)")
                  (truncate-lines "自動折列" :help "截斷螢幕上的長列")
                  (auto-fill-mode "在文字模式中字詞換列" :help "自動地填充文字在之間左右邊距 (自動填充)")
                  (case-fold-search "忽略大小寫搜尋" :help "在搜尋中忽略字母大小寫")
                  (cua-emulation-mode "使用 位移 移動選擇區域(CUA)" :help "使用位移的移動索引鍵到設定和延伸區域")
                  (cua-mode "使用 C-x/C-c/C-v 剪下貼上( CUA)" :help "使用 C-z/C-x/C-c/C-v 索引鍵用於復原/剪下/複製/貼上")
                  (uniquify "使用目錄為同名緩衝區命名" :help "Uniquify 緩衝區名稱由加入上層目錄名稱")
                  (save-place "在暫時檔案中儲存置放" :help "造訪檔案的前一個執行階段時重新啟動 Emacs")
                  (blink-cursor-mode "游標閃動" :help "是否游標閃動 (閃動游標模式)")
                  (debug-on-error "錯誤時進行除錯" :help "發生錯誤信號時進入 Lisp 除錯程式")
                  (debug-on-quit "使用 C-g 離開時進行除錯" :help "按下 C-g 時進入 Lisp 除錯程式")
                  (mule "Mule (多國語言環境)"
                        (set-language-environment "設定語言環境"
                                                  (Default "預設")
                                                  (Chinese "漢語")
                                                  (Cyrillic "斯拉夫語")
                                                  (Indian "印度語")
                                                  (English "英語")
                                                  (ASCII "ASCII")
                                                  (Ethiopic "衣索比亞語")
                                                  (European "歐洲諸語")
                                                  (Turkish "土耳其語")
                                                  (Greek "希臘語")
                                                  (Hebrew "希伯來語")
                                                  (Windows-1255 "Windows-1255")
                                                  (Japanese "日語")
                                                  (Korean "韓語")
                                                  (Lao "老撾語")
                                                  (Thai "泰語")
                                                  (Tibetan "藏語")
                                                  (Vietnamese "越南語")
                                                  (IPA "IPA")
                                                  (UTF-8 "UTF-8"))
                        (toggle-input-method "切換輸入法")
                        (set-input-method "選擇輸入法…")
                        (set-various-coding-system "選擇編碼系統"
                                                   (universal-coding-system-argument "為下一個命令" :help "編碼系統為使用的由下一個命令")
                                                   (set-buffer-file-coding-system "為儲存目前緩衝區" :help "如何到編碼這個緩衝區時儲存")
                                                   (revert-buffer-with-coding-system "為重新讀取檔案" :help "即時重讀這個檔案並使用指定的編碼系統")
                                                   (set-file-name-coding-system "為檔案名稱" :help "如何到解碼/編碼檔案名稱")
                                                   (set-keyboard-coding-system "鍵盤" :help "如何到解碼鍵盤輸入")
                                                   (set-terminal-coding-system "終端機" :help "如何到編碼終端機輸出")
                                                   (set-selection-coding-system "X選擇/剪下板" :help "如何編/解碼資料到/從選擇/剪貼簿")
                                                   (set-next-selection-coding-system "為下一次X選擇" :help "如何編/解碼下一個選擇/剪貼簿作業")
                                                   (set-buffer-process-coding-system "為子處理序I/O" :help "如何編/解碼 I/O 從/到子程序連線到這個緩衝區"))
                        (view-hello-file "顯示多國語言文字" :help "顯示在許多語言集中表示哈囉的檔案")
                        (describe-language-environment "語言環境說明"
                                                       (Default "預設")
                                                       (Chinese "漢語")
                                                       (Cyrillic "斯拉夫語")
                                                       (Indian "印度語")
                                                       (English "英語")
                                                       (ASCII "ASCII")
                                                       (Ethiopic "衣索比亞語")
                                                       (European "歐洲諸語")
                                                       (Turkish "土耳其語")
                                                       (Greek "希臘語")
                                                       (Hebrew "希伯來語")
                                                       (Windows-1255 "Windows-1255")
                                                       (Japanese "日語")
                                                       (Korean "韓語")
                                                       (Lao "老撾語")
                                                       (Thai "泰語")
                                                       (Tibetan "藏語")
                                                       (Vietnamese "越南語")
                                                       (IPA "IPA")
                                                       (UTF-8 "UTF-8"))
                        (describe-input-method "輸入法說明…" :help "鍵盤布局用於特定的輸入法")
                        (describe-coding-system "編碼系統說明…")
                        (list-character-sets "字元集清單" :help "顯示表格的可用字元集")
                        (mule-diag "顯示所有 Mule 狀態" :help "顯示多語言環境設定值"))
                  (showhide "顯示/隱藏"
                            (showhide-tool-bar "工具列" :help "輪值工具列於/關閉")
                            (menu-bar-mode "功能表列" :help "切換功能表列於/關閉")
                            (showhide-tooltip-mode "提示" :help "切換工具提示於/關閉")
                            (showhide-scroll-bar "捲動欄"
                                                 (none "無" :help "關閉捲動軸")
                                                 (left "左側" :help "捲動軸左側的側邊")
                                                 (right "右側" :help "捲動軸右側的側邊"))
                            (showhide-fringe "邊緣"
                                             (none "無" :help "關閉 fringe")
                                             (left "左側" :help "Fringe 只有左側的側邊")
                                             (right "右側" :help "Fringe 只有右側的側邊")
                                             (default "預設" :help "預設寬度 fringe 於兩者左右側邊")
                                             (customize "自訂" :help "詳細的客製化的 fringe")
                                             (indicate-empty-lines "清除空行指示" :help "指出 fringe 中的尾隨空列")
                                             (showhide-fringe-ind "緩衝區邊界"
                                                                  (none "無" :help "隱藏所有緩衝區邊界指示器和箭頭")
                                                                  (left "在左邊緣" :help "顯示緩衝區邊界和箭頭在左 fringe 中")
                                                                  (right "在右邊緣" :help "顯示緩衝區邊界和箭頭在右 fringe 中")
                                                                  (box "相反，無箭頭" :help "顯示頂/底部指示器在相反 fringes 中，無箭頭")
                                                                  (mixed "相反，箭頭右側" :help "顯示頂/底部指示器在相反 fringes 中，箭頭在右")
                                                                  (customize "其他 (自訂)" :help "額外選擇可用透過自訂緩衝區")))
                            (showhide-speedbar "速度條" :help "顯示速度條、快速導航訊框")
                            (showhide-date-time "時間、負載和郵件" :help "在模式列中顯示時間、系統負載平均值和郵件狀態")
                            (showhide-battery "電池狀態" :help "在模式列中顯示電池狀態資訊")
                            (size-indication-mode "大小指示" :help "在模式列中顯示大小的緩衝區")
                            (line-number-mode "列號" :help "在模式列中顯示目前的列號")
                            (column-number-mode "列號" :help "在模式列中顯示目前的欄號"))
                  (mouse-set-font "設定字型/字型集…" :help "選取字型從已知字型清單的/字型集")
                  (save "儲存選項" :help "儲存選項設定從選單以上的")
                  (customize "自訂 Emacs"
                             (customize "最頂層自訂群組" :help "主群組稱為「Emacs」")
                             (customize-browse "瀏覽自訂群組" :help "瀏覽所有客製化群組")
                             (customize-saved "儲存的選項" :help "自訂在之前儲存的選項")
                             (customize-changed-options "新選項…" :help "選項已加入或變更到最近的 Emacs 版本中")
                             (customize-option "指定選項…" :help "自訂值的特定選項")
                             (customize-face "指定字體…" :help "自訂屬性的特定的字體")
                             (customize-group "指定群組…" :help "自訂設定值的特定的群組")
                             (customize-apropos "設定所有匹配正規表示式的…" :help "瀏覽可客製化的設定值其名稱吻合 regexp")
                             (customize-apropos-options "設定匹配正規表示式的選項…" :help "瀏覽選項其名稱吻合 regexp")
                             (customize-apropos-faces "設定匹配正規表示式的字體…" :help "瀏覽字體其名稱吻合 regexp")
                             (customize-apropos-groups "設定匹配正規表示式的群組…" :help "瀏覽群組其名稱吻合 regexp")))
         (buffer "緩衝區"
                 (next-buffer "次一個緩衝區" :help "切換到循環排序的次一個緩衝區")
                 (previous-buffer "前一個緩衝區" :help "切換到循環排序的前一個緩衝區")
                 (select-named-buffer "選擇緩衝區…" :help "提示用於緩衝區名稱，而選取該緩衝區在之中目前的視窗")
                 (list-all-buffers "列出所有緩衝區" :help "快顯視窗列表所有 emacs 緩衝區"))
         (tools "工具"
                (grep "在檔案中尋找(使用 grep)…" :help "搜尋檔案用於字串或 regexps (與 grep)")
                (compile "編譯…" :help "調用編譯器或製作，檢視編譯錯誤")
                (shell "執行 Shell 命令…" :help "調用 Shell 命令和擷取它的輸出")
                (shell-on-region "對區域執行 Shell 命令…" :help "輸出標記的區域給 Shell 命令")
                (gdb "除錯(GDB)…" :help "在 Emacs 之內使用 GDB 除錯程式")
                (spell "拼寫檢查")
                (compare "檔案比較(Ediff)"
                         (ediff-files "兩個檔案…")
                         (ediff-buffers "兩個緩衝區…")
                         (ediff-files3 "三個檔案…")
                         (ediff-buffers3 "三個緩衝區…")
                         (ediff-directories "兩個目錄…")
                         (ediff-directories3 "三個目錄…")
                         (ediff-revision "檔案與修訂…")
                         (ediff-dir-revision "目錄修訂…")
                         (ediff-regions-wordwise "區域逐字…")
                         (ediff-regions-linewise "區域逐列…")
                         (ediff-windows-wordwise "視窗逐字…")
                         (ediff-windows-linewise "視窗逐列…")
                         (window "這個視窗和下一個視窗"))
                (ediff-merge "合併"
                             (ediff-merge-files "檔案…")
                             (ediff-merge-files-with-ancestor "檔案與原始節點…")
                             (ediff-merge-buffers "緩衝區…")
                             (ediff-merge-buffers-with-ancestor "緩衝區與原始節點…")
                             (ediff-merge-directories "目錄…")
                             (ediff-merge-directories-with-ancestor "目錄與原始節點…")
                             (ediff-merge-revisions "修訂…")
                             (ediff-merge-revisions-with-ancestor "修訂與原始節點…")
                             (ediff-merge-dir-revisions "目錄修訂…")
                             (ediff-merge-dir-revisions-with-ancestor "目錄修訂與原始節點…"))
                (epatch "套用修補"
                        (ediff-patch-file "到一個檔案…")
                        (ediff-patch-buffer "到一個緩衝區…"))
                (ediff-misc "Ediff Miscellanea"
                            (ediff-doc "Ediff 手動")
                            (ediff-cust "自訂 Ediff")
                            (eregistry "清單 Ediff 期間")
                            (emultiframe "切換使用的分隔控制緩衝區訊框"))
                (vc "版本控制"
                    (vc-register "註冊")
                    (vc-next-action "簽入/出")
                    (vc-update "更新到最後的版本")
                    (vc-revert-buffer "還原成基底版本")
                    (undo "復原最後一筆簽入")
                    (vc-insert-header "插入頁首")
                    (vc-print-log "顯示歷史")
                    (vc-update-change-log "更新變更記錄")
                    (vc-diff "比較與基底版本")
                    (vc-version-other-window "顯示其他版本")
                    (vc-rename-file "重新命名檔案")
                    (vc-annotate "註釋")
                    (vc-directory "VC 目錄清單")
                    (vc-create-snapshot "建立快照")
                    (vc-retrieve-snapshot "取回快照"))
                (pcl-cvs "PCL-CVS"
                         (examine "檢查目錄" :help "檢查目前的狀態的工作區")
                         (update "更新目錄" :help "擷取更新從儲存庫")
                         (checkout "簽出模組" :help "簽出模組從儲存庫")
                         (status "目錄狀態" :help "更多詳細的狀態的工作區"))
                (gnus "讀取網路新聞 (Gnus)" :help "讀取網路新聞群組")
                (rmail
                 (format "讀取郵件(使用%s)"
                         (read-mail-item-name))
                 :help "讀取您的郵件和回覆到它")
                (compose-mail
                 (format "傳送郵件(使用%s)"
                         (send-mail-item-name))
                 :help "發送郵件訊息")
                (directory-search "目錄搜尋")
                (calendar "行事曆")
                (calc "可程式設計的小算盤" :help "調用 Emacs 內建全部科學計算器")
                (simple-calculator "簡單的小算盤" :help "調用 Emacs 內建快速計算器")
                (games "遊戲"
                       (5x5 "5x5" :help "填入所有方形於 5x5 板")
                       (adventure "冒險" :help "Dunnet，文字冒險遊戲用於 Emacs")
                       (black-box "黑箱" :help "經由發射光束尋找在黑色框中的球")
                       (gomoku "Gomoku" :help "標記 5 contiguous 方形 (如同 tic-tac-toe)")
                       (hanoi "漢諾塔" :help "監看 Towers-of-Hanoi puzzle 解決經由 Emacs")
                       (life "生命" :help "監看如何 John Conway cellular 自動裝置 evolves")
                       (mult "乘法謎" :help "乘法動動腦")
                       (snake "貪食蛇" :help "移動蛇周圍避免碰撞")
                       (solitaire "撲克牌")
                       (tetris "俄羅斯方塊")
                       (yow "隨機引言" :help "顯示隨機 Zippy 引言")
                       (zone "區出" :help "播放 tricks 與 Emacs 顯示時 Emacs 是閒置")))
         (help-menu "求助"
                    (emacs-tutorial "Emacs 教學課程" :help "學習如何以使用 Emacs")
                    (emacs-tutorial-language-specific "Emacs 教學課程(選擇語言)…" :help "學習如何以使用 Emacs (選擇語言)")
                    (emacs-faq "Emacs FAQ")
                    (emacs-news "Emacs 新聞" :help "新特徵的這個版本")
                    (emacs-problems "Emacs 已知問題")
                    (report-emacs-bug "傳送 錯誤 報告…" :help "發送電子郵件到 Emacs 維護者")
                    (debian-emacs-readme "Debian 讀我檔案" :help "顯示讀我檔案.Debian 檔案")
                    (debian-emacs-news "Debian 新聞" :help "顯示新的.Debian 檔案")
                    (debian-emacs-changelog "Debian 變更記錄" :help "顯示 Debian 變更記錄")
                    (apropos "搜尋文件"
                             (emacs-glossary "Emacs 術語" :help "顯示字彙區段的 Emacs 手動")
                             (emacs-index-search "在使用者手冊中搜尋主題…" :help "在 Emacs 使用手冊中尋找描述的主旨")
                             (elisp-index-search "在 Elisp 手冊中搜尋主題…" :help "在 Emacs Lisp 手冊中尋找描述的主旨")
                             (emacs-key-command-node "在手冊中搜尋按鍵…" :help "顯示手動區段該描述鍵")
                             (emacs-command-node "在手冊中搜尋命令…" :help "顯示手動區段該描述命令")
                             (apropos-commands "搜尋命令…" :help "尋找命令其名稱吻合 regexp")
                             (apropos-variables "搜尋選項…" :help "尋找變數其名稱吻合 regexp")
                             (apropos-value "根據值搜尋選項…" :help "尋找變數其值吻合 regexp")
                             (apropos "搜尋物件…" :help "尋找符號的任何種類其名稱吻合 regexp")
                             (apropos-documentation "搜尋文件…" :help "尋找函式和變數其文件字串吻合 regexp"))
                    (describe "說明"
                              (describe-mode "緩衝區 模式 說明" :help "描述這個緩衝區主要的和次要模式")
                              (describe-key-1 "按鍵或滑鼠作業說明…" :help "顯示文件的命令約束到鍵，按一下，或功能表項目")
                              (describe-function "函式說明…" :help "顯示文件的函式/命令")
                              (describe-variable "變數說明…" :help "顯示文件的變數/選項")
                              (describe-face "字體 說明…" :help "顯示屬性的字體")
                              (describe-current-display-table "顯示表格 說明" :help "描述目前的顯示表格")
                              (list-keybindings "列出按鍵繫結" :help "顯示所有目前的按鍵聯結 (快速鍵)")
                              (describe-language-environment "列出語言環境"
                                                             (Default "預設")
                                                             (Chinese "漢語")
                                                             (Cyrillic "斯拉夫語")
                                                             (Indian "印度語")
                                                             (English "英語")
                                                             (ASCII "ASCII")
                                                             (Ethiopic "衣索比亞語")
                                                             (European "歐洲諸語")
                                                             (Turkish "土耳其語")
                                                             (Greek "希臘語")
                                                             (Hebrew "希伯來語")
                                                             (Windows-1255 "Windows-1255")
                                                             (Japanese "日語")
                                                             (Korean "韓語")
                                                             (Lao "老撾語")
                                                             (Thai "泰語")
                                                             (Tibetan "藏語")
                                                             (Vietnamese "越南語")
                                                             (IPA "IPA")
                                                             (UTF-8 "UTF-8"))
                              (describe-input-method "輸入法說明…" :help "鍵盤布局用於特定的輸入法")
                              (describe-coding-system "編碼系統說明…")
                              (describe-coding-system-briefly "編碼系統說明(簡短)…")
                              (mule-diag "顯示所有 Mule 狀態" :help "顯示多語言環境設定值"))
                    (emacs-manual "檢視 Emacs 手冊" :help "全部文件的 Emacs 特徵")
                    (manuals "更多手冊"
                             (info-elintro "Emacs Lisp 簡介" :help "讀取介紹到 Emacs Lisp 程式設計")
                             (info-elisp "Emacs Lisp 參考手冊" :help "讀取 Emacs Lisp 參考手動")
                             (info "其他手冊(資訊)" :help "讀取任何的已安裝的手冊")
                             (info-apropos "在所有手冊中搜尋主題…" :help "在所有已安裝的手冊中尋找描述的主旨")
                             (order-emacs-manuals "定序手冊" :help "如何到排序手冊從自由軟體基金會")
                             (man "檢視使用手冊…" :help "線上手冊用於外部命令和函式庫"))
                    (finder-by-keyword "搜尋 Emacs 封包" :help "尋找套件和特徵由關鍵字")
                    (about "關於 Emacs" :help "顯示版本編號，著作權資訊，而基本說明")
                    (more "其他套件" :help "分隔地用於 Emacs 中已經發行的 Lisp 套件")
                    (describe-distribution "獲取新版本" :help "如何到取得最後的版本的 Emacs")
                    (describe-copying "版權" :help "顯示 Emacs 授權 (GPL)")
                    (describe-no-warranty "(非) 擔保" :help "解釋該 Emacs 沒有任何擔保")
                    (eliza "Emacs 心理醫生" :help "我們的醫生將協助您有較好感覺")))
        ;;}}}
        ;;{{{  outline-mode
        ((eq major-mode 'outline-mode)
         (headings "標頭"
                   (outline-up-heading "向上")
                   (outline-next-visible-heading "下一步")
                   (outline-previous-visible-heading "前一個")
                   (outline-forward-same-level "下一個相同等級")
                   (outline-backward-same-level "前一個相同等級")
                   (outline-insert-heading "新標頭")
                   (copy "複製到砍除環")
                   (move-subtree-up "移動子樹向上")
                   (move-subtree-down "移動子樹向下")
                   (promote-subtree "升級子樹")
                   (demote-subtree "降級子樹"))
         (show "顯示"
               (show-all "全部顯示")
               (show-entry "顯示項目")
               (show-branches "顯示分支")
               (show-children "顯示孩子")
               (show-subtree "顯示子樹"))
         (hide "隱藏"
               (hide-leaves "隱藏樹葉")
               (hide-body "隱藏主體")
               (hide-entry "隱藏項目")
               (hide-subtree "隱藏子樹")
               (hide-sublevels "隱藏子層級")
               (hide-other "隱藏其他")))
        ;;}}}
        ;;{{{  outline-minor-mode
        (outline-minor-mode
         (outline "大綱"
                  (outline-up-heading "向上一級")
                  (outline-next-visible-heading "下一區段")
                  (outline-previous-visible-heading "上一區段")
                  (outline-forward-same-level "下一個相同等級")
                  (outline-backward-same-level "前一個相同等級")
                  (outline-insert-heading "新標頭")
                  (copy "複製到砍除環")
                  (move-subtree-up "移動子樹向上")
                  (move-subtree-down "移動子樹向下")
                  (promote-subtree "升級子樹")
                  (demote-subtree "降級子樹")
                  (show-all "顯示所有")
                  (show-entry "顯示項目")
                  (show-branches "顯示分支")
                  (show-children "顯示孩子")
                  (show-subtree "顯示子樹")
                  (hide-leaves "隱藏樹葉")
                  (hide-body "隱藏主體")
                  (hide-entry "隱藏項目")
                  (hide-subtree "隱藏子樹")
                  (hide-sublevels "隱藏子層級")
                  (hide-other "隱藏其他")))
        ;;}}}
        ((and (featurep 'session)
              (key-binding [menu-bar file Open\.\.\.recently\ changed]))
         (file "檔案"
               (Open\.\.\.recently\ changed "開啟最近修改")
               (Open\.\.\.recently\ visited "開啟最近存取")))
        ((and (featurep 'template)
              (key-binding [menu-bar file template-new-file]))
         (file "檔案"
               (template-new-file "使用範本新增檔案" :help "使用範本建立一個新檔案")))
        ;;{{{  hs-minor-mode
        (hs-minor-mode
         (Hide/Show "隱藏/顯示"
            (Hide\ Block "顯示塊")
            (Show\ Block "顯示區塊")
            (Hide\ All "隱藏所有")
            (Show\ All "全部顯示")
            (Hide\ Level "隱藏等級")
            (Toggle\ Hiding "切換隱藏中")))
        ;;}}}
        ((and (featurep 'mule-menu)
              (key-binding [menu-bar options mule set-menu-language]))
         (options "選項"
                  (mule "Mule (多國語言環境)"
                        (set-menu-language "設定選單語言"))))
        ;;{{{  emacs-lisp-mode
        ((eq major-mode 'emacs-lisp-mode)
         (emacs-lisp "Emacs-Lisp"
                     (indent-line "縮排行")
                     (indent-region "縮排區域")
                     (comment-region "註釋整個區域")
                     (eval-sexp "對前一個 S-運算式求值")
                     (eval-region "對區域求值")
                     (eval-buffer "對整個緩衝區求值")
                     (byte-compile "位元組編譯檔案")
                     (emacs-byte-compile-and-load "位元組編譯並匯入")
                     (byte-recompile "位元組編譯整個目錄…")
                     (edebug-defun "使函式可除錯")))
        ;;}}}
        ;;{{{  ibuffer-mode
        ((eq major-mode 'ibuffer-mode)
         (operate "作業"
                  (do-view "檢視")
                  (do-view-other-frame "檢視 (分隔訊框)")
                  (do-save "儲存")
                  (do-replace-regexp "替換 (regexp)…")
                  (do-query-replace "查詢置換…")
                  (do-query-replace-regexp "查詢置換 (regexp)…")
                  (do-print "列印")
                  (do-toggle-modified "切換修改旗標")
                  (do-revert "回復")
                  (do-rename-uniquely "重新命名唯一地")
                  (do-delete "砍除")
                  (do-occur "清單列吻合中…")
                  (do-shell-command-pipe "管道到 Shell 命令…")
                  (do-shell-command-pipe-replace "管道到 Shell 命令 (置換)…")
                  (do-shell-command-file "Shell 命令於緩衝區檔案…")
                  (do-eval "求值…")
                  (do-view-and-eval "求值(觀看緩衝區)…"))
         (view "瀏覽"
               (visit-buffer "瀏覽這個緩衝區")
               (visit-buffer-other-window "在其他窗格中瀏覽")
               (visit-buffer-other-frame "在其他視窗中瀏覽")
               (ibuffer-update "更新")
               (switch-format "切換顯示格式")
               (sort "排序"
                     (do-sort-by-major-mode "按主模式排序")
                     (do-sort-by-size "按緩衝區大小排序")
                     (do-sort-by-alphabetic "字典序")
                     (do-sort-by-recency "按存取時間排序")
                     (invert-sorting "反向排序")
                     (toggle-sorting-mode "切換排序模式"))
               (filter "過濾器"
                       (filter-disable "全部停用篩選")
                       (filter-by-mode "加入篩選器由主要的模式使用中…")
                       (filter-by-name "加入篩選器由緩衝區名稱…")
                       (filter-by-filename "加入篩選器由檔名…")
                       (filter-by-size-lt "加入篩選器依大小少於…")
                       (filter-by-size-gt "加入篩選器依大小大於…")
                       (filter-by-content "加入篩選器由內容 (regexp)…")
                       (filter-by-predicate "加入篩選器由 Lisp 述詞…")
                       (pop-filter "移除頂篩選器")
                       (or-filter "或頂兩篩選器")
                       (negate-filter "Negate 頂篩選器")
                       (decompose-filter "Decompose 頂篩選器")
                       (exchange-filters "交換頂兩篩選器")
                       (save-filters "永久儲存目前的篩選器…")
                       (switch-to-saved-filters "還原永久儲存的篩選器…")
                       (add-saved-filters "加入到永久儲存的篩選器…")
                       (delete-saved-filters "刪除永久儲存的篩選器…"))
               (filter-groups "篩選器群組"
                              (filters-to-filter-group "建立篩選器群組從目前的篩選器…")
                              (forward-filter-group "移動點到下一個篩選器群組")
                              (backward-filter-group "移動點到前一個篩選器群組")
                              (jump-to-filter-group "移動點到特定的篩選器群組…")
                              (kill-filter-group "砍除篩選器群組具名的…")
                              (yank-filter-group "Yank 最後一筆砍除篩選器群組之前…")
                              (clear-filter-groups "全部移除篩選器群組")
                              (pop-filter-group "Decompose 篩選器群組…")
                              (save-filter-groups "永久儲存目前的篩選器群組…")
                              (switch-to-saved-filter-groups "還原永久儲存的篩選器…")
                              (delete-saved-filter-groups "刪除永久儲存的篩選器群組…")
                              (set-filter-groups-by-mode "設定目前的篩選器群組到篩選器由模式"))
               (diff-with-file "Diff 與檔案")
               (auto-mode "切換自動模式")
               (customize "自訂 Ibuffer"))
         (mark "標記"
               (toggle-marks "反轉標記")
               (mark-forward "標記")
               (unmark-forward "取消標記")
               (mark-by-mode "按模式標記…")
               (mark-modified-buffers "標記已經修改緩衝區")
               (mark-unsaved-buffers "標記未儲存的緩衝區")
               (mark-read-only-buffers "標記唯讀緩衝區")
               (mark-special-buffers "標記特殊緩衝區")
               (mark-dired-buffers "標記 dired 緩衝區")
               (mark-dissociated-buffers "標記不相關緩衝區")
               (mark-help-buffers "標記說明緩衝區")
               (mark-compressed-file-buffers "標記壓縮過的檔案緩衝區")
               (mark-old-buffers "標記舊的緩衝區")
               (unmark-all "取消標記所有")
               (mark-by-name-regexp "標記由緩衝區名稱 (regexp)…")
               (mark-by-mode-regexp "標記由主要的模式 (regexp)…")
               (mark-by-file-name-regexp "標記由檔案名稱 (regexp)…")))
        ;;}}}
        ;;{{{  dired-mode
        ((eq major-mode 'dired-mode)
         (operate "作業"
                  (copy "複製到…" :help "複製目前的檔案或所有標記的檔案")
                  (rename "重新命名為…" :help "重新命名目前的檔案或移動標記的檔案")
                  (delete "刪除" :help "刪除目前的檔案或所有標記的檔案")
                  (find-files "尋找檔案" :help "尋找目前的或標記的檔案")
                  (command "Shell 命令…" :help "運行 Shell 命令於每個的標記的檔案")
                  (symlink "符號連結到…" :help "製作符號連結用於目前的或標記的檔案")
                  (relsymlink "相對的符號連結到…" :help "製作相對的符號連結用於目前的或標記的檔案")
                  (hardlink "硬式連結到…" :help "製作強制連結用於目前的或標記的檔案")
                  (print "列印…" :help "詢問列印命令和列印標記的檔案")
                  (compress "壓縮" :help "壓縮/解壓縮標記的檔案")
                  (compile "Byte-compile" :help "位元組編譯標記的 Emacs Lisp 檔案")
                  (load "載入" :help "載入標記的 Emacs Lisp 檔案")
                  (touch "變更時間戳記…" :help "變更時間戳記的標記的檔案")
                  (chmod "變更模式…" :help "變更模式 (屬性) 的標記的檔案")
                  (chgrp "變更群組…" :help "變更群組的標記的檔案")
                  (chown "變更擁有者…" :help "變更擁有者的標記的檔案")
                  (search "搜尋檔案…" :help "搜尋標記的檔案用於 regexp")
                  (query-replace "查詢檔案中置換…" :help "在標記的檔案中置換 regexp")
                  (tumme-display-thumbs "顯示縮圖" :help "顯示縮圖用於目前的或標記的影像檔")
                  (tumme-dired-comment-files "加入影像註釋…" :help "加入影像註釋到目前的或標記的檔案")
                  (tumme-tag-files "加入影像標記…" :help "加入影像標記到目前的或標記的檔案")
                  (tumme-delete-tag "刪除影像標記…" :help "刪除影像標記從目前的或標記的檔案"))
         (mark "標記"
               (toggle-marks "切換標記" :help "標記取消標記的檔案，取消標記標記的一個")
               (mark "標記" :help "標記目前的列檔案用於未來計算")
               (unmark "取消標記" :help "取消標記或 unflag 目前的列檔案")
               (deletion "旗標" :help "旗標目前的列檔案用於刪除")
               (auto-save-files "旗標自動儲存檔案" :help "旗標自動儲存檔案用於刪除")
               (backup-files "旗標備份檔案" :help "旗標所有備份檔案用於刪除")
               (garbage-files "旗標 Garbage 檔案" :help "旗標 unneeded 檔案用於刪除")
               (flag-extension "旗標延伸…" :help "旗標檔案與某些延伸用於刪除")
               (executables "標記可執行檔案" :help "標記所有可執行檔")
               (directory "標記舊的備份" :help "旗標舊的已編號備份用於刪除")
               (directories "標記目錄" :help "標記所有目錄除了「.」和「..」")
               (symlinks "標記符號連結" :help "標記所有符號連結")
               (mark-extension "標記延伸…" :help "標記檔案與某些延伸")
               (mark-omitted "標記省略" :help "標記檔案吻合中「dired-omit-files」和「dired-omit-extensions」")
               (unmark-all "取消標記所有")
               (marks "變更標記…" :help "置換標誌與另外的字元")
               (next "下一個標記" :help "移動到下一個標記的檔案")
               (prev "前一個標記" :help "移動到前一個標記的檔案"))
         (regexp "正規表示式"
                 (mark-cont "標記包含中…" :help "標記檔案其內容相符者 regexp")
                 (mark "標記…" :help "標記檔案吻合 regexp 用於未來計算")
                 (flag "旗標…" :help "旗標檔案吻合 regexp 用於刪除")
                 (copy "複製…" :help "複製標記的檔案吻合 regexp")
                 (rename "重新命名…" :help "重新命名標記的檔案吻合 regexp")
                 (symlink "符號連結…" :help "製作符號連結用於檔案吻合 regexp")
                 (relsymlink-regexp "相對的符號連結…" :help "製作相對的符號連結用於檔案吻合 regexp")
                 (hardlink "硬式連結…" :help "製作強制連結用於檔案吻合 regexp")
                 (upcase "大寫" :help "重新命名標記的檔案到大寫名稱")
                 (downcase "小寫" :help "重新命名標記的檔案到小寫名稱")
                 (tumme-mark-tagged-files "標記從影像標記…" :help "標記檔案其影像標記相符者 regexp"))
         (immediate "立即"
                    (wdired-change-to-wdired-mode "修改檔案名稱")
                    (wdired-mode "修改多個檔案名稱")
                    (create-directory "建立目錄…")
                    (find-file "尋找這個檔案" :help "編輯檔案游標所在")
                    (find-file-other-window "在其他視窗中尋找" :help "在其他視窗中編輯檔案游標所在")
                    (display "在其他視窗中顯示" :help "在其他視窗中顯示檔案游標所在")
                    (view "檢視這個檔案" :help "在唯讀模式中檢查檔案游標所在")
                    (diff "差異化…" :help "比較檔案游標所在與另外的檔案")
                    (backup-diff "比較與備份" :help "差異化游標所在檔案與它的最後備份")
                    (compare-directories "比較目錄…" :help "在兩份列出目錄的緩衝區中標記檔案與不同的屬性")
                    (omit-mode "省略模式" :help "啟用或停用省略「不感興趣」的檔案")
                    (revert-buffer "重新整理" :help "更新內容的顯示目錄")
                    (tumme-dired-display-image "顯示影像" :help "在分隔視窗中顯示大小的影像")
                    (tumme-dired-display-external "顯示影像外部地" :help "在外部檢視器中顯示影像"))
         (subdir "子目錄"
                 (insert "插入這個子目錄" :help "插入內容的子目錄")
                 (next-dirline "下一行" :help "移動到前一個 directory-file 列")
                 (prev-dirline "前一行" :help "移動到下一個 directory-file 列")
                 (next-subdir "下一個子目錄" :help "前往下一個子目錄頁首列")
                 (prev-subdir "前一個子目錄" :help "前往前一個子目錄頁首列")
                 (up "上一級目錄" :help "編輯上層目錄")
                 (tree-up "樹向上" :help "前往先子目錄頁首向上樹")
                 (tree-down "樹向下" :help "前往先子目錄頁首向下樹")
                 (hide-subdir "隱藏/顯示子目錄" :help "隱藏或解除隱藏目前的目錄清單")
                 (hide-all "隱藏所有" :help "隱藏所有子目錄，只保留頁首列")))
        ;;}}}
        ;;{{{  fold-mode
        (fold-mode-active
         (fold "折疊"
               (fold-hide "隱藏折疊")
               (fold-show "顯示折疊")
               (fold-show-all "顯示所有")
               (fold-whole-buffer "折疊整個緩衝區")
               (fold-region "建立折疊")))
        ;;}}}
        ;;{{{  cperl-mode
        ((eq major-mode 'cperl-mode)
         (Perl "Perl"
               (Beginning\ of\ function "函式開始")
               (End\ of\ function "結束的函式")
               (Mark\ function "標記函式")
               (Indent\ expression "縮排運算式")
               (Fill\ paragraph/comment "填滿段落/註釋")
               (Line\ up\ a\ construction "貼齊建構")
               (Invert\ if/unless/while\ etc "反相如果/除非/當等項")
               (Regexp "Regexp"
                       (Beautify "美化")
                       (Beautify\ one\ level\ deep "更深一級美化")
                       (Beautify\ a\ group "美化群組")
                       (Beautify\ a\ group\ one\ level\ deep "美化群組更深一級")
                       (Contract\ a\ group "合約群組")
                       (Contract\ groups "合約群組"))
               (Refresh\ \"hard\"\ constructions "重新顯示「硬式」建構")
               (Indent\ region "縮排區域")
               (Comment\ region "註釋區域")
               (Uncomment\ region "取消註釋區域")
               (Run "運行")
               (Kill "砍除")
               (Next\ error "下一個錯誤")
               (Check\ syntax "檢查語法")
               (Debugger "除錯程式")
               (Tools "工具"
                      (Imenu "Imenu")
                      (Insert\ spaces\ if\ needed "插入空格如果所需的")
                      (Class\ Hierarchy\ from\ TAGS "類別階層從標記")
                      (CPerl\ pretty\ print\ \(exprmntl\) "CPerl 優質列印(實驗性質)")
                      (Imenu\ on\ info "Imenu 於資訊")
                      (Tags "標記"
                            (Create\ tags\ for\ current\ file "建立標記用於目前的檔案")
                            (Add\ tags\ for\ current\ file "加入標記用於目前的檔案")
                            (Create\ tags\ for\ Perl\ files\ in\ directory "在目錄中建立標記用於 Perl 檔案")
                            (Add\ tags\ for\ Perl\ files\ in\ directory "在目錄中加入標記用於 Perl 檔案")
                            (Create\ tags\ for\ Perl\ files\ in\ \(sub\)directories "在(子)目錄中建立標記用於 Perl 檔案")
                            (Add\ tags\ for\ Perl\ files\ in\ \(sub\)directories "在(子)目錄中加入標記用於 Perl 檔案")))
               (Perl\ docs "Perl docs"
                           (Define\ word\ at\ point "定義字詞於點")
                           (Help\ on\ function "說明於函式")
                           (Help\ on\ function\ at\ point "說明於函式於點")
                           (Help\ on\ symbol\ at\ point "說明於符號於點")
                           (Perldoc "Perldoc")
                           (Perldoc\ on\ word\ at\ point "Perldoc 於字詞於點")
                           (View\ manpage\ of\ POD\ in\ this\ file "在這個檔案中檢視 manpage 的 POD")
                           (Auto-help\ on "Auto-help 於")
                           (Auto-help\ off "Auto-help 關閉"))
               (Toggle\.\.\. "切換…"
                             (Auto\ newline "自動新列")
                             (Electric\ parens "Electric parens")
                             (Electric\ keywords "Electric 關鍵字")
                             (Fix\ whitespace\ on\ indent "修正空白於縮排")
                             (Auto-help\ on\ Perl\ constructs "Auto-help 於 Perl 構造")
                             (Auto\ fill "自動填充"))
               (Indent\ styles\.\.\. "縮排樣式…"
                                     (CPerl "CPerl")
                                     (PerlStyle "PerlStyle")
                                     (GNU "GNU")
                                     (C++ "C++")
                                     (FSF "FSF")
                                     (BSD "BSD")
                                     (Whitesmith "Whitesmith")
                                     (Current "目前的")
                                     (Memorized "已記憶的"))
               (Micro-docs "Micro-docs"
                           (Tips "秘訣")
                           (Problems "問題")
                           (Speed "速度")
                           (Praise "Praise")
                           (Faces "字體")
                           (CPerl\ mode "CPerl 模式")
                           (CPerl\ version "CPerl 版本"))))
        ;;}}}
        ((eq major-mode 'c-mode)
         (C "C"
            (Comment\ Out\ Region "註釋區域")
            (Uncomment\ Region "取消註釋區域")
            (Indent\ Expression "縮排運算式")
            (Indent\ Line\ or\ Region "縮排列或區域")
            (Fill\ Comment\ Paragraph "填充註釋段落")
            (Backward\ Statement "退一步敘述")
            (Forward\ Statement "轉寄敘述")
            (Up\ Conditional "向上條件")
            (Backward\ Conditional "退一步條件")
            (Forward\ Conditional "轉寄條件")
            (Macro\ Expand\ Region "巨集展開區域")
            (Backslashify "Backslashify")
            (Toggle\.\.\. "切換…"
                          (Syntactic\ indentation "語意縮排")
                          (Electric\ mode "電子模式")
                          (Auto\ newline "自動新列")
                          (Hungry\ delete "儘可能刪除")
                          (Subword\ mode "部份字詞模式"))))
        ((eq major-mode 'c-mode)
         (C++ "C++"
              (Comment\ Out\ Region "加入註釋區域")
              (Uncomment\ Region "取消註釋區域")
              (Indent\ Expression "縮排運算式")
              (Indent\ Line\ or\ Region "縮排列或區域")
              (Fill\ Comment\ Paragraph "填充註釋段落")
              (Backward\ Statement "退一步敘述")
              (Forward\ Statement "轉寄敘述")
              (Up\ Conditional "向上條件")
              (Backward\ Conditional "退一步條件")
              (Forward\ Conditional "轉寄條件")
              (Macro\ Expand\ Region "巨集展開區域")
              (Backslashify "Backslashify")
              (Toggle\.\.\. "切換…"
                            (Syntactic\ indentation "語意縮排")
                            (Electric\ mode "電子模式")
                            (Auto\ newline "自動新列")
                            (Hungry\ delete "儘可能刪除")
                            (Subword\ mode "部份字詞模式"))))
        ))

;;; chinese-t-menu.el ends here
