;;; chinese-menu.el --- Add chinese menu bar -*- coding: utf-8 -*-

;; Copyright 2006 Ye Wenbin
;;
;; Author: wenbinye@163.com
;; Time-stamp: <Ye Wenbin 2006-12-26 19:01:07>
;; Version: $Id: chinese-menu.el,v 1.1 2006/12/24 09:14:29 ywb Exp ywb $
;; Keywords: 
;; X-URL: not distributed yet

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

;;; Commentary:

;; Put this file into your load-path and the following into your ~/.emacs:
;; (require 'chinese-menu)
;; (require 'english-menu)
;; (require 'mule-menu)

;;; Code:

(provide 'chinese-menu)
(eval-when-compile
  (require 'cl))

(defvar mule-menu-languages-list nil)
(defvar mule-menu-menu)
(add-to-list 'mule-menu-languages-list '("中文" "chinese-menu"))

(setq mule-menu-menu
      '((permanent
         (buffer "缓冲区"))
        ;;{{{  global
        (t
         (file "文件"
               (new-file "访问新文件..." :help "指定一个新文件名，编辑文件")
               (open-file "打开文件..." :help "读取已存在的文件到缓冲区")
               (dired "打开目录..." :help "读取一个目录并对目录内的文件进行操作")
               (insert-file "插入文件..." :help "插入另一个文件到当前缓冲区")
               (kill-buffer "关闭" :help "关闭当前缓冲区")
               (save-buffer "保存" :help "保存当前缓冲区到对应的文件")
               (write-file "另存为..." :help "将当前缓冲区写到另一个文件")
               (revert-buffer "重新读入" :help "从文件中重新读入到当前缓冲区")
               (recover-session "恢复对话" :help "从上次崩溃的对话中恢复")
               (print-buffer "打印缓冲区" :help "打印当前缓冲区，显示页码标题")
               (print-region "打印区域" :help "打印标记和当前位置之间的区域")
               (ps-print-buffer-faces "使用Postscript打印缓冲区" :help "Pretty-print current buffer to PostScript printer")
               (ps-print-region-faces "使用Postscript打印区域" :help "Pretty-print marked region to PostScript printer")
               (ps-print-buffer "使用Postscript黑白打印缓冲区" :help "Pretty-print current buffer in black and white to PostScript printer")
               (ps-print-region "使用Postscript黑白打印区域" :help "Pretty-print marked region in black and white to PostScript printer")
               (split-window "分割窗格" :help "将当前选择的窗格分割成两个窗格")
               (one-window "取消分割" :help "使当前选择的窗格填充整个窗口")
               (make-frame "新建窗口" :help "打开一个新窗口")
               (make-frame-on-display "New Frame on Display..." :help "Open a new frame on another display")
               (delete-this-frame "删除窗口" :help "删除当前选择的窗口")
               (exit-emacs "退出" :help "保存未保存的缓冲区，退出 Emacs"))
         (edit "编辑"
               (undo "撤消" :help "撤消最近一次操作")
               (cut "剪切")
               (copy "复制")
               (paste "粘贴")
               (select-paste "选择并粘贴")
               (clear "清除" :help "删除标记和当前位置之间区域内的文字")
               (mark-whole-buffer "全部选中" :help "选择整个缓冲区")
               (search "查找"
                       (search-forward "向前查找字符串" :help "Search forward for a string")
                       (search-backward "向后查找字符串" :help "Search backwards for a string")
                       (re-search-forward "向前使用正则表达式搜索" :help "Search forward for a regular expression")
                       (re-search-backward "向后使用正则表达式搜索" :help "Search backwards for a regular expression")
                       (repeat-search-fwd "重复向前查找" :help "Repeat last search forward")
                       (repeat-search-back "重复向后查找" :help "Repeat last search backwards")
                       (tags-srch "查找索引的文件" :help "Search for a regexp in all tagged files")
                       (tags-continue "继续上一次索引查找" :help "Continue last tags search operation")
                       (i-search "增量查找"
                                 (isearch-forward "向前查找字符串" :help "Search forward for a string as you type it")
                                 (isearch-backward "向后查找字符串" :help "Search backwards for a string as you type it")
                                 (isearch-forward-regexp "向前使用正则表达式搜索" :help "Search forward for a regular expression as you type it")
                                 (isearch-backward-regexp "向后使用正则表达式搜索" :help "Search backwards for a regular expression as you type it")))
               (replace "替换"
                        (query-replace "替换字符串" :help "Replace string interactively, ask about each occurrence")
                        (query-replace-regexp "替换正则表达式" :help "Replace regular expression interactively, ask about each occurrence")
                        (tags-repl "在索引的文件中替换" :help "Interactively replace a regexp in all tagged files")
                        (tags-repl-continue "继续上一次索引替换" :help "Continue last tags replace operation"))
               (goto "移动"
                     (go-to-line "移动到行..." :help "Read a line number and go to that line")
                     (go-to-pos "移动到位置..." :help "Read a number N and go to buffer position N")
                     (beg-of-buf "移动到缓冲区开始")
                     (end-of-buf "移动到缓冲区末尾")
                     (find-tag "查找Tag" :help "Find definition of function or variable")
                     (find-tag-otherw "在另一个窗格中查找Tag" :help "Find function/variable definition in another window")
                     (next-tag "查找下一个Tag" :help "Find next function/variable matching last tag name")
                     (next-tag-otherw "在新窗格中查找下一个Tag" :help "Find next function/variable matching last tag name in another window")
                     (apropos-tags "模糊查找Tag" :help "Find function/variables whose names match regexp")
                     (set-tags-name "设置Tags文件" :help "Tell Tags commands which tag table file to use"))
               (bookmark "书签"
                         (jump "转到书签...")
                         (set "设置书签...")
                         (insert "插入内容...")
                         (locate "插入路径...")
                         (rename "重命名书签...")
                         (delete "删除书签...")
                         (edit "编辑书签列表")
                         (save "保存书签")
                         (write "书签另存为...")
                         (load "从文件中导入书签..."))
               (fill "格式化" :help "Fill text in region to fit between left and right margin")
               (props "文本属性"
                      (fc "Face"
                          (100 "默认")
                          (98 "加粗")
                          (105 "斜体")
                          (108 "粗斜体")
                          (117 "下划线")
                          (111 "其它..."))
                      (fg "前景颜色"
                          (111 "Other..."))
                      (bg "背景颜色"
                          (111 "Other..."))
                      (sp "特殊属性"
                          (114 "只读")
                          (118 "不可见")
                          (116 "Intangible")
                          (115 "Remove Special"))
                      (ju "对齐"
                          (117 "Unfilled")
                          (108 "左对齐")
                          (114 "右对齐")
                          (98 "两端对齐")
                          (99 "居中"))
                      (in "缩进"
                          (increase-left-margin "增加缩进")
                          (decrease-left-margin "减少缩进")
                          (increase-right-margin "向右增加缩进")
                          (decrease-right-margin "向右减少缩进"))
                      (rm "清除Face属性")
                      (ra "清除文本属性")
                      (dp "属性说明")
                      (df "显示Face")
                      (dc "显示颜色")))
               (options "选项"
                  (transient-mark-mode "高亮选中区域" :help "Make text in active region stand out in color (Transient Mark mode)")
                  (highlight-paren-mode "高亮匹配的括号" :help "Highlight matching/mismatched parentheses at cursor (Show Paren mode)")
                  (truncate-lines "自动折行" :help "Truncate long lines on the screen")
                  (auto-fill-mode "Word Wrap in Text Modes" :help "Automatically fill text between left and right margins (Auto Fill)")
                  (case-fold-search "忽略大小写搜索" :help "Ignore letter-case in search")
                  (cua-emulation-mode "使用Shift移动选择区域(CUA)" :help "Use shifted movement keys to set and extend the region.")
                  (cua-mode "使用C-x/C-c/C-v剪切粘贴(CUA)" :help "Use C-z/C-x/C-c/C-v keys for undo/cut/copy/paste")
                  (uniquify "使用目录为重名缓冲区命名" :help "Uniquify buffer names by adding parent directory names")
                  (save-place "Save Place in Files between Sessions" :help "Visit files of previous session when restarting Emacs")
                  (blink-cursor-mode "光标闪动" :help "Whether the cursor blinks (Blink Cursor mode)")
                  (debug-on-error "错误时进行调试" :help "Enter Lisp debugger when an error is signaled")
                  (debug-on-quit "使用C-g退出时进行调试" :help "Enter Lisp debugger when C-g is pressed")
                  (mule "Mule (多国语言环境)"
                        (set-language-environment "设置语言环境"
                                                  (Default "默认")
                                                  (Chinese "中文")
                                                  (Cyrillic "Cyrillic")
                                                  (Indian "Indian")
                                                  (English "English")
                                                  (ASCII "ASCII")
                                                  (Ethiopic "Ethiopic")
                                                  (European "European")
                                                  (Turkish "Turkish")
                                                  (Greek "Greek")
                                                  (Hebrew "Hebrew")
                                                  (Windows-1255 "Windows-1255")
                                                  (Japanese "Japanese")
                                                  (Korean "Korean")
                                                  (Lao "Lao")
                                                  (Thai "Thai")
                                                  (Tibetan "Tibetan")
                                                  (Vietnamese "Vietnamese")
                                                  (IPA "IPA")
                                                  (UTF-8 "UTF-8"))
                        (toggle-input-method "切换输入法")
                        (set-input-method "选择输入法...")
                        (set-various-coding-system "选择编码系统"
                                                   (universal-coding-system-argument "为下一个命令" :help "Coding system to be used by next command")
                                                   (set-buffer-file-coding-system "为保存当前缓冲区" :help "How to encode this buffer when saved")
                                                   (revert-buffer-with-coding-system "为重新读入文件" :help "Revisit this file immediately using specified coding system")
                                                   (set-file-name-coding-system "为文件名" :help "How to decode/encode file names")
                                                   (set-keyboard-coding-system "键盘" :help "How to decode keyboard input")
                                                   (set-terminal-coding-system "终端" :help "How to encode terminal output")
                                                   (set-selection-coding-system "X选择/剪切板" :help "How to en/decode data to/from selection/clipboard")
                                                   (set-next-selection-coding-system "为下一次X选择" :help "How to en/decode next selection/clipboard operation")
                                                   (set-buffer-process-coding-system "为子进程I/O" :help "How to en/decode I/O from/to subprocess connected to this buffer"))
                        (view-hello-file "显示多国语言文本" :help "Display file which says HELLO in many languages")
                        (describe-language-environment "语言环境说明"
                                                       (Default "默认")
                                                       (Chinese "中文")
                                                       (Cyrillic "Cyrillic")
                                                       (Indian "Indian")
                                                       (English "English")
                                                       (ASCII "ASCII")
                                                       (Ethiopic "Ethiopic")
                                                       (European "European")
                                                       (Turkish "Turkish")
                                                       (Greek "Greek")
                                                       (Hebrew "Hebrew")
                                                       (Windows-1255 "Windows-1255")
                                                       (Japanese "Japanese")
                                                       (Korean "Korean")
                                                       (Lao "Lao")
                                                       (Thai "Thai")
                                                       (Tibetan "Tibetan")
                                                       (Vietnamese "Vietnamese")
                                                       (IPA "IPA")
                                                       (UTF-8 "UTF-8"))
                        (describe-input-method "输入法说明..." :help "Keyboard layout for a specific input method")
                        (describe-coding-system "编码系统说明...")
                        (list-character-sets "字符集列表" :help "Show table of available character sets")
                        (mule-diag "显示所有Mule状态" :help "Display multilingual environment settings"))
                  (showhide "显示/隐藏"
                            (showhide-tool-bar "工具栏" :help "Turn tool-bar on/off")
                            (menu-bar-mode "菜单栏" :help "Toggle menu-bar on/off")
                            (showhide-tooltip-mode "提示" :help "Toggle tooltips on/off")
                            (showhide-scroll-bar "滚动栏"
                                                 (none "无" :help "Turn off scroll-bar")
                                                 (left "左侧" :help "Scroll-bar on the left side")
                                                 (right "右侧" :help "Scroll-bar on the right side"))
                            (showhide-fringe "边缘"
                                             (none "无" :help "Turn off fringe")
                                             (left "左侧" :help "Fringe only on the left side")
                                             (right "右侧" :help "Fringe only on the right side")
                                             (default "默认" :help "Default width fringe on both left and right side")
                                             (customize "自定义" :help "Detailed customization of fringe")
                                             (indicate-empty-lines "清除空行指示" :help "Indicate trailing empty lines in fringe")
                                             (showhide-fringe-ind "缓冲区边界"
                                                                  (none "无" :help "Hide all buffer boundary indicators and arrows")
                                                                  (left "在左边缘" :help "Show buffer boundaries and arrows in left fringe")
                                                                  (right "在右边缘" :help "Show buffer boundaries and arrows in right fringe")
                                                                  (box "Opposite, No Arrows" :help "Show top/bottom indicators in opposite fringes, no arrows")
                                                                  (mixed "Opposite, Arrows Right" :help "Show top/bottom indicators in opposite fringes, arrows in right")
                                                                  (customize "Other (Customize)" :help "Additional choices available through Custom buffer")))
                            (showhide-speedbar "Speedbar" :help "Display a Speedbar quick-navigation frame")
                            (showhide-date-time "时间，加载和邮件" :help "Display time, system load averages and mail status in mode line")
                            (showhide-battery "电池状态" :help "Display battery status information in mode line")
                            (size-indication-mode "大小指示" :help "Show the size of the buffer in the mode line")
                            (line-number-mode "行号" :help "Show the current line number in the mode line")
                            (column-number-mode "列号" :help "Show the current column number in the mode line"))
                  (mouse-set-font "设置字体/字体集..." :help "Select a font from list of known fonts/fontsets")
                  (save "保存选项" :help "Save options set from the menu above")
                  (customize "自定义Emacs"
                             (customize "最顶层自定义组" :help "The master group called `Emacs'")
                             (customize-browse "浏览自定义组" :help "Browse all customization groups")
                             (customize-saved "保存的选项" :help "Customize previously saved options")
                             (customize-changed-options "新选项..." :help "Options added or changed in recent Emacs versions")
                             (customize-option "指定选项..." :help "Customize value of specific option")
                             (customize-face "指定Face..." :help "Customize attributes of specific face")
                             (customize-group "指定组..." :help "Customize settings of specific group")
                             (customize-apropos "设置所有匹配正则的..." :help "Browse customizable settings whose names match regexp")
                             (customize-apropos-options "设置匹配正则的选项..." :help "Browse options whose names match regexp")
                             (customize-apropos-faces "设置匹配正则的Face..." :help "Browse faces whose names match regexp")
                             (customize-apropos-groups "设置匹配正则的组..." :help "Browse groups whose names match regexp")))
         (buffer "缓冲区"
                 (next-buffer "下一个缓冲区" :help "Switch to the \"next\" buffer in a cyclic order")
                 (previous-buffer "前一个缓冲区" :help "Switch to the \"previous\" buffer in a cyclic order")
                 (select-named-buffer "选择缓冲区..." :help "Prompt for a buffer name, and select that buffer in the current window")
                 (list-all-buffers "列出所有缓冲区" :help "Pop up a window listing all emacs buffers"))
         (tools "工具"
                (grep "在文件中查找(使用grep)..." :help "Search files for strings or regexps (with grep)")
                (compile "编译..." :help "Invoke compiler or Make, view compilation errors")
                (shell "运行Shell命令..." :help "Invoke a shell command and catch its output")
                (shell-on-region "对区域运行Shell命令..." :help "Pass marked region to a shell command")
                (gdb "调试(GDB)..." :help "Debug a program from within Emacs with GDB")
                (spell "拼写检查")
                (compare "文件比较(Ediff)"
                         (ediff-files "两个文件...")
                         (ediff-buffers "两个缓冲区...")
                         (ediff-files3 "三个文件...")
                         (ediff-buffers3 "三个缓冲区...")
                         (ediff-directories "两个目录...")
                         (ediff-directories3 "三个目录...")
                         (ediff-revision "File with Revision...")
                         (ediff-dir-revision "Directory Revisions...")
                         (ediff-regions-wordwise "Regions Word-by-word...")
                         (ediff-regions-linewise "Regions Line-by-line...")
                         (ediff-windows-wordwise "Windows Word-by-word...")
                         (ediff-windows-linewise "Windows Line-by-line...")
                         (window "This Window and Next Window"))
                (ediff-merge "合并"
                             (ediff-merge-files "文件...")
                             (ediff-merge-files-with-ancestor "Files with Ancestor...")
                             (ediff-merge-buffers "缓冲区...")
                             (ediff-merge-buffers-with-ancestor "Buffers with Ancestor...")
                             (ediff-merge-directories "目录...")
                             (ediff-merge-directories-with-ancestor "Directories with Ancestor...")
                             (ediff-merge-revisions "Revisions...")
                             (ediff-merge-revisions-with-ancestor "Revisions with Ancestor...")
                             (ediff-merge-dir-revisions "Directory Revisions...")
                             (ediff-merge-dir-revisions-with-ancestor "Directory Revisions with Ancestor..."))
                (epatch "应用补丁"
                        (ediff-patch-file "到一个文件...")
                        (ediff-patch-buffer "到一个缓冲区..."))
                (ediff-misc "Ediff Miscellanea"
                            (ediff-doc "Ediff Manual")
                            (ediff-cust "Customize Ediff")
                            (eregistry "List Ediff Sessions")
                            (emultiframe "Toggle use of separate control buffer frame"))
                (vc "版本控制"
                    (vc-register "注册")
                    (vc-next-action "Check In/Out")
                    (vc-update "Update to Latest Version")
                    (vc-revert-buffer "Revert to Base Version")
                    (undo "Undo Last Check-In")
                    (vc-insert-header "Insert Header")
                    (vc-print-log "Show History")
                    (vc-update-change-log "Update ChangeLog")
                    (vc-diff "Compare with Base Version")
                    (vc-version-other-window "Show Other Version")
                    (vc-rename-file "Rename File")
                    (vc-annotate "Annotate")
                    (vc-directory "VC Directory Listing")
                    (vc-create-snapshot "Create Snapshot")
                    (vc-retrieve-snapshot "Retrieve Snapshot"))
                (pcl-cvs "PCL-CVS"
                         (examine "Examine Directory" :help "Examine the current state of a workarea")
                         (update "Update Directory" :help "Fetch updates from the repository")
                         (checkout "Checkout Module" :help "Check out a module from the repository")
                         (status "Directory Status" :help "A more verbose status of a workarea"))
                (gnus "Read Net News (Gnus)" :help "Read network news groups")
                (rmail
                 (format "读取邮件(使用%s)"
                         (read-mail-item-name))
                 :help "Read your mail and reply to it")
                (compose-mail
                 (format "发送邮件(使用%s)"
                         (send-mail-item-name))
                 :help "Send a mail message")
                (directory-search "目录搜索")
                (calendar "日历")
                (calc "可编程的计算器" :help "Invoke the Emacs built-in full scientific calculator")
                (simple-calculator "简单的计算器" :help "Invoke the Emacs built-in quick calculator")
                (games "游戏"
                       (5x5 "5x5" :help "Fill in all the squares on a 5x5 board")
                       (adventure "冒险" :help "Dunnet, a text Adventure game for Emacs")
                       (black-box "黑箱" :help "Find balls in a black box by shooting rays")
                       (gomoku "Gomoku" :help "Mark 5 contiguous squares (like tic-tac-toe)")
                       (hanoi "汉诺塔" :help "Watch Towers-of-Hanoi puzzle solved by Emacs")
                       (life "生命" :help "Watch how John Conway's cellular automaton evolves")
                       (mult "乘法谜" :help "Exercise brain with multiplication")
                       (snake "贪食蛇" :help "Move snake around avoiding collisions")
                       (solitaire "Solitaire")
                       (tetris "俄罗斯方块")
                       (yow "Random Quotations" :help "Display a random Zippy quotation")
                       (zone "Zone Out" :help "Play tricks with Emacs display when Emacs is idle")))
         (help-menu "帮助"
                    (emacs-tutorial "Emacs教程" :help "Learn how to use Emacs")
                    (emacs-tutorial-language-specific "Emacs教程(选择语言)..." :help "Learn how to use Emacs (choose a language)")
                    (emacs-faq "Emacs FAQ")
                    (emacs-news "Emacs News" :help "New features of this version")
                    (emacs-problems "Emacs已知问题")
                    (report-emacs-bug "发送Bug报告..." :help "Send e-mail to Emacs maintainers")
                    (debian-emacs-readme "Debian README" :help "Display the README.Debian file")
                    (debian-emacs-news "Debian News" :help "Display the NEWS.Debian file")
                    (debian-emacs-changelog "Debian ChangeLog" :help "Display the Debian changelog")
                    (apropos "搜索文档"
                             (emacs-glossary "Emacs术语" :help "Display the Glossary section of the Emacs manual")
                             (emacs-index-search "在用户手册中查找主题..." :help "Find description of a subject in Emacs User manual")
                             (elisp-index-search "在Elisp手册中查找主题..." :help "Find description of a subject in Emacs Lisp manual")
                             (emacs-key-command-node "在手册中查找按键..." :help "Display manual section that describes a key")
                             (emacs-command-node "在手册中查找命令..." :help "Display manual section that describes a command")
                             (apropos-commands "查找命令..." :help "Find commands whose names match a regexp")
                             (apropos-variables "查找选项..." :help "Find variables whose names match a regexp")
                             (apropos-value "根据值查找选项..." :help "Find variables whose values match a regexp")
                             (apropos "查找对象..." :help "Find symbols of any kind whose names match a regexp")
                             (apropos-documentation "查找文档..." :help "Find functions and variables whose doc strings match a regexp"))
                    (describe "说明"
                              (describe-mode "缓冲区Mode说明" :help "Describe this buffer's major and minor mode")
                              (describe-key-1 "按键或鼠标操作说明..." :help "Display documentation of command bound to a key, a click, or a menu-item")
                              (describe-function "函数说明..." :help "Display documentation of function/command")
                              (describe-variable "变量说明..." :help "Display documentation of variable/option")
                              (describe-face "Face说明..." :help "Display the properties of a face")
                              (describe-current-display-table "Display Table说明" :help "Describe the current display table")
                              (list-keybindings "列出按键绑定" :help "Display all current keybindings (keyboard shortcuts)")
                              (describe-language-environment "列出语言环境"
                                                             (Default "默认")
                                                             (Chinese "中文")
                                                             (Cyrillic "Cyrillic")
                                                             (Indian "Indian")
                                                             (English "English")
                                                             (ASCII "ASCII")
                                                             (Ethiopic "Ethiopic")
                                                             (European "European")
                                                             (Turkish "Turkish")
                                                             (Greek "Greek")
                                                             (Hebrew "Hebrew")
                                                             (Windows-1255 "Windows-1255")
                                                             (Japanese "Japanese")
                                                             (Korean "Korean")
                                                             (Lao "Lao")
                                                             (Thai "Thai")
                                                             (Tibetan "Tibetan")
                                                             (Vietnamese "Vietnamese")
                                                             (IPA "IPA")
                                                             (UTF-8 "UTF-8"))
                              (describe-input-method "输入法说明..." :help "Keyboard layout for specific input method")
                              (describe-coding-system "编码系统说明...")
                              (describe-coding-system-briefly "编码系统说明(简短)...")
                              (mule-diag "显示所有Mule状态" :help "Display multilingual environment settings"))
                    (emacs-manual "阅读Emacs手册" :help "Full documentation of Emacs features")
                    (manuals "更多手册"
                             (info-elintro "Emacs Lisp简介" :help "Read the Introduction to Emacs Lisp Programming")
                             (info-elisp "Emacs Lisp参考手册" :help "Read the Emacs Lisp Reference manual")
                             (info "其它手册(Info)" :help "Read any of the installed manuals")
                             (info-apropos "在所有手册中查找主题..." :help "Find description of a subject in all installed manuals")
                             (order-emacs-manuals "Ordering Manuals" :help "How to order manuals from the Free Software Foundation")
                             (man "阅读Man Page..." :help "Man-page docs for external commands and libraries"))
                    (finder-by-keyword "查找Emacs包" :help "Find packages and features by keyword")
                    (about "关于Emacs" :help "Display version number, copyright info, and basic help")
                    (more "其它包" :help "Lisp packages distributed separately for use in Emacs")
                    (describe-distribution "获取新版本" :help "How to get latest versions of Emacs")
                    (describe-copying "版权" :help "Show the Emacs license (GPL)")
                    (describe-no-warranty "(Non)Warranty" :help "Explain that Emacs has NO WARRANTY")
                    (eliza "Emacs心理医生" :help "Our doctor will help you feel better")))
        ;;}}}
        ;;{{{  outline-mode
        ((eq major-mode 'outline-mode)
         (headings "Heading"
                   (outline-up-heading "Up")
                   (outline-next-visible-heading "Next")
                   (outline-previous-visible-heading "Previous")
                   (outline-forward-same-level "Next Same Level")
                   (outline-backward-same-level "Previous Same Level")
                   (outline-insert-heading "New heading")
                   (copy "复制到 kill ring")
                   (move-subtree-up "Move subtree up")
                   (move-subtree-down "Move subtree down")
                   (promote-subtree "Promote subtree")
                   (demote-subtree "Demote subtree"))
         (show "显示"
               (show-all "Show All")
               (show-entry "Show Entry")
               (show-branches "Show Branches")
               (show-children "Show Children")
               (show-subtree "Show Subtree"))
         (hide "隐藏"
               (hide-leaves "Hide Leaves")
               (hide-body "Hide Body")
               (hide-entry "Hide Entry")
               (hide-subtree "Hide Subtree")
               (hide-sublevels "Hide Sublevels")
               (hide-other "Hide Other")))
        ;;}}}
        ;;{{{  outline-minor-mode
        (outline-minor-mode
         (outline "大纲"
                  (outline-up-heading "向上一级")
                  (outline-next-visible-heading "下一节")
                  (outline-previous-visible-heading "上一节")
                  (outline-forward-same-level "Next Same Level")
                  (outline-backward-same-level "Previous Same Level")
                  (outline-insert-heading "New heading")
                  (copy "Copy to kill ring")
                  (move-subtree-up "Move subtree up")
                  (move-subtree-down "Move subtree down")
                  (promote-subtree "Promote subtree")
                  (demote-subtree "Demote subtree")
                  (show-all "显示所有")
                  (show-entry "Show Entry")
                  (show-branches "Show Branches")
                  (show-children "Show Children")
                  (show-subtree "Show Subtree")
                  (hide-leaves "Hide Leaves")
                  (hide-body "Hide Body")
                  (hide-entry "Hide Entry")
                  (hide-subtree "Hide Subtree")
                  (hide-sublevels "Hide Sublevels")
                  (hide-other "Hide Other")))
        ;;}}}
        ((and (featurep 'session)
              (key-binding [menu-bar file Open\.\.\.recently\ changed]))
         (file "文件"
               (Open\.\.\.recently\ changed "打开最近修改")
               (Open\.\.\.recently\ visited "打开最近访问")))
        ((and (featurep 'template)
              (key-binding [menu-bar file template-new-file]))
         (file "文件"
               (template-new-file "使用模板新建文件" :help "使用模板创建一个新文件")))
        ;;{{{  hs-minor-mode
        (hs-minor-mode
         (Hide/Show "隐藏/显示"
            (Hide\ Block "显示块")
            (Show\ Block "Show Block")
            (Hide\ All "Hide All")
            (Show\ All "Show All")
            (Hide\ Level "Hide Level")
            (Toggle\ Hiding "Toggle Hiding")))
        ;;}}}
        ((and (featurep 'mule-menu)
              (key-binding [menu-bar options mule set-menu-language]))
         (options "选项"
                  (mule "Mule (多国语言环境)"
                        (set-menu-language "设置菜单语言"))))
        ;;{{{  emacs-lisp-mode
        ((eq major-mode 'emacs-lisp-mode)
         (emacs-lisp "Emacs-Lisp"
                     (indent-line "缩进行")
                     (indent-region "缩进区域")
                     (comment-region "注释整个区域")
                     (eval-sexp "对前一个S-表达式求值")
                     (eval-region "对区域求值")
                     (eval-buffer "对整个缓冲区求值")
                     (byte-compile "字节编译文件")
                     (emacs-byte-compile-and-load "字节编译并导入")
                     (byte-recompile "字节编译整个目录...")
                     (edebug-defun "使函数可调试")))
        ;;}}}
        ;;{{{  ibuffer-mode
        ((eq major-mode 'ibuffer-mode)
         (operate "操作"
                  (do-view "View")
                  (do-view-other-frame "View (separate frame)")
                  (do-save "保存")
                  (do-replace-regexp "替换 (regexp)...")
                  (do-query-replace "Query Replace...")
                  (do-query-replace-regexp "Query Replace (regexp)...")
                  (do-print "Print")
                  (do-toggle-modified "Toggle modification flag")
                  (do-revert "Revert")
                  (do-rename-uniquely "Rename Uniquely")
                  (do-delete "Kill")
                  (do-occur "List lines matching...")
                  (do-shell-command-pipe "Pipe to shell command...")
                  (do-shell-command-pipe-replace "Pipe to shell command (replace)...")
                  (do-shell-command-file "Shell command on buffer's file...")
                  (do-eval "Eval...")
                  (do-view-and-eval "Eval (viewing buffer)..."))
         (view "浏览"
               (visit-buffer "浏览这个缓冲区")
               (visit-buffer-other-window "在其它窗格中浏览")
               (visit-buffer-other-frame "在其它窗口中浏览")
               (ibuffer-update "更新")
               (switch-format "切换显示格式")
               (sort "排序"
                     (do-sort-by-major-mode "按主模式排序")
                     (do-sort-by-size "按缓冲区大小排序")
                     (do-sort-by-alphabetic "字典序")
                     (do-sort-by-recency "按访问时间排序")
                     (invert-sorting "反向排序")
                     (toggle-sorting-mode "切换排序模式"))
               (filter "过滤器"
                       (filter-disable "Disable all filtering")
                       (filter-by-mode "Add filter by major mode in use...")
                       (filter-by-name "Add filter by buffer name...")
                       (filter-by-filename "Add filter by filename...")
                       (filter-by-size-lt "Add filter by size less than...")
                       (filter-by-size-gt "Add filter by size greater than...")
                       (filter-by-content "Add filter by content (regexp)...")
                       (filter-by-predicate "Add filter by Lisp predicate...")
                       (pop-filter "Remove top filter")
                       (or-filter "OR top two filters")
                       (negate-filter "Negate top filter")
                       (decompose-filter "Decompose top filter")
                       (exchange-filters "Swap top two filters")
                       (save-filters "Save current filters permanently...")
                       (switch-to-saved-filters "Restore permanently saved filters...")
                       (add-saved-filters "Add to permanently saved filters...")
                       (delete-saved-filters "Delete permanently saved filters..."))
               (filter-groups "Filter Groups"
                              (filters-to-filter-group "Create filter group from current filters...")
                              (forward-filter-group "Move point to the next filter group")
                              (backward-filter-group "Move point to the previous filter group")
                              (jump-to-filter-group "Move point to a specific filter group...")
                              (kill-filter-group "Kill filter group named...")
                              (yank-filter-group "Yank last killed filter group before...")
                              (clear-filter-groups "Remove all filter groups")
                              (pop-filter-group "Decompose filter group...")
                              (save-filter-groups "Save current filter groups permanently...")
                              (switch-to-saved-filter-groups "Restore permanently saved filters...")
                              (delete-saved-filter-groups "Delete permanently saved filter groups...")
                              (set-filter-groups-by-mode "Set current filter groups to filter by mode"))
               (diff-with-file "Diff with file")
               (auto-mode "Toggle Auto Mode")
               (customize "Customize Ibuffer"))
         (mark "标记"
               (toggle-marks "反转标记")
               (mark-forward "标记")
               (unmark-forward "取消标记")
               (mark-by-mode "按模式标记...")
               (mark-modified-buffers "Mark modified buffers")
               (mark-unsaved-buffers "Mark unsaved buffers")
               (mark-read-only-buffers "Mark read-only buffers")
               (mark-special-buffers "Mark special buffers")
               (mark-dired-buffers "Mark dired buffers")
               (mark-dissociated-buffers "Mark dissociated buffers")
               (mark-help-buffers "Mark help buffers")
               (mark-compressed-file-buffers "Mark compressed file buffers")
               (mark-old-buffers "Mark old buffers")
               (unmark-all "Unmark All")
               (mark-by-name-regexp "Mark by buffer name (regexp)...")
               (mark-by-mode-regexp "Mark by major mode (regexp)...")
               (mark-by-file-name-regexp "Mark by file name (regexp)...")))
        ;;}}}
        ;;{{{  dired-mode
        ((eq major-mode 'dired-mode)
         (operate "操作"
                  (copy "复制到..." :help "Copy current file or all marked files")
                  (rename "重命名为..." :help "Rename current file or move marked files")
                  (delete "Delete" :help "Delete current file or all marked files")
                  (find-files "Find files" :help "Find current or marked files")
                  (command "Shell Command..." :help "Run a shell command on each of marked files")
                  (symlink "Symlink to..." :help "Make symbolic links for current or marked files")
                  (relsymlink "Relative symlink to..." :help "Make relative symbolic links for current or marked files")
                  (hardlink "Hardlink to..." :help "Make hard links for current or marked files")
                  (print "Print..." :help "Ask for print command and print marked files")
                  (compress "Compress" :help "Compress/uncompress marked files")
                  (compile "Byte-compile" :help "Byte-compile marked Emacs Lisp files")
                  (load "Load" :help "Load marked Emacs Lisp files")
                  (touch "Change Timestamp..." :help "Change timestamp of marked files")
                  (chmod "Change Mode..." :help "Change mode (attributes) of marked files")
                  (chgrp "Change Group..." :help "Change the group of marked files")
                  (chown "Change Owner..." :help "Change the owner of marked files")
                  (search "Search Files..." :help "Search marked files for regexp")
                  (query-replace "Query Replace in Files..." :help "Replace regexp in marked files")
                  (tumme-display-thumbs "Display Thumbnails" :help "Display thumbnails for current or marked image files")
                  (tumme-dired-comment-files "Add Image Comment..." :help "Add image comment to current or marked files")
                  (tumme-tag-files "Add Image Tags..." :help "Add image tags to current or marked files")
                  (tumme-delete-tag "Delete Image Tag..." :help "Delete image tag from current or marked files"))
         (mark "标记"
               (toggle-marks "Toggle Marks" :help "Mark unmarked files, unmark marked ones")
               (mark "Mark" :help "Mark current line's file for future operations")
               (unmark "Unmark" :help "Unmark or unflag current line's file")
               (deletion "Flag" :help "Flag current line's file for deletion")
               (auto-save-files "Flag Auto-save Files" :help "Flag auto-save files for deletion")
               (backup-files "Flag Backup Files" :help "Flag all backup files for deletion")
               (garbage-files "Flag Garbage Files" :help "Flag unneeded files for deletion")
               (flag-extension "Flag extension..." :help "Flag files with a certain extension for deletion")
               (executables "Mark Executables" :help "Mark all executable files")
               (directory "Mark Old Backups" :help "Flag old numbered backups for deletion")
               (directories "Mark Directories" :help "Mark all directories except `.' and `..'")
               (symlinks "Mark Symlinks" :help "Mark all symbolic links")
               (mark-extension "Mark extension..." :help "Mark files with a certain extension")
               (mark-omitted "Mark omitted" :help "Mark files matching `dired-omit-files' and `dired-omit-extensions'")
               (unmark-all "Unmark All")
               (marks "Change Marks..." :help "Replace marker with another character")
               (next "Next Marked" :help "Move to next marked file")
               (prev "Previous Marked" :help "Move to previous marked file"))
         (regexp "正则"
                 (mark-cont "Mark Containing..." :help "Mark files whose contents matches regexp")
                 (mark "Mark..." :help "Mark files matching regexp for future operations")
                 (flag "Flag..." :help "Flag files matching regexp for deletion")
                 (copy "Copy..." :help "Copy marked files matching regexp")
                 (rename "Rename..." :help "Rename marked files matching regexp")
                 (symlink "Symlink..." :help "Make symbolic links for files matching regexp")
                 (relsymlink-regexp "Relative symlink..." :help "Make relative symbolic links for files matching regexp")
                 (hardlink "Hardlink..." :help "Make hard links for files matching regexp")
                 (upcase "Upcase" :help "Rename marked files to upper-case name")
                 (downcase "Downcase" :help "Rename marked files to lower-case name")
                 (tumme-mark-tagged-files "Mark From Image Tag..." :help "Mark files whose image tags matches regexp"))
         (immediate "立即"
                    (wdired-change-to-wdired-mode "修改文件名")
                    (wdired-mode "修改多个文件名")
                    (create-directory "创建目录...")
                    (find-file "Find This File" :help "Edit file at cursor")
                    (find-file-other-window "Find in Other Window" :help "Edit file at cursor in other window")
                    (display "Display in Other Window" :help "Display file at cursor in other window")
                    (view "View This File" :help "Examine file at cursor in read-only mode")
                    (diff "Diff..." :help "Compare file at cursor with another file")
                    (backup-diff "Compare with Backup" :help "Diff file at cursor with its latest backup")
                    (compare-directories "Compare Directories..." :help "Mark files with different attributes in two dired buffers")
                    (omit-mode "Omit mode" :help "Enable or disable omitting \"uninteresting\" files")
                    (revert-buffer "Refresh" :help "Update contents of shown directories")
                    (tumme-dired-display-image "Display Image" :help "Display sized image in a separate window")
                    (tumme-dired-display-external "Display Image Externally" :help "Display image in external viewer"))
         (subdir "子目录"
                 (insert "插入这个子目录" :help "Insert contents of subdirectory")
                 (next-dirline "下一行" :help "Move to previous directory-file line")
                 (prev-dirline "前一行" :help "Move to next directory-file line")
                 (next-subdir "下一个子目录" :help "Go to next subdirectory header line")
                 (prev-subdir "前一个子目录" :help "Go to previous subdirectory header line")
                 (up "上一级目录" :help "Edit the parent directory")
                 (tree-up "Tree Up" :help "Go to first subdirectory header up the tree")
                 (tree-down "Tree Down" :help "Go to first subdirectory header down the tree")
                 (hide-subdir "隐藏/显示子目录" :help "Hide or unhide current directory listing")
                 (hide-all "隐藏所有" :help "Hide all subdirectories, leave only header lines")))
        ;;}}}
        ;;{{{  fold-mode
        (fold-mode-active
         (fold "折叠"
               (fold-hide "隐藏折叠")
               (fold-show "显示折叠")
               (fold-show-all "显示所有")
               (fold-whole-buffer "折叠整个缓冲区")
               (fold-region "创建折叠")))
        ;;}}}
        ;;{{{  cperl-mode
        ((eq major-mode 'cperl-mode)
         (Perl "Perl"
               (Beginning\ of\ function "函数开始")
               (End\ of\ function "End of function")
               (Mark\ function "Mark function")
               (Indent\ expression "Indent expression")
               (Fill\ paragraph/comment "Fill paragraph/comment")
               (Line\ up\ a\ construction "Line up a construction")
               (Invert\ if/unless/while\ etc "Invert if/unless/while etc")
               (Regexp "Regexp"
                       (Beautify "Beautify")
                       (Beautify\ one\ level\ deep "Beautify one level deep")
                       (Beautify\ a\ group "Beautify a group")
                       (Beautify\ a\ group\ one\ level\ deep "Beautify a group one level deep")
                       (Contract\ a\ group "Contract a group")
                       (Contract\ groups "Contract groups"))
               (Refresh\ \"hard\"\ constructions "Refresh \"hard\" constructions")
               (Indent\ region "Indent region")
               (Comment\ region "Comment region")
               (Uncomment\ region "Uncomment region")
               (Run "Run")
               (Kill "Kill")
               (Next\ error "Next error")
               (Check\ syntax "Check syntax")
               (Debugger "Debugger")
               (Tools "Tools"
                      (Imenu "Imenu")
                      (Insert\ spaces\ if\ needed "Insert spaces if needed")
                      (Class\ Hierarchy\ from\ TAGS "Class Hierarchy from TAGS")
                      (CPerl\ pretty\ print\ \(exprmntl\) "CPerl pretty print (exprmntl)")
                      (Imenu\ on\ info "Imenu on info")
                      (Tags "Tags"
                            (Create\ tags\ for\ current\ file "Create tags for current file")
                            (Add\ tags\ for\ current\ file "Add tags for current file")
                            (Create\ tags\ for\ Perl\ files\ in\ directory "Create tags for Perl files in directory")
                            (Add\ tags\ for\ Perl\ files\ in\ directory "Add tags for Perl files in directory")
                            (Create\ tags\ for\ Perl\ files\ in\ \(sub\)directories "Create tags for Perl files in (sub)directories")
                            (Add\ tags\ for\ Perl\ files\ in\ \(sub\)directories "Add tags for Perl files in (sub)directories")))
               (Perl\ docs "Perl docs"
                           (Define\ word\ at\ point "Define word at point")
                           (Help\ on\ function "Help on function")
                           (Help\ on\ function\ at\ point "Help on function at point")
                           (Help\ on\ symbol\ at\ point "Help on symbol at point")
                           (Perldoc "Perldoc")
                           (Perldoc\ on\ word\ at\ point "Perldoc on word at point")
                           (View\ manpage\ of\ POD\ in\ this\ file "View manpage of POD in this file")
                           (Auto-help\ on "Auto-help on")
                           (Auto-help\ off "Auto-help off"))
               (Toggle\.\.\. "Toggle..."
                             (Auto\ newline "Auto newline")
                             (Electric\ parens "Electric parens")
                             (Electric\ keywords "Electric keywords")
                             (Fix\ whitespace\ on\ indent "Fix whitespace on indent")
                             (Auto-help\ on\ Perl\ constructs "Auto-help on Perl constructs")
                             (Auto\ fill "Auto fill"))
               (Indent\ styles\.\.\. "Indent styles..."
                                     (CPerl "CPerl")
                                     (PerlStyle "PerlStyle")
                                     (GNU "GNU")
                                     (C++ "C++")
                                     (FSF "FSF")
                                     (BSD "BSD")
                                     (Whitesmith "Whitesmith")
                                     (Current "Current")
                                     (Memorized "Memorized"))
               (Micro-docs "Micro-docs"
                           (Tips "Tips")
                           (Problems "Problems")
                           (Speed "Speed")
                           (Praise "Praise")
                           (Faces "Faces")
                           (CPerl\ mode "CPerl mode")
                           (CPerl\ version "CPerl version"))))
        ;;}}}
        ((eq major-mode 'c-mode)
         (C "C"
            (Comment\ Out\ Region "注释区域")
            (Uncomment\ Region "Uncomment Region")
            (Indent\ Expression "Indent Expression")
            (Indent\ Line\ or\ Region "Indent Line or Region")
            (Fill\ Comment\ Paragraph "Fill Comment Paragraph")
            (Backward\ Statement "Backward Statement")
            (Forward\ Statement "Forward Statement")
            (Up\ Conditional "Up Conditional")
            (Backward\ Conditional "Backward Conditional")
            (Forward\ Conditional "Forward Conditional")
            (Macro\ Expand\ Region "Macro Expand Region")
            (Backslashify "Backslashify")
            (Toggle\.\.\. "Toggle..."
                          (Syntactic\ indentation "Syntactic indentation")
                          (Electric\ mode "Electric mode")
                          (Auto\ newline "Auto newline")
                          (Hungry\ delete "Hungry delete")
                          (Subword\ mode "Subword mode"))))
        ((eq major-mode 'c-mode)
         (C++ "C++"
              (Comment\ Out\ Region "Comment Out Region")
              (Uncomment\ Region "Uncomment Region")
              (Indent\ Expression "Indent Expression")
              (Indent\ Line\ or\ Region "Indent Line or Region")
              (Fill\ Comment\ Paragraph "Fill Comment Paragraph")
              (Backward\ Statement "Backward Statement")
              (Forward\ Statement "Forward Statement")
              (Up\ Conditional "Up Conditional")
              (Backward\ Conditional "Backward Conditional")
              (Forward\ Conditional "Forward Conditional")
              (Macro\ Expand\ Region "Macro Expand Region")
              (Backslashify "Backslashify")
              (Toggle\.\.\. "Toggle..."
                            (Syntactic\ indentation "Syntactic indentation")
                            (Electric\ mode "Electric mode")
                            (Auto\ newline "Auto newline")
                            (Hungry\ delete "Hungry delete")
                            (Subword\ mode "Subword mode"))))
        ))

;;; chinese-menu.el ends here
