#FILE text/plain
KHJlcXVpcmUgJ3F1YWlsKQoocXVhaWwtZGVmaW5lLXBhY2thZ2UKICJnbGFnb2xpdGljLXRyYW5z
bGl0IiAiR2xhZ29saXRpYyIgIuKwgyIgbmlsCiAiQSB0cmFuc2xpdGVyYXRpb24gc2NoZW1lIGZv
ciBHbGFnb2xpdGljIGNoYXJhY3RlcnMuIgogbmlsIHQgdCB0IHQgbmlsIG5pbCBuaWwgbmlsIG5p
bCB0KQoocXVhaWwtZGVmaW5lLXJ1bGVzCigiYSIgP+KwgCkKKCJiIiA/4rCBKQooInYiID/isIIp
CigiZyIgP+KwgykKKCJkIiA/4rCEKQooImUiID/isIUpCigiemgiID/isIYpCigiZHoiID/isIcp
CigieiIgP+KwiCkKKCJpaSIgP+KwiSkKKCJpeSIgP+KwiikKKCJpIiA/4rCLKQooImoiID/isIwp
CigiayIgP+KwjSkKKCJsIiA/4rCOKQooIm0iID/isI8pCigibiIgP+KwkCkKKCJvIiA/4rCRKQoo
InAiID/isJIpCigiciIgP+KwkykKKCJzIiA/4rCUKQooInQiID/isJUpCigidSIgP+KwlikKKCJm
IiA/4rCXKQooIngiID/isJgpCigib28iID/isJkpCigidyIgP+KwmSkKKCJzaHQiID/isJspCigi
dHMiID/isJwpCigiY2giID/isJ0pCigic2giID/isJ4pCigiJyciID/isJ8pCigiJ2kiID/isIop
CigiJyIgP+KwoCkKKCJ5YSIgP+KwoSkKKCJ5byIgP+KwpikKKCJ5dSIgP+KwoykKKCJlfiIgP+Kw
pCkKKCJ5ZX4iID/isKcpCigib34iID/isKgpCigieW9+IiA/4rCpKQooInRoIiA/4rCqKQooInYi
ID/isKspCikK
