#+TITLE: ESS Smart Underscore
#+AUTHOR: Matthew L. Fidler

* Library Information
 *ess-smart-underscore.el* --- Ess Smart Underscore

 - Filename :: [[file:ess-smart-underscore.el][ess-smart-underscore.el]]
 - Description :: ess-smart-underscore
 - Author :: Matthew L. Fidler
 - Maintainer :: Matthew Fidler
 - Created :: Thu Jul 14 11:04:42 2011 (-0500)
 - Version :: 0.73
 - Last-Updated :: Wed Aug  8 18:42:23 2012 (-0500)
 -           By :: Matthew L. Fidler
 -     Update # :: 151
 - URL :: http://github.com/mlf176f2/ess-smart-underscore.el
 - Keywords :: ESS, underscore
Compatibility:

* Possible Dependencies

  `custom', `easymenu', `ess', `ess-compat', `ess-custom',
  `font-lock', `syntax', `widget'.

* Installation

To use without using a package manager:

 - Put the library in a directory in the emacs load path, like ~/.emacs.d
 - Add (require 'ess-smart-underscore) in your ~/.emacs file

This is in emacswiki, so this package can also be installed using el-get.

After installing el-get, Type M-x el-get-install ess-smart-underscore.
* Ess-Smart Underscore Package Information
Smart "_" key: insert =ess-S-assign=, unless:

  1. in string/comment
  2. after a $ (like d$one_two) (toggle with =ess-S-underscore-after-$=)
  3. when the underscore is part of a variable definition previously defined.
     (toggle with `ess-S-underscore-after-defined')
  4. when the underscore is after a "=" or "<-" on the same line.
  5. inside a parenthetical statement () or [].
     (toggle with =ess-S-underscore-when-inside-paren=)
  6. At the beginning of a line.
  7. In a variable that contains underscores already (for example foo_a)
     (toggle with =ess-S-underscore-when-variable-contains-underscores=)
  8. The preceding character is not a tab/space (toggle with
     =ess-S-underscore-when-last-character-is-a-space=.  Not enabled
     by default.)

An exception to #4 is in the following situation:

#+BEGIN_SRC R
a <- b |
#+END_SRC

Pressing an underscore here would produce


#+BEGIN_SRC R
a <- b <-
#+END_SRC

However when in the following situation

#+BEGIN_SRC R
a <- b|
#+END_SRC

Pressing an underscore would produce

#+BEGIN_SRC  R
a <- b_
#+END_SRC

This behavior can be toggled by =ess-S-space-underscore-is-assignment=

If the underscore key is pressed a second time, the assignment
operator is removed and replaced by the underscore.  =ess-S-assign=,
typically " <- ", can be customized.  In ESS modes other than R/S,
an underscore is always inserted.

* History

 - 08-Aug-2012 ::  Updated the documentation to have the R code preformatted. (Matthew L. Fidler)
 - 07-Aug-2012 ::  Attempt to upload and convert again. (Matthew L. Fidler)
 - 07-Aug-2012 ::  Added more information to Readme.org (Matthew L. Fidler)
 - 07-Aug-2012 ::  Added Readme.org (Matthew L. Fidler)
 - 07-Aug-2012 ::  Added readme.org (Matthew L. Fidler)
 - 07-Aug-2012 ::  Added readme.org (Matthew L. Fidler)
 - 07-Aug-2012 ::  To use, put (require 'ess-smart-underscore) in your ~/.emacs file (Matthew L. Fidler)
 - 07-Aug-2012 ::  Added a Readme.org (Matthew L. Fidler)
 - 22-Feb-2012 ::  Support unbalanced sexps. (Matthew L. Fidler)
 - 02-Feb-2012 ::  Took out auto-installing. Most package managers don't want you to do this. (Matthew L. Fidler)
 - 03-Aug-2011 ::  Bug fix for parenthetical statement (Matthew L. Fidler)
 - 20-Jul-2011 ::  Changed to allow underscore instead of assign when inside a parenthetical statement.  (Matthew L. Fidler)
  - 15-Jul-2011 ::  Bug fix for d[d$CMT == 2,"DV"] _ to produce d[d$CMT == 2,"DV"] <-  (Matthew L. Fidler)
