;;; switch-color-theme-matlab-latex.el --- color themes for matlab

;; Filename: switch-color-theme-matlab-latex.el 
;; Author: Da Zhang
;; Created: Wed Jan 16 13:06:57 2008 Update #: 8

;; Copyright (C) 2008 Da Zhang ECE OU, zhangda@member.fsf.org

;; This is free software; you can redistribute it and/or modify it under
;; the terms of the GNU General Public License as published by the Free
;; Software Foundation; either version 2, or (at your option) any later
;; version.
;;
;; This is distributed in the hope that it will be useful, but WITHOUT
;; ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
;; FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
;; for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to the
;; Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
;; MA 02111-1307, USA.

;;; Commentary: 

;; switch-color-theme-matlab-latex.el contains the customized color themes
;; for matlab mode (yellow background) and normal (black background). Call
;; function da-color-theme to change to the dark face, and call C-u
;; da-color-theme for the yellow background face.

;; color-theme-da-matlab is particularly designed to simulate the warm
;; yellow-green color and visual effect of Matlab programming environment

;; color-theme-da-normal is a dark theme, designed for normal programming
;; tasks such as C/C++/Java development, org/muse mode editing and LaTeX
;; editing.


;; Install theme:
;; (1)Place switch-color-theme-matlab-latex.el into your load-path.

;; (2)In your .emacs, add:
;; (require 'switch-color-theme-matlab-latex)

;; (3)optional settings such as keybinding and hooking
;; (add-hook 'matlab-mode-hook 'color-theme-da-matlab)
;; (global-set-key [f6] 'da-color-theme)

;;; Code:

(defun color-theme-da-matlab ()
  "Color theme by Da Zhang, created 2007-07-23."
  (interactive)
  (ignore-errors  (color-theme-install
		   '(my-color-theme
		     ((background-color . "light goldenrod yellow")
		      (background-mode . light)
		      (border-color . "black")
		      (cursor-color . "red")
		      (foreground-color . "black")
		      (mouse-color . "black"))
		     (default ((t (:stipple nil :background "light goldenrod yellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 130 :width normal :family "outline-andale mono"))))
		     (bold ((t (:bold t :background "grey40" :foreground "yellow" :weight bold))))
		     (bold-italic ((t (:italic t :bold t :foreground "yellow green" :slant italic :weight bold))))
		     (border ((t (:background "yellow"))))
		     (buffer-menu-buffer ((t (:bold t :weight bold))))
		     (button ((t (:underline t))))
		     (comint-highlight-prompt ((t (:bold t :foreground "DarkBlue" :weight bold))))
		     (compilation-column-number ((t (:foreground "DarkBlue"))))
		     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
		     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
		     (compilation-line-number ((t (:bold t :weight ultra-bold :foreground "saddle brown"))))
		     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
		     (completions-common-part ((t (:family "outline-andale mono" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "light goldenrod yellow" :stipple nil :height 120))))
		     (completions-first-difference ((t (:bold t :weight bold :foreground "yellow" :background "grey40"))))
		     (cursor ((t (:background "red"))))
		     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
		     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
		     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
		     (custom-button-pressed-unraised ((t (:underline t :foreground "magenta4"))))
		     (custom-button-unraised ((t (:underline t))))
		     (custom-changed ((t (:background "blue1" :foreground "white"))))
		     (custom-comment ((t (:background "gray85"))))
		     (custom-comment-tag ((t (:foreground "blue4"))))
		     (custom-documentation ((t (nil))))
		     (custom-face-tag ((t (:bold t :family "helv" :weight bold :height 1.2))))
		     (custom-group-tag ((t (:bold t :foreground "blue1" :weight bold :height 1.2))))
		     (custom-group-tag-1 ((t (:bold t :family "helv" :foreground "red1" :weight bold :height 1.2))))
		     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
		     (custom-link ((t (:underline t :foreground "blue1"))))
		     (custom-modified ((t (:background "blue1" :foreground "white"))))
		     (custom-rogue ((t (:background "black" :foreground "pink"))))
		     (custom-saved ((t (:underline t))))
		     (custom-set ((t (:background "white" :foreground "blue1"))))
		     (custom-state ((t (:foreground "dark green"))))
		     (custom-themed ((t (:background "blue1" :foreground "white"))))
		     (custom-variable-button ((t (:bold t :underline t :weight bold))))
		     (custom-variable-tag ((t (:bold t :family "helv" :foreground "blue1" :weight bold :height 1.2))))
		     (ecb-analyse-bucket-element-face ((t (:foreground "brown" :height 1.0))))
		     (ecb-analyse-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
		     (ecb-analyse-face ((t (:background "cornflower blue" :foreground "yellow"))))
		     (ecb-analyse-general-face ((t (:height 1.0))))
		     (ecb-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
		     (ecb-default-general-face ((t (:height 1.0))))
		     (ecb-default-highlight-face ((t (:background "cornflower blue" :foreground "yellow"))))
		     (ecb-directories-general-face ((t (:height 1.0))))
		     (ecb-directory-face ((t (:background "cornflower blue" :foreground "yellow"))))
		     (ecb-directory-not-accessible-face ((t (:foreground "gray60" :height 1.0))))
		     (ecb-history-face ((t (:background "cornflower blue" :foreground "yellow"))))
		     (ecb-history-general-face ((t (:height 1.0))))
		     (ecb-method-face ((t (:background "cornflower blue" :foreground "yellow"))))
		     (ecb-method-non-semantic-face ((t (:foreground "brown" :height 1.0))))
		     (ecb-methods-general-face ((t (:height 1.0))))
		     (ecb-mode-line-data-face ((t (nil))))
		     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
		     (ecb-mode-line-win-nr-face ((t (:bold t :weight bold))))
		     (ecb-source-face ((t (:background "cornflower blue" :foreground "yellow"))))
		     (ecb-source-in-directories-buffer-face ((t (:foreground "medium blue" :height 1.0))))
		     (ecb-source-read-only-face ((t (:italic t :slant italic))))
		     (ecb-sources-general-face ((t (:height 1.0))))
		     (ecb-tag-header-face ((t (:background "SeaGreen1"))))
		     (ecb-tree-guide-line-face ((t (:foreground "grey" :height 1.0))))
		     (ecb-type-tag-class-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-enum-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
		     (ecb-type-tag-interface-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-struct-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-typedef-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-union-face ((t (:bold t :weight bold))))
		     (eieio-custom-slot-tag-face ((t (:foreground "blue"))))
		     (escape-glyph ((t (:foreground "brown"))))
		     (file-name-shadow ((t (:foreground "grey50"))))
		     (fixed-pitch ((t (:family "courier"))))
		     (fl-comment-face ((t (:foreground "medium purple"))))
		     (fl-function-name-face ((t (:foreground "green"))))
		     (fl-keyword-face ((t (:foreground "LightGreen"))))
		     (fl-string-face ((t (:foreground "light coral"))))
		     (fl-type-face ((t (:foreground "cyan"))))
		     (font-lock-builtin-face ((t (:foreground "dark blue" :weight bold))))
		     (font-lock-comment-delimiter-face ((t (:foreground "dark green" :weight bold))))
		     (font-lock-comment-face ((t (:foreground "dark green" :weight bold))))
		     (font-lock-constant-face ((t (:bold t :foreground "DarkBlue" :weight extra-bold))))
		     (font-lock-doc-face ((t (:bold t :foreground "purple2" :weight bold))))
		     (font-lock-function-name-face ((t (:bold t :foreground "red4" :weight bold))))
		     (font-lock-keyword-face ((t (:bold t :foreground "blue" :weight bold))))
		     (font-lock-negation-char-face ((t (nil))))
		     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue" :weight bold))))
		     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold :foreground "NavyBlue" ))))
		     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold :foreground "NavyBlue" ))))
		     (font-lock-string-face ((t (:bold t :foreground "purple2" :weight extra-bold))))
		     (font-lock-type-face ((t (:foreground "dark blue" :weight bold))))
		     (font-lock-variable-name-face ((t (:bold t :foreground "saddle brown" :weight ultra-bold))))
		     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight extra-bold))))
		     (fringe ((t (:background "grey95"))))
		     (header-line ((t (:background "grey90" :foreground "grey20" :box nil))))
		     (help-argument-name ((t (nil))))
		     (highlight ((t (:background "black" :foreground "burlywood"))))
		     (html-helper-bold-face ((t (:bold t :weight bold))))
		     (html-helper-italic-face ((t (:bold t :background "black" :foreground "yellow" :weight bold))))
		     (html-helper-underline-face ((t (:underline t))))
		     (ibuffer-deletion-face ((t (:foreground "red"))))
		     (ibuffer-marked-face ((t (:foreground "green"))))
		     (ido-first-match ((t (:bold t :weight ultra-bold))))
		     (ido-indicator ((t (:background "red" :foreground "yellow" :width condensed))))
		     (ido-only-match ((t (:foreground "Green" :weight ultra-bold))))
		     (ido-subdir ((t (:foreground "red"))))
		     (info-node ((t (:bold t :foreground "green3" :weight bold))))
		     (info-xref ((t (:bold t :weight bold))))
		     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
		     (italic ((t (:italic t :foreground "yellow3" :slant italic))))
		     (lazy-highlight ((t (:background "paleturquoise"))))
		     (link ((t (:foreground "blue1" :underline t))))
		     (link-visited ((t (:underline t :foreground "magenta4"))))
		     (linum ((t (:inherit shadow :foreground "DarkGreen" :height 100 :weight normal))))
		     (match ((t (:background "yellow"))))
		     (man-bold ((t (:bold t :weight bold))))
		     (man-heading ((t (:bold t :weight bold))))
		     (man-italic ((t (:foreground "MediumBlue"))))
		     (man-xref ((t (:underline t))))
		     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
		     (message-cited-text-face ((t (:foreground "red"))))
		     (message-header-cc-face ((t (:bold t :foreground "green4" :weight bold))))
		     (message-header-name-face ((t (:foreground "DarkGreen"))))
		     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
		     (message-header-other-face ((t (:foreground "#b00000"))))
		     (message-header-subject-face ((t (:foreground "green3"))))
		     (message-header-to-face ((t (:bold t :foreground "green2" :weight bold))))
		     (message-header-xheader-face ((t (:foreground "blue"))))
		     (message-mml-face ((t (:foreground "ForestGreen"))))
		     (message-separator-face ((t (:foreground "blue3"))))
		     (minibuffer-prompt ((t (:foreground "medium blue"))))
		     (mode-line ((t (:background "wheat" :foreground "black"))))
		     (mode-line-buffer-id ((t (:background "wheat" :foreground "black"))))
		     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
		     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
		     (modeline-mousable ((t (:background "wheat" :foreground "black"))))
		     (modeline-mousable-minor-mode ((t (:background "wheat" :foreground "black"))))
		     (mouse ((t (:background "black"))))
		     (next-error ((t (:background "gray80"))))
		     (nobreak-space ((t (:foreground "brown" :underline t))))
		     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
		     (region ((t (:background "gray80"))))
		     (scroll-bar ((t (:foreground "systemscrollbar"))))
		     (secondary-selection ((t (:background "darkslateblue" :foreground "black"))))
		     (semantic-decoration-on-private-members-face ((t (:background "#8fffff"))))
		     (semantic-decoration-on-protected-members-face ((t (:background "#fffff8"))))
		     (semantic-highlight-edits-face ((t (:background "gray90"))))
		     (semantic-tag-boundary-face ((t (:overline "blue"))))
		     (semantic-tag-highlight-face ((t (:background "#FFFFAA"))))
		     (semantic-tag-highlight-start-face ((t (:background "#FFFFAA"))))
		     (semantic-unmatched-syntax-face ((t (:underline "red"))))
		     (senator-intangible-face ((t (:foreground "gray25"))))
		     (senator-momentary-highlight-face ((t (:background "gray70"))))
		     (senator-read-only-face ((t (:background "#CCBBBB"))))
		     (shadow ((t (:foreground "grey50"))))
		     (show-paren-match ((t (:background "turquoise"))))
		     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
		     (speedbar-button-face ((t (:foreground "green4"))))
		     (speedbar-directory-face ((t (:foreground "blue4"))))
		     (speedbar-file-face ((t (:foreground "cyan4"))))
		     (speedbar-highlight-face ((t (:background "green"))))
		     (speedbar-selected-face ((t (:foreground "red" :underline t))))
		     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
		     (speedbar-tag-face ((t (:foreground "brown"))))
		     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :underline t :weight bold))))
		     (swbuff-default-face ((t (nil))))
		     (swbuff-separator-face ((t (:foreground "blue"))))
		     (tabbar-button-face ((t (:background "gray72" :family "helv" :foreground "dark red" :box (:line-width 2 :color "white" :style released-button) :height 0.8))))
		     (tabbar-default-face ((t (:family "helv" :background "gray72" :foreground "gray60" :height 0.8))))
		     (tabbar-selected-face ((t (:background "gray72" :family "helv" :foreground "blue" :box (:line-width 2 :color "white" :style released-button) :height 0.8))))
		     (tabbar-separator-face ((t (:foreground "gray60" :background "gray72" :family "helv" :height 0.16000000000000003))))
		     (tabbar-unselected-face ((t (:foreground "gray60" :background "gray72" :family "helv" :box (:line-width 2 :color "white" :style pressed-button) :height 0.8))))
		     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
		     (tooltip ((t (:family "helv" :background "systeminfowindow" :foreground "systeminfotext"))))
		     (trailing-whitespace ((t (:background "red1"))))
		     (underline ((t (:underline t))))
		     (variable-pitch ((t (:family "helv"))))
		     (vertical-border ((t (nil))))
		     (which-func ((t (:foreground "DeepSkyBlue4"))))
		     (widget-button ((t (:bold t :weight bold))))
		     (widget-button-pressed ((t (:foreground "red1"))))
		     (widget-documentation ((t (:foreground "dark green"))))
		     (widget-field ((t (:background "gray85"))))
		     (widget-inactive ((t (:foreground "grey50"))))
		     (widget-single-line-field ((t (:background "gray85"))))
		     (xref-keyword-face ((t (:foreground "blue"))))
		     (xref-list-default-face ((t (nil))))
		     (xref-list-pilot-face ((t (:foreground "navy"))))
		     (xref-list-symbol-face ((t (:foreground "navy"))))))))



(defun color-theme-da-normal ()
  "Color theme by Da Zhang, created 2007-07-24."
  (interactive)
  (ignore-errors  (color-theme-install
		   '(my-color-theme
		     ((background-color . "black")
		      (background-mode . dark)
		      (background-toolbar-color . "#cf3ccf3ccf3c")
		      (border-color . "#000000000000")
		      (bottom-toolbar-shadow-color . "#79e77df779e7")
		      (cursor-color . "Red3")
		      (foreground-color . "honeydew")
		      (mouse-color . "black")
		      (top-toolbar-shadow-color . "#fffffbeeffff"))
		     (default ((t (:stipple nil :background "black" :foreground "honeydew3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 130 :width normal :family "outline-andale mono"))))
		     (bbdb-company ((t (nil))))
		     (bbdb-field-name ((t (:bold t :weight bold))))
		     (bbdb-field-value ((t (nil))))
		     (bbdb-name ((t (:underline t))))
		     (blue ((t (:foreground "blue"))))
		     (bold ((t (:bold t :weight bold))))
		     (bold-italic ((t (:bold t :foreground "yellow" :weight bold))))
		     (border ((t (:background "#000000000000"))))
		     (border-glyph ((t (nil))))
		     (buffer-menu-buffer ((t (:bold t :weight bold))))
		     (buffers-tab ((t (:background "black" :foreground "LightSkyBlue"))))
		     (button ((t (:underline t))))
		     (comint-highlight-prompt ((t (:bold t :foreground "Green1" :weight bold))))
		     (compilation-column-number ((t (:foreground "DarkSlateGray1"))))
		     (compilation-error ((t (:bold t :weight bold :foreground "Red"))))
		     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
		     (compilation-line-number ((t (:foreground "magenta2"))))
		     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
		     (completions-common-part ((t (:family "outline-andale mono" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "gray78" :background "black" :stipple nil :height 120))))
		     (completions-first-difference ((t (:bold t :weight bold))))
		     (cperl-array-face ((t (:bold t :foreground "SkyBlue2" :weight bold))))
		     (cperl-hash-face ((t (:foreground "LightBlue2"))))
		     (cperl-invalid-face ((t (:foreground "red"))))
		     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
		     (cursor ((t (:background "Red3"))))
		     (custom-button ((t (:bold t :weight bold))))
		     (custom-button-face ((t (:bold t :weight bold))))
		     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
		     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
		     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
		     (custom-button-unraised ((t (:underline t))))
		     (custom-changed ((t (:background "blue" :foreground "white"))))
		     (custom-changed-face ((t (:background "blue" :foreground "white"))))
		     (custom-comment ((t (:foreground "white"))))
		     (custom-comment-face ((t (:foreground "white"))))
		     (custom-comment-tag ((t (:foreground "white"))))
		     (custom-comment-tag-face ((t (:foreground "white"))))
		     (custom-documentation ((t (nil))))
		     (custom-documentation-face ((t (nil))))
		     (custom-face-tag ((t (:underline t))))
		     (custom-face-tag-face ((t (:underline t))))
		     (custom-group-tag ((t (:foreground "blue" :underline t))))
		     (custom-group-tag-1 ((t (:foreground "red" :underline t))))
		     (custom-group-tag-face ((t (:foreground "blue" :underline t))))
		     (custom-group-tag-face-1 ((t (:foreground "red" :underline t))))
		     (custom-invalid ((t (:background "red" :foreground "yellow"))))
		     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
		     (custom-link ((t (:underline t :foreground "cyan1"))))
		     (custom-modified ((t (:background "blue" :foreground "white"))))
		     (custom-modified-face ((t (:background "blue" :foreground "white"))))
		     (custom-rogue ((t (:background "black" :foreground "pink"))))
		     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
		     (custom-saved ((t (:underline t))))
		     (custom-saved-face ((t (:underline t))))
		     (custom-set ((t (:background "white" :foreground "blue"))))
		     (custom-set-face ((t (:background "white" :foreground "blue"))))
		     (custom-state ((t (:foreground "white"))))
		     (custom-state-face ((t (:foreground "white"))))
		     (custom-themed ((t (:background "blue1" :foreground "white"))))
		     (custom-variable-button ((t (:bold t :underline t :weight bold))))
		     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
		     (custom-variable-tag ((t (:foreground "blue" :underline t))))
		     (custom-variable-tag-face ((t (:foreground "blue" :underline t))))
		     (cvs-filename-face ((t (:foreground "Green1"))))
		     (cvs-handled-face ((t (:foreground "pink"))))
		     (cvs-header-face ((t (:foreground "green"))))
		     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
		     (cvs-msg-face ((t (:foreground "red"))))
		     (cvs-need-action-face ((t (:foreground "yellow"))))
		     (cvs-unknown-face ((t (:foreground "grey"))))
		     (diff-added-face ((t (nil))))
		     (diff-changed-face ((t (nil))))
		     (diff-file-header-face ((t (:bold t :background "grey70" :weight bold))))
		     (diff-hunk-header-face ((t (:background "grey85"))))
		     (diff-index-face ((t (:bold t :background "grey70" :weight bold))))
		     (diff-removed-face ((t (nil))))
		     (dired-face-boring ((t (:foreground "Gray65"))))
		     (dired-face-directory ((t (:bold t :foreground "SkyBlue2" :weight bold))))
		     (dired-face-executable ((t (:foreground "Green"))))
		     (dired-face-flagged ((t (:background "LightSlateGray"))))
		     (dired-face-header ((t (:background "grey75" :foreground "black"))))
		     (dired-face-marked ((t (:background "PaleVioletRed"))))
		     (dired-face-permissions ((t (:background "grey75" :foreground "black"))))
		     (dired-face-setuid ((t (:foreground "Red"))))
		     (dired-face-socket ((t (:foreground "magenta"))))
		     (dired-face-symlink ((t (:foreground "cyan"))))
		     (ecb-analyse-bucket-element-face ((t (:height 1.0))))
		     (ecb-analyse-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
		     (ecb-analyse-face ((t (:background "magenta"))))
		     (ecb-analyse-general-face ((t (:height 1.0))))
		     (ecb-bucket-node-face ((t (:bold t :weight bold :height 1.0))))
		     (ecb-default-general-face ((t (:height 1.0))))
		     (ecb-default-highlight-face ((t (:background "magenta"))))
		     (ecb-directories-general-face ((t (:height 1.0))))
		     (ecb-directory-face ((t (:background "magenta"))))
		     (ecb-directory-not-accessible-face ((t (:foreground "gray60" :height 1.0))))
		     (ecb-history-face ((t (:background "magenta"))))
		     (ecb-history-general-face ((t (:height 1.0))))
		     (ecb-method-face ((t (:background "magenta"))))
		     (ecb-method-non-semantic-face ((t (:foreground "brown" :height 1.0))))
		     (ecb-methods-general-face ((t (:height 1.0))))
		     (ecb-mode-line-data-face ((t (nil))))
		     (ecb-mode-line-prefix-face ((t (:foreground "forestgreen"))))
		     (ecb-mode-line-win-nr-face ((t (:bold t :weight bold))))
		     (ecb-source-face ((t (:background "magenta"))))
		     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1" :height 1.0))))
		     (ecb-source-read-only-face ((t (:italic t :slant italic))))
		     (ecb-sources-general-face ((t (:height 1.0))))
		     (ecb-tag-header-face ((t (:background "SeaGreen1"))))
		     (ecb-tree-guide-line-face ((t (:foreground "gray" :height 1.0))))
		     (ecb-type-tag-class-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-enum-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
		     (ecb-type-tag-interface-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-struct-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-typedef-face ((t (:bold t :weight bold))))
		     (ecb-type-tag-union-face ((t (:bold t :weight bold))))
		     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
		     (escape-glyph ((t (:foreground "cyan"))))
		     (excerpt ((t (nil))))
		     (file-name-shadow ((t (:foreground "grey70"))))
		     (fixed ((t (:bold t :weight bold))))
		     (fixed-pitch ((t (:family "courier"))))
		     (font-lock-builtin-face ((t (:foreground "red3" :weight bold))))
		     (font-lock-comment-delimiter-face ((t (:foreground "YellowGreen" :weight ultra-bold))))
		     (font-lock-comment-face ((t (:foreground "YellowGreen" :weight bold))))
		     (font-lock-constant-face ((t (:bold t :foreground "DarkOrange" :weight ultra-bold))))
		     (font-lock-doc-face ((t (:foreground "burlywood"))))
		     (font-lock-doc-string-face ((t (:foreground "turquoise" :weight bold))))
		     (font-lock-function-name-face ((t (:foreground "white" :weight ultra-bold))))
		     (font-lock-keyword-face ((t (:bold t :foreground "DodgerBlue" :weight ultra-bold))))
		     (font-lock-negation-char-face ((t (nil))))
		     (font-lock-preprocessor-face ((t (:foreground "green3" :weight bold))))
		     (font-lock-reference-face ((t (:foreground "red3" :weight bold))))
		     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
		     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
		     (font-lock-string-face ((t (:foreground "burlywood" ))))
		     (font-lock-type-face ((t (:foreground "brown2" :weight bold))))
		     (font-lock-variable-name-face ((t (:foreground "magenta2" :weight bold))))
		     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight ultra-bold))))
		     (fringe ((t (:background "grey10"))))
		     (green ((t (:foreground "green"))))
		     (gui-button-face ((t (:background "grey75" :foreground "black"))))
		     (gui-element ((t (nil))))
		     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
		     (help-argument-name ((t (nil))))
		     (highlight ((t (:background "darkseagreen2" :foreground "blue"))))
		     (html-helper-bold-face ((t (:bold t :weight bold))))
		     (html-helper-italic-face ((t (:bold t :foreground "yellow" :weight bold))))
		     (html-helper-underline-face ((t (:underline t))))
		     (hyper-apropos-documentation ((t (:foreground "LightSlateGray"))))
		     (hyper-apropos-heading ((t (:bold t :weight bold))))
		     (hyper-apropos-hyperlink ((t (:foreground "sky blue"))))
		     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
		     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
		     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
		     (ibuffer-deletion-face ((t (:foreground "red"))))
		     (ibuffer-marked-face ((t (:foreground "green"))))
		     (ido-first-match ((t (:bold t :weight ultra-bold))))
		     (ido-indicator ((t (:background "red" :foreground "yellow" :width condensed))))
		     (ido-only-match ((t (:foreground "Green" :weight ultra-bold))))
		     (ido-subdir ((t (:foreground "red"))))
		     (info-node ((t (:bold t :foreground "yellow" :weight bold))))
		     (info-xref ((t (:bold t :weight bold))))
		     (isearch ((t (:background "paleturquoise" :foreground "dark red"))))
		     (isearch-secondary ((t (:foreground "red3"))))
		     (italic ((t (:bold t :foreground "yellow" :weight bold))))
		     (lazy-highlight ((t (:background "paleturquoise4"))))
		     (left-margin ((t (nil))))
		     (link ((t (:foreground "cyan1" :underline t))))
		     (link-visited ((t (:underline t :foreground "violet"))))
		     (linum ((t (:inherit shadow :foreground "burlywood" :height 100 :weight normal))))
		     (list-mode-item-selected ((t (:background "gray68" :foreground "dark green"))))
		     (man-bold ((t (:bold t :weight bold))))
		     (man-heading ((t (:bold t :weight bold))))
		     (man-italic ((t (:foreground "yellow"))))
		     (man-xref ((t (:underline t))))
		     (match ((t (:background "RoyalBlue3"))))
		     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
		     (message-cited-text ((t (:foreground "orange"))))
		     (message-header-contents ((t (:foreground "white"))))
		     (message-headers ((t (:bold t :foreground "orange" :weight bold))))
		     (message-highlighted-header-contents ((t (:bold t :weight bold))))
		     (message-url ((t (:bold t :foreground "pink" :weight bold))))
		     (minibuffer-prompt ((t (:foreground "cyan"))))
		     (mmm-face ((t (:background "black" :foreground "green"))))
		     (mode-line ((t (nil))))
		     (mode-line-buffer-id ((t (:background "Gray80" :foreground "blue4"))))
		     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
		     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
		     (modeline-mousable ((t (:background "Gray80" :foreground "firebrick"))))
		     (modeline-mousable-minor-mode ((t (:background "Gray80" :foreground "green4"))))
		     (mouse ((t (:background "black"))))
		     (next-error ((t (:foreground "DarkBlue" :background "gray65"))))
		     (nobreak-space ((t (:foreground "cyan" :underline t))))
		     (org-level-1 ((((class color) (min-colors 88) (background dark)) (:foreground "LightSkyBlue" :weight bold))))
		     (org-level-3 ((((class color) (min-colors 88) (background dark)) (:foreground "Green2" :weight normal))))
		     (paren-blink-off ((t (:foreground "gray80"))))
		     (paren-match ((t (:background "MediumBlue"))))
		     (paren-mismatch ((t (:background "DeepPink" :foreground "LightSkyBlue"))))
		     (pointer ((t (nil))))
		     (primary-selection ((t (:background "gray65" :foreground "DarkBlue"))))
		     (query-replace ((t (:foreground "dark red" :background "paleturquoise"))))
		     (red ((t (:foreground "red"))))
		     (region ((t (:background "gray65" :foreground "DarkBlue"))))
		     (right-margin ((t (nil))))
		     (scroll-bar ((t (:foreground "systemscrollbar"))))
		     (secondary-selection ((t (:background "paleturquoise" :foreground "black"))))
		     (semantic-highlight-edits-face ((t (:background "gray20"))))
		     (semantic-unmatched-syntax-face ((t (:underline "red"))))
		     (senator-intangible-face ((t (:foreground "gray75"))))
		     (senator-momentary-highlight-face ((t (:background "gray30"))))
		     (senator-read-only-face ((t (:background "#664444"))))
		     (shadow ((t (:foreground "grey70"))))
		     (shell-option-face ((t (:foreground "LightSkyBlue1"))))
		     (shell-output-2-face ((t (:foreground "SeaGreen1"))))
		     (shell-output-3-face ((t (:foreground "SeaGreen1"))))
		     (shell-output-face ((t (:bold t :weight bold))))
		     (shell-prompt-face ((t (:foreground "red4"))))
		     (show-paren-match ((t (:background "steelblue3"))))
		     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
		     (speedbar-button-face ((t (:foreground "green3"))))
		     (speedbar-directory-face ((t (:foreground "light blue"))))
		     (speedbar-file-face ((t (:foreground "cyan"))))
		     (speedbar-highlight-face ((t (:background "sea green"))))
		     (speedbar-selected-face ((t (:foreground "red" :underline t))))
		     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
		     (speedbar-tag-face ((t (:foreground "yellow"))))
		     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :underline t :weight bold))))
		     (swbuff-default-face ((t (nil))))
		     (swbuff-separator-face ((t (:foreground "DodgerBlue1"))))
		     (tabbar-button-face ((t (:background "gray72" :family "helv" :foreground "dark red" :box (:line-width 2 :color "white" :style released-button) :height 0.8))))
		     (tabbar-default-face ((t (:family "helv" :background "gray72" :foreground "gray60" :height 0.8))))
		     (tabbar-selected-face ((t (:background "gray72" :family "helv" :foreground "blue" :box (:line-width 2 :color "white" :style released-button) :height 0.8))))
		     (tabbar-separator-face ((t (:foreground "gray60" :background "gray72" :family "helv" :height 0.16000000000000003))))
		     (tabbar-unselected-face ((t (:foreground "gray60" :background "gray72" :family "helv" :box (:line-width 2 :color "white" :style pressed-button) :height 0.8))))
		     (text-cursor ((t (:background "Red3" :foreground "black"))))
		     (tool-bar ((t (:background "Gray80" :foreground "black"))))
		     (tooltip ((t (:family "helv" :background "systeminfowindow" :foreground "systeminfotext"))))
		     (trailing-whitespace ((t (:background "red1"))))
		     (underline ((t (:underline t))))
		     (variable-pitch ((t (:family "helv"))))
		     (vertical-border ((t (nil))))
		     (vertical-divider ((t (nil))))
		     (vm-xface ((t (:background "white" :foreground "black"))))
		     (vmpc-pre-sig-face ((t (:foreground "forestgreen"))))
		     (vmpc-sig-face ((t (:foreground "steelblue"))))
		     (which-func ((t (:foreground "DeepSkyBlue1"))))
		     (widget ((t (nil))))
		     (widget-button ((t (:bold t :weight bold))))
		     (widget-button-pressed ((t (:foreground "red"))))
		     (widget-documentation ((t (:foreground "lime green"))))
		     (widget-field ((t (:background "gray85" :foreground "black"))))
		     (widget-inactive ((t (:foreground "dim gray"))))
		     (widget-single-line-field ((t (:background "dim gray"))))
		     (x-face ((t (:background "white" :foreground "black"))))
		     (xrdb-option-name-face ((t (:foreground "red"))))
		     (yellow ((t (:foreground "yellow"))))
		     (zmacs-region ((t (:background "gray65"))))))))



(defun da-color-theme (&optional arg)
  "Changes color theme to my custom black background theme.
    With a prefix arg, changes to my custom white background theme."
  (interactive "P")
  (ignore-errors
    (if arg
    	(color-theme-da-matlab)
      (color-theme-da-normal))))

(provide 'switch-color-theme-matlab-latex)
;;; switch-color-theme-matlab-latex.el ends here
