;;; tacl-syntax.el
;; This is a list of help strings for use by tacl-mode.el which is free software.
;;
;; It's possible to display 3 different help strings for a given keyword.
;; If the cursor is at the beginning of a word, "|<keyword>" is searched
;; for.  If the cursor is not at the beginning or "|<keyword>" is not found
;; then "<keyword>" is searched for.  If the character before the cursor is
;; / then the keyword prior to / is searched for as <keyword>/ so that
;; help for slash arguments to keyword can be displayed.
(set (intern "|?BLANK"                  tacl-eldoc-obarray) "Use the ?BLANK directive to insert a blank line into a variable.")
(set (intern "|?FORMAT"                 tacl-eldoc-obarray) "?FORMAT changes the input format of the file from this line forward.")
(set (intern "|?SECTION"                tacl-eldoc-obarray) "Use the ?SECTION directive to signal the beginning of a variable definition in a file.")
(set (intern "|?TACL"                   tacl-eldoc-obarray) "Use the ?TACL directive to specify that the TACL statements following the directive in a file are the contents of a TACL variable.")

(set (intern "|ACTIVATE"                tacl-eldoc-obarray) "ACTIVATE Reactivates a previously suspended process")
(set (intern "|ADD"                     tacl-eldoc-obarray) "ADD DEFINE Creates one or more DEFINEs")
(set (intern "|ADDDSTTRANSITION"        tacl-eldoc-obarray) "ADDDSTTRANSITION Adds entries to daylight-saving time transition table")
(set (intern "|ADDUSER"                 tacl-eldoc-obarray) "ADDUSER (program) Adds new users to a group")
(set (intern "|ALARMOFF"                tacl-eldoc-obarray) "ALARMOFF (program) Turns off HP NonStop VLX system audio alarm")
(set (intern "|ALARMOFF"                tacl-eldoc-obarray) "ALARMOFF (program) Turns off NonStop VLX system audio alarm")
(set (intern "|ALTER"                   tacl-eldoc-obarray) "ALTER DEFINE Changes attributes of one or more DEFINEs")
(set (intern "|ALTPRI"                  tacl-eldoc-obarray) "ALTPRI Alters execution priority of a process")
(set (intern "|ASSIGN"                  tacl-eldoc-obarray) "ASSIGN Gives file attributes to logical-file descriptions used by application programs")
(set (intern "|ATTACHSEG"               tacl-eldoc-obarray) "ATTACHSEG Provides user access to a TACL segment file")
(set (intern "|BACKUPCPU"               tacl-eldoc-obarray) "BACKUPCPU Specifies backup CPU for current named TACL process, or deletes existing backup process")
(set (intern "|BREAK"                   tacl-eldoc-obarray) "BREAK Sets breakpoint on specified variable or lists all breakpoints")
(set (intern "|BUILTINS"                tacl-eldoc-obarray) "Shows TACL built-in functions and variables")
(set (intern "|BUSCMD"                  tacl-eldoc-obarray) "BUSCMD (program) Tells operating system that a bus is (or is not) available for use")
(set (intern "|CLEAR"                   tacl-eldoc-obarray) "CLEAR Deletes attributes previously set by ASSIGN or PARAM commands")
(set (intern "|COLUMNIZE"               tacl-eldoc-obarray) "Displays a list in columnar form")
(set (intern "|COMMENT"                 tacl-eldoc-obarray) "Begins comment line in TACL command file")
(set (intern "|COMPUTE"                 tacl-eldoc-obarray) "COMPUTE Performs calculation and displays result")
(set (intern "|COPYDUMP"                tacl-eldoc-obarray) "COPYDUMP (program) Copies and compresses tape dump file or existing disk dump file into a disk dump file")
(set (intern "|COPYDUMP"                tacl-eldoc-obarray) "COPYDUMP (program) Copies and compresses tape dump file or existing disk dump file into a disk dump file")
(set (intern "|COPYVAR"                 tacl-eldoc-obarray) "COPYVAR Copies one variable to another")
(set (intern "|CREATE"                  tacl-eldoc-obarray) "CREATE Creates an unstructured disk file")
(set (intern "|CREATE"                  tacl-eldoc-obarray) "CREATE Creates an unstructured disk file")
(set (intern "|CREATESEG"               tacl-eldoc-obarray) "CREATESEG Creates a TACL segment file")
(set (intern "|DEBUG"                   tacl-eldoc-obarray) "DEBUG Puts a process into debug state")
(set (intern "|DEFAULT"                 tacl-eldoc-obarray) "DEFAULT (program) Changes logon default setting for volume and subvolume names; sets default disk file security")
(set (intern "|DELETE"                  tacl-eldoc-obarray) "DELETE DEFINE Removes one or more DEFINEs from process file segment (PFS) of current TACL process")
(set (intern "|DELUSER"                 tacl-eldoc-obarray) "DELUSER (program) Deletes users from a group")
(set (intern "|DETACHSEG"               tacl-eldoc-obarray) "DETACHSEG Relinquishes use of a TACL segment file")
(set (intern "|ENV"                     tacl-eldoc-obarray) "Displays settings of TACL environmental parameters")
(set (intern "|EXIT"                    tacl-eldoc-obarray) "EXIT Used interactively, stops current process; used in a command file, stops execution of commands")
(set (intern "|FC"                      tacl-eldoc-obarray) "Retrieves, edits, and reexecutes lines in history buffer")
(set (intern "|FILEINFO"                tacl-eldoc-obarray) "Displays information about files")
(set (intern "|FILENAMES"               tacl-eldoc-obarray) "Displays names of files in a subvolume, using a file-name template")
(set (intern "|FILES"                   tacl-eldoc-obarray) "Displays names of files in a subvolume")
(set (intern "|FILETOVAR"               tacl-eldoc-obarray) "FILETOVAR Copies data from a file and appends it to a variable")
(set (intern "|HELP"                    tacl-eldoc-obarray) "Displays useful information about TACL")
(set (intern "|HISTORY"                 tacl-eldoc-obarray) "Displays previously issued command lines")
(set (intern "|HOME"                    tacl-eldoc-obarray) "HOME Specifies directory in which TACL searches first for variables")
(set (intern "|INFO"                    tacl-eldoc-obarray) "DEFINE Displays attributes and associated values in one or more DEFINEs residing in process file segment of current TACL process")
(set (intern "|INITTERM"                tacl-eldoc-obarray) "INITTERM Initializes home terminal by reinstating its default SETMODE settings")
(set (intern "|INLECHO"                 tacl-eldoc-obarray) "INLECHO Controls copying to TACL OUT file of lines sent to inline process")
(set (intern "|INLEOF"                  tacl-eldoc-obarray) "INLEOF Sends end-of-file indication to an inline process")
(set (intern "|INLOUT"                  tacl-eldoc-obarray) "INLOUT Controls copying to TACL OUT file of lines sent to OUT file of inline process")
(set (intern "|INLPREFIX"               tacl-eldoc-obarray) "INLPREFIX Establishes prefix that identifies lines to be passed to inline process")
(set (intern "|INLTO"                   tacl-eldoc-obarray) "INLTO Establishes variable to receive copies of lines sent to OUT file of inline process")
(set (intern "|JOIN"                    tacl-eldoc-obarray) "JOIN Converts multiple-line variable to single-line variable")
(set (intern "|KEEP"                    tacl-eldoc-obarray) "KEEP Removes bottom levels from a variable stack")
(set (intern "|KEYS"                    tacl-eldoc-obarray) "Displays current function-key variables")
(set (intern "|LIGHTS"                  tacl-eldoc-obarray) "LIGHTS (program) Controls processor panel lights")
(set (intern "|LOAD"                    tacl-eldoc-obarray) "LOAD Loads all properly formatted definitions from a TACL library")
(set (intern "|LOADEDFILES"             tacl-eldoc-obarray) "Displays the loadfiles used by a selected process")
(set (intern "|LOGOFF"                  tacl-eldoc-obarray) "LOGOFF Concludes TACL session")
(set (intern "|LOGON"                   tacl-eldoc-obarray) "LOGON Begins TACL session")
(set (intern "|OUTVAR"                  tacl-eldoc-obarray) "OUTVAR Displays contents of a variable")
(set (intern "|O[BEY]"                  tacl-eldoc-obarray) "O[BEY] Instructs TACL to execute commands from file you specify")
(set (intern "|PARAM"                   tacl-eldoc-obarray) "PARAM Assigns parameter value to a parameter name, or displays all current parameters and their values")
(set (intern "|PASSWORD"                tacl-eldoc-obarray) "PASSWORD (program) Establishes or changes your password")
(set (intern "|PAUSE"                   tacl-eldoc-obarray) "PAUSE Makes TACL stop prompting for commands and allows another process to control terminal")
(set (intern "|PMSEARCH"                tacl-eldoc-obarray) "PMSEARCH Defines subvolumes to be searched for program and macro files")
(set (intern "|PMSG"                    tacl-eldoc-obarray) "Controls process-identifier displays of processes you create or delete")
(set (intern "|POP"                     tacl-eldoc-obarray) "POP Removes top level of variable or built-in function")
(set (intern "|PPD"                     tacl-eldoc-obarray) "Displays names, cpu,pin designations, and ancestors of processes currently running")
(set (intern "|PURGE"                   tacl-eldoc-obarray) "PURGE Purges (deletes) a disk file")
(set (intern "|PUSH"                    tacl-eldoc-obarray) "PUSH A Adds a level to a variable")
(set (intern "|RELOAD"                  tacl-eldoc-obarray) "RELOAD (program) Reloads operating system image into a processor that was previously halted")
(set (intern "|REMOTEPASSWORD"          tacl-eldoc-obarray) "REMOTEPASSWORD Defines remote password for use in network security (runs")
(set (intern "|RESET"                   tacl-eldoc-obarray) "RESET DEFINE Restores attributes in DEFINE working set to their initial values")
(set (intern "|RPASSWRD"                tacl-eldoc-obarray) "RPASSWRD program)")
(set (intern "|RPASSWRD"                tacl-eldoc-obarray) "RPASSWRD (program) Establishes or changes remote password")
(set (intern "|RUN"                     tacl-eldoc-obarray) "RUN or RUND Runs a program; optionally puts resulting process into debug state")
(set (intern "|SEGINFO"                 tacl-eldoc-obarray) "Shows information about TACL segment files")
(set (intern "|SET"                     tacl-eldoc-obarray) "SET DEFINE SET DEFINE establishes a value for one or more DEFINE attributes in working attribute set")
(set (intern "|SET"                     tacl-eldoc-obarray) "SET DEFMODE Controls whether DEFINEs are enabled for current TACL process and are propagated to new processes")
(set (intern "|SET"                     tacl-eldoc-obarray) "SET HIGHPIN Sets the default PIN range for processes started by the current TACL process")
(set (intern "|SET"                     tacl-eldoc-obarray) "SET SWAP Sets swap volume for all subsequent RUN commands (unless swap volume is explicitly specified in a command)")
(set (intern "|SET"                     tacl-eldoc-obarray) "SET VARIABLE Changes contents of a variable level")
(set (intern "|SET"                     tacl-eldoc-obarray) "SET INSPECT Specifies whether INSPECT or DEBUG is default debugger for programs started by TACL")
(set (intern "|SETPROMPT"               tacl-eldoc-obarray) "SETPROMPT Changes TACL prompt")
(set (intern "|SETTIME"                 tacl-eldoc-obarray) "SETTIME Sets system date and time-of-day clocks")
(set (intern "|SHOW"                    tacl-eldoc-obarray) "Displays values of attributes set with SET command")
(set (intern "|SHOW"                    tacl-eldoc-obarray) "DEFINE Displays DEFINE attributes in working attribute set and their current values")
(set (intern "|SINK"                    tacl-eldoc-obarray) "SINK Disables the display of the result of the argument to SINK")
(set (intern "|STATUS"                  tacl-eldoc-obarray) "Displays status of running processes")
(set (intern "|STOP"                    tacl-eldoc-obarray) "STOP Stops and deletes a process")
(set (intern "|SUSPEND"                 tacl-eldoc-obarray) "SUSPEND Prevents a process from running until it is reactivated by an ACTIVATE command")
(set (intern "|SWITCH"                  tacl-eldoc-obarray) "SWITCH Causes backup TACL process to become primary and primary process to become a backup")
(set (intern "|SYSTEM"                  tacl-eldoc-obarray) "SYSTEM Changes your current default system")
(set (intern "|SYSTIMES"                tacl-eldoc-obarray) "Displays current date and time, plus date and time of last cold load")
(set (intern "|TACL"                    tacl-eldoc-obarray) "TACL (program) Starts TACL process on your local system or a remote system")
(set (intern "|TIME"                    tacl-eldoc-obarray) "Displays current system date and time of day")
(set (intern "|USE"                     tacl-eldoc-obarray) "USE Defines one or more directories in which TACL searches to find variables")
(set (intern "|USERS"                   tacl-eldoc-obarray) "(program) Displays attributes of users and groups")
(set (intern "|VARIABLES"               tacl-eldoc-obarray) "Displays names of all your variables")
(set (intern "|VARINFO"                 tacl-eldoc-obarray) "Displays information about specified variables")
(set (intern "|VARTOFILE"               tacl-eldoc-obarray) "VARTOFILE Copies data from a variable to a file")
(set (intern "|VCHANGE"                 tacl-eldoc-obarray) "VCHANGE Changes all occurrences of one string to another string within a range of lines in a variable")
(set (intern "|VCOPY"                   tacl-eldoc-obarray) "VCOPY Copies a range of lines from a variable and inserts it at a specified line position in another variable")
(set (intern "|VDELETE"                 tacl-eldoc-obarray) "VDELETE Deletes a range of lines from a variable")
(set (intern "|VFIND"                   tacl-eldoc-obarray) "VFIND Searches a range of lines in a variable for a specified string")
(set (intern "|VINSERT"                 tacl-eldoc-obarray) "VINSERT Inserts lines from current TACL IN file at a specified line position")
(set (intern "|VLIST"                   tacl-eldoc-obarray) "VLIST Lists a range of lines in a variable")
(set (intern "|VMOVE"                   tacl-eldoc-obarray) "VMOVE Deletes a range of lines from a variable, inserts them at a specified line position in another variable")
(set (intern "|VOLUME"                  tacl-eldoc-obarray) "VOLUME Changes your current default volume, subvolume, or security")
(set (intern "|WAKEUP"                  tacl-eldoc-obarray) "WAKEUP Sets wakeup mode")
(set (intern "|WHO"                     tacl-eldoc-obarray) "Displays information about your current default settings")
(set (intern "|XBUSDOWN"                tacl-eldoc-obarray) "XBUSDOWN Tells operating system that a bus is not available for use")
(set (intern "|XBUSUP"                  tacl-eldoc-obarray) "XBUSUP Tells operating system that a bus is available for use")
(set (intern "|YBUSDOWN"                tacl-eldoc-obarray) "YBUSDOWN Tells operating system that a bus is not available for use")
(set (intern "|YBUSUP"                  tacl-eldoc-obarray) "YBUSUP Tells operating system that a bus is available for use")
(set (intern "|_COMPAREV"               tacl-eldoc-obarray) "_COMPAREV Compares two variables")
(set (intern "|_CONTIME_TO_TEXT"        tacl-eldoc-obarray) "_CONTIME_TO_TEXT Converts numeric date and time to text form")
(set (intern "|_CONTIME_TO_TEXT_DATE"   tacl-eldoc-obarray) "_CONTIME_TO_TEXT_DATE Converts numeric date to text form")
(set (intern "|_CONTIME_TO_TEXT_TIME"   tacl-eldoc-obarray) "_CONTIME_TO_TEXT_TIME Converts numeric time to text form")
(set (intern "|_DEBUGGER"               tacl-eldoc-obarray) "_DEBUGGER Debugs TACL statements")
(set (intern "|_LONGEST"                tacl-eldoc-obarray) "_LONGEST Returns length of longest element in a space-separated list")
(set (intern "|_MONTH3"                 tacl-eldoc-obarray) "_MONTH3 Returns three-letter abbreviation for a month number")

(set (intern "|#ABEND"                  tacl-eldoc-obarray) "#ABEND Built-In Function Immediately terminates a process")
(set (intern "|#ABORTTRANSACTION"       tacl-eldoc-obarray) "#ABORTTRANSACTION Built-In Function Aborts and backs out a transaction")
(set (intern "|#ACTIVATEPROCESS"        tacl-eldoc-obarray) "#ACTIVATEPROCESS Built-In Function Returns process or process pair from suspended state to ready state")
(set (intern "|#ADDDSTTRANSITION"       tacl-eldoc-obarray) "#ADDDSTTRANSITION Built-In Function (Super-Group Only) Adds entry to daylight savings time transition table")
(set (intern "|#ALTERPRIORITY"          tacl-eldoc-obarray) "#ALTERPRIORITY Built-In Function Changes execution priority of a process or process pair")
(set (intern "|#APPEND"                 tacl-eldoc-obarray) "#APPEND Built-In Function Appends additional lines to a variable level")
(set (intern "|#APPENDV"                tacl-eldoc-obarray) "#APPENDV Built-In Function Appends a line from one variable level to another")
(set (intern "|#ARGUMENT"               tacl-eldoc-obarray) "#ARGUMENT Built-In Function Parses arguments to routines")
(set (intern "|#BACKUPCPU"              tacl-eldoc-obarray) "#BACKUPCPU Built-In Function Sets or changes the TACL backup CPU")
(set (intern "|#BEGINTRANSACTION"       tacl-eldoc-obarray) "#BEGINTRANSACTION Built-In Function Starts a new transaction")
(set (intern "|#BREAKPOINT"             tacl-eldoc-obarray) "#BREAKPOINT Built-In FunctionT Sets or deletes _DEBUGGER breakpoint for a specific variable level")
(set (intern "|#BUILTINS"               tacl-eldoc-obarray) "#BUILTINS Built-In Function Examines names of TACL built-in functions and variables")
(set (intern "|#CASE"                   tacl-eldoc-obarray) "#CASE Built-In Function Chooses one out of a set of options")
(set (intern "|#CHANGEUSER"             tacl-eldoc-obarray) "#CHANGEUSER Built-In Function Logs user on under different user ID")
(set (intern "|#CHARADDR"               tacl-eldoc-obarray) "#CHARADDR Built-In Function Converts line address to character address")
(set (intern "|#CHARBREAK"              tacl-eldoc-obarray) "#CHARBREAK Built-In Function Inserts line break in variable at character address")
(set (intern "|#CHARCOUNT"              tacl-eldoc-obarray) "#CHARCOUNT Built-In Function Obtains number of characters in variable")
(set (intern "|#CHARDEL"                tacl-eldoc-obarray) "#CHARDEL Built-In Function Deletes characters from variable at character address")
(set (intern "|#CHARFIND"               tacl-eldoc-obarray) "#CHARFIND Built-In Function Locates text in variable, searching forward from character address")
(set (intern "|#CHARFINDR"              tacl-eldoc-obarray) "#CHARFINDR Built-In Function Locates text in variable, searching backward from character address")
(set (intern "|#CHARFINDRV"             tacl-eldoc-obarray) "#CHARFINDRV Built-In Function Locates string in variable, searching backward from character address")
(set (intern "|#CHARFINDV"              tacl-eldoc-obarray) "#CHARFINDV Built-In Function Locates string in variable, searching forward from character address")
(set (intern "|#CHARGET"                tacl-eldoc-obarray) "#CHARGET Built-In Function Obtains copy of specified number of characters from a variable")
(set (intern "|#CHARGETV"               tacl-eldoc-obarray) "#CHARGETV Built-In Function Copies specified number of characters from one variable to another")
(set (intern "|#CHARINS"                tacl-eldoc-obarray) "#CHARINS Built-In Function Inserts text into a variable at character address")
(set (intern "|#CHARINSV"               tacl-eldoc-obarray) "#CHARINSV Built-In Function Inserts string into a variable at character address")
(set (intern "|#COLDLOADTACL"           tacl-eldoc-obarray) "#COLDLOADTACL Built-In Function Determines if TACL process is the cold-load TACL")
(set (intern "|#COMPAREV"               tacl-eldoc-obarray) "#COMPAREV Built-In Function Compares one variable with another")
(set (intern "|#COMPUTE"                tacl-eldoc-obarray) "#COMPUTE Built-In Function Returns value of expression")
(set (intern "|#COMPUTEJULIANDAYNO"     tacl-eldoc-obarray) "#COMPUTEJULIANDAYNO Built-In Function Converts Gregorian calendar date to a Julian day number")
(set (intern "|#COMPUTETIMESTAMP"       tacl-eldoc-obarray) "#COMPUTETIMESTAMP Built-In Function Converts calendar date to a four-word timestamp")
(set (intern "|#COMPUTETRANSID"         tacl-eldoc-obarray) "#COMPUTETRANSID Built-In Function Converts separate components of a transaction ID to one numeric transaction ID")
(set (intern "|#CONTIME"                tacl-eldoc-obarray) "#CONTIME Built-In Function Converts timestamp to seven-digit date and time")
(set (intern "|#CONVERTPHANDLE"         tacl-eldoc-obarray) "#CONVERTPHANDLE Built-In Function Converts a process file identifier to a process handle, or vice versa")
(set (intern "|#CONVERTPROCESSTIME"     tacl-eldoc-obarray) "#CONVERTPROCESSTIME Built-In Function Converts time value obtained by PROCESSTIME option of #PROCESSINFO")
(set (intern "|#CONVERTTIMESTAMP"       tacl-eldoc-obarray) "#CONVERTTIMESTAMP Built-In Function Converts GMT timestamp to a local-time-based timestamp, or a local-time-based timestamp to a GMT timestamp")
(set (intern "|#CREATEFILE"             tacl-eldoc-obarray) "#CREATEFILE Built-In Function Creates a file")
(set (intern "|#CREATEPROCESSNAME"      tacl-eldoc-obarray) "#CREATEPROCESSNAME Built-In Function Creates unique process name")
(set (intern "|#CREATEREMOTENAME"       tacl-eldoc-obarray) "#CREATEREMOTENAME Built- In Function Returns process name unique to specified system")
(set (intern "|#DEBUGPROCESS"           tacl-eldoc-obarray) "#DEBUGPROCESS Built-In Function Calls debugger for specified process")
(set (intern "|#DEF"                    tacl-eldoc-obarray) "#DEF Built-In Function Defines a variable")
(set (intern "|#DEFINEADD"              tacl-eldoc-obarray) "#DEFINEADD Built-In Function Adds a DEFINE to TACL context, using attributes in the working set")
(set (intern "|#DEFINEDELETE"           tacl-eldoc-obarray) "#DEFINEDELETE Built-In Function Deletes a DEFINE from TACL context")
(set (intern "|#DEFINEDELETEALL"        tacl-eldoc-obarray) "#DEFINEDELETEALL Built-In Function Deletes all DEFINEs from TACL context")
(set (intern "|#DEFINEINFO"             tacl-eldoc-obarray) "#DEFINEINFO Built-In Function Gets information about a DEFINE")
(set (intern "|#DEFINENAMES"            tacl-eldoc-obarray) "#DEFINENAMES Built-In Function Gets names of all DEFINEs that match specified template")
(set (intern "|#DEFINENEXTNAME"         tacl-eldoc-obarray) "#DEFINENEXTNAME Built-In Function Gets name of next DEFINE following specified DEFINE in sequence established by the operating system")
(set (intern "|#DEFINEREADATTR"         tacl-eldoc-obarray) "#DEFINEREADATTR Built-In Function Gets value of specified attribute")
(set (intern "|#DEFINERESTORE"          tacl-eldoc-obarray) "#DEFINERESTORE Built-In Function Creates or replaces active DEFINE, or replaces working set with contents of DEFINE previously saved with #DEFINESAVE")
(set (intern "|#DEFINERESTOREWORK"      tacl-eldoc-obarray) "#DEFINERESTOREWORK Built- In Function Restores DEFINE working set from background set")
(set (intern "|#DEFINESAVE"             tacl-eldoc-obarray) "#DEFINESAVE Built-In Function Saves copy of active DEFINE or working set for later restoration with #DEFINERESTORE")
(set (intern "|#DEFINESAVEWORK"         tacl-eldoc-obarray) "#DEFINESAVEWORK Built-In Function Saves DEFINE current working set to background set")
(set (intern "|#DEFINESETATTR"          tacl-eldoc-obarray) "#DEFINESETATTR Built-In Function Modifies value of specified DEFINE attribute in current working set")
(set (intern "|#DEFINESETLIKE"          tacl-eldoc-obarray) "#DEFINESETLIKE Built-In Function Initializes current working set with attributes of an existing DEFINE")
(set (intern "|#DEFINEVALIDATEWORK"     tacl-eldoc-obarray) "#DEFINEVALIDATEWORK Built- In Function Checks DEFINE current working set for consistency")
(set (intern "|#DELAY"                  tacl-eldoc-obarray) "#DELAY Built-In Function Causes TACL to wait for specified time")
(set (intern "|#DELTA"                  tacl-eldoc-obarray) "#DELTA Built-In Function Acts as a complex character processor")
(set (intern "|#DEVICEINFO"             tacl-eldoc-obarray) "#DEVICEINFO Built-In Function Gets detailed information about a device")
(set (intern "|#EMPTY"                  tacl-eldoc-obarray) "#EMPTY Built-In Function Determines whether specified string contains text")
(set (intern "|#EMPTYV"                 tacl-eldoc-obarray) "#EMPTYV Built-In Function Determines whether a variable level contains any lines")
(set (intern "|#EMSADDSUBJECT"          tacl-eldoc-obarray) "#EMSADDSUBJECT Built-In Function Adds subject token to event message buffer")
(set (intern "|#EMSADDSUBJECTV"         tacl-eldoc-obarray) "#EMSADDSUBJECTV Built-In Function Adds subject token to event message buffer, obtaining token values from a STRUCT")
(set (intern "|#EMSGET"                 tacl-eldoc-obarray) "#EMSGET Built-In Function Retrieves token values from SPI buffer")
(set (intern "|#EMSGETV"                tacl-eldoc-obarray) "#EMSGETV Built-In Function Copies token values from SPI buffer to a STRUCT")
(set (intern "|#EMSINIT"                tacl-eldoc-obarray) "#EMSINIT Built-In Function Initializes a STRUCT as event message buffer")
(set (intern "|#EMSINITV"               tacl-eldoc-obarray) "#EMSINITV Built-In Function Initializes STRUCT as event message buffer, obtaining initial values from another STRUCT")
(set (intern "|#EMSTEXT"                tacl-eldoc-obarray) "#EMSTEXT Built-In Function Converts information from event buffer to printable text")
(set (intern "|#EMSTEXTV"               tacl-eldoc-obarray) "#EMSTEXTV Built-In Function Converts information from event buffer to printable text, copies text to a STRUCT")
(set (intern "|#ENDTRANSACTION"         tacl-eldoc-obarray) "#ENDTRANSACTION Built-In Function Commits data base changes associated with a transaction")
(set (intern "|#EOF"                    tacl-eldoc-obarray) "#EOF Built-In Function Sets flag so that a process receives an end-of-file after reading all data in a variable")
(set (intern "|#ERRORTEXT"              tacl-eldoc-obarray) "#ERRORTEXT Built-In Function Used with exception handlers to catch error text")
(set (intern "|#EXCEPTION"              tacl-eldoc-obarray) "#EXCEPTION Built-In Function Determines why a routine was invoked during exception handling")
(set (intern "|#EXTRACT"                tacl-eldoc-obarray) "#EXTRACT Built-In Function Deletes first line of a variable level")
(set (intern "|#EXTRACTV"               tacl-eldoc-obarray) "#EXTRACTV Built-In Function Moves first line of a variable level to another variable")
(set (intern "|#FILEGETLOCKINFO"        tacl-eldoc-obarray) "#FILEGETLOCKINFO Built-In FunctionO Obtains information about record locks and file locks")
(set (intern "|#FILEINFO"               tacl-eldoc-obarray) "#FILEINFO Built-In Function Gets information about a file")
(set (intern "|#FILENAMES"              tacl-eldoc-obarray) "#FILENAMES Built-In Function Lists file names")
(set (intern "|#FILTER"                 tacl-eldoc-obarray) "#FILTER Built-In Function Indicates which exceptions a routine can handle")
(set (intern "|#FRAME"                  tacl-eldoc-obarray) "#FRAME Built-In Function Tracks pushed variables")
(set (intern "|#GETCONFIGURATION"       tacl-eldoc-obarray) "#GETCONFIGURATION Built-In Function Obtains settings of flags that affect TACL behavior")
(set (intern "|#GETPROCESSSTATE"        tacl-eldoc-obarray) "#GETPROCESSSTATE Built-In Function Obtains process state information about the current TACL process")
(set (intern "|#GETSCAN"                tacl-eldoc-obarray) "#GETSCAN Built-In Function Obtains number of characters passed over by #ARGUMENT")
(set (intern "|#HISTORY"                tacl-eldoc-obarray) "#HISTORY Built-In Function Operates on commands in history buffer")
(set (intern "|#IF"                     tacl-eldoc-obarray) "#IF Built-In Function Executes one of two options")
(set (intern "|#INITTERM"               tacl-eldoc-obarray) "#INITTERM Built-In Function Resets your home terminal to its configured settings")
(set (intern "|#INLINEEOF"              tacl-eldoc-obarray) "#INLINEEOF Built-In Function Sends end-of-file to process running under control of INLINE facility")
(set (intern "|#INPUT"                  tacl-eldoc-obarray) "#INPUT Built-In Function Reads information from TACL primary input file")
(set (intern "|#INPUTV"                 tacl-eldoc-obarray) "#INPUTV Built-In Function Reads information from TACL primary input file into a variable level")
(set (intern "|#INTERACTIVE"            tacl-eldoc-obarray) "#INTERACTIVE Built-In Function Determines whether your TACL is interactive")
(set (intern "|#INTERPRETJULIANDAYNO"   tacl-eldoc-obarray) "#INTERPRETJULIANDAYNO Built-In Function Converts Julian day number to year, month, and day")
(set (intern "|#INTERPRETTIMESTAMP"     tacl-eldoc-obarray) "#INTERPRETTIMESTAMP Built- In Function Breaks down four-word timestamp to its component parts")
(set (intern "|#INTERPRETTRANSID"       tacl-eldoc-obarray) "#INTERPRETTRANSID Built-In Function Converts numeric transaction ID to its separate component values")
(set (intern "|#JULIANTIMESTAMP"        tacl-eldoc-obarray) "#JULIANTIMESTAMP Built-In Function Obtains four-word timestamp")
(set (intern "|#KEEP"                   tacl-eldoc-obarray) "#KEEP Built-In Function Removes all but specified level of a variable")
(set (intern "|#KEYS"                   tacl-eldoc-obarray) "#KEYS Built-In Function Displays defined function keys")
(set (intern "|#LINEADDR"               tacl-eldoc-obarray) "#LINEADDR Built-In Function Converts character address to line address")
(set (intern "|#LINEBREAK"              tacl-eldoc-obarray) "#LINEBREAK Built-In Function Inserts line break in variable at line address")
(set (intern "|#LINECOUNT"              tacl-eldoc-obarray) "#LINECOUNT Built-In unction Obtains number of lines in a variable")
(set (intern "|#LINEDEL"                tacl-eldoc-obarray) "#LINEDEL Built-In Function Deletes lines from variable at line address")
(set (intern "|#LINEFIND"               tacl-eldoc-obarray) "#LINEFIND Built-In Function Locates text in variable, searching forward from line address")
(set (intern "|#LINEFINDR"              tacl-eldoc-obarray) "#LINEFINDR Built-In Function Locates text in variable, searching backward from line address")
(set (intern "|#LINEFINDRV"             tacl-eldoc-obarray) "#LINEFINDRV Built-In Function Locates string in variable, searching backward from line address")
(set (intern "|#LINEFINDV"              tacl-eldoc-obarray) "#LINEFINDV Built-In Function Locates string in variable, searching forward from line address")
(set (intern "|#LINEGET"                tacl-eldoc-obarray) "#LINEGET Built-In Function Gets copy of specified number of lines from a variable")
(set (intern "|#LINEGETV"               tacl-eldoc-obarray) "#LINEGETV Built-In Function Copies specified number of lines from one variable to another")
(set (intern "|#LINEINS"                tacl-eldoc-obarray) "#LINEINS Built-In Function Inserts text into a variable at line address")
(set (intern "|#LINEINSV"               tacl-eldoc-obarray) "#LINEINSV Built-In Function Inserts string into a variable at line address")
(set (intern "|#LINEJOIN"               tacl-eldoc-obarray) "#LINEJOIN Built-In Function Deletes line break at end of a line, joining following line to it")
(set (intern "|#LOAD"                   tacl-eldoc-obarray) "#LOAD Built-In Function Processes a TACL library file")
(set (intern "|#XLOADEDFILES"           tacl-eldoc-obarray) "#XLOADEDFILES Built-In Function Gets information about all LOADFILES associated with a given process")
(set (intern "|#LOCKINFO"               tacl-eldoc-obarray) "#LOCKINFO Built-In Function Gets information about record locks")
(set (intern "|#LOGOFF"                 tacl-eldoc-obarray) "#LOGOFF Built-In Function Logs off current TACL")
(set (intern "|#LOOKUPPROCESS"          tacl-eldoc-obarray) "#LOOKUPPROCESS Built-In Function Gets information about a PPD entry")
(set (intern "|#LOOP"                   tacl-eldoc-obarray) "#LOOP Built-In Function Repeatedly executes one or more statements in a function")
(set (intern "|#MATCH"                  tacl-eldoc-obarray) "#MATCH Built-In Function Determines whether given string satisfies a template")
(set (intern "|#MOM"                    tacl-eldoc-obarray) "#MOM Built-In Function Obtains identity of creator process")
(set (intern "|#MORE"                   tacl-eldoc-obarray) "#MORE Built-In Function Determines whether an entire argument has been consumed")
(set (intern "|#MYGMOM"                 tacl-eldoc-obarray) "#MYGMOM Built-In Function Obtains identity of TACL job ancestor process")
(set (intern "|#MYPID"                  tacl-eldoc-obarray) "#MYPID Built-In Function Obtains your CPU,PIN number")
(set (intern "|#MYSYSTEM"               tacl-eldoc-obarray) "#MYSYSTEM Built-In Function Determines name of system executing current TACL")
(set (intern "|#NEWPROCESS"             tacl-eldoc-obarray) "#NEWPROCESS Built-In Function Starts a process")
(set (intern "|#NEXTFILENAME"           tacl-eldoc-obarray) "#NEXTFILENAME Built-In Function Determines file following specified file")
(set (intern "|#OPENINFO"               tacl-eldoc-obarray) "#OPENINFO Built-In Function Gets information about file openers")
(set (intern "|#OUTPUT"                 tacl-eldoc-obarray) "#OUTPUT Built-In Function Writes data to an output file")
(set (intern "|#OUTPUTV"                tacl-eldoc-obarray) "#OUTPUTV Built-In Function Writes contents of a variable level to an output file")
(set (intern "|#PAUSE"                  tacl-eldoc-obarray) "#PAUSE Built-In Function Gives control of your terminal to another process")
(set (intern "|#POP"                    tacl-eldoc-obarray) "#POP Built-In Function Deletes top level of variables")
(set (intern "|#PROCESS"                tacl-eldoc-obarray) "#PROCESS Built-In Function Obtains identity of last process created or paused for by TACL")
(set (intern "|#PROCESSEXISTS"          tacl-eldoc-obarray) "#PROCESSEXISTS Built-In Function Determines whether a process exists")
(set (intern "|#PROCESSINFO"            tacl-eldoc-obarray) "#PROCESSINFO Built-In Function Requests information about a process")
(set (intern "|#PROCESSLAUNCH"          tacl-eldoc-obarray) "#PROCESSLAUNCH Built-In Function Starts a process")
(set (intern "|#PROCESSORSTATUS"        tacl-eldoc-obarray) "#PROCESSORSTATUS Built-In Function Determines status of 16 possible CPUs on a given system")
(set (intern "|#PROCESSORTYPE"          tacl-eldoc-obarray) "#PROCESSORTYPE Built-In Function Determines processor type of given system or process")
(set (intern "|#PURGE"                  tacl-eldoc-obarray) "#PURGE Built-In Function Deletes a file")
(set (intern "|#PUSH"                   tacl-eldoc-obarray) "#PUSH Built-In Function Creates new top level for variables")
(set (intern "|#RAISE"                  tacl-eldoc-obarray) "#RAISE Built-In Function Defines exception to be filtered by routine")
(set (intern "|#RENAME"                 tacl-eldoc-obarray) "#RENAME Built-In Function Changes name of existing disk file")
(set (intern "|#REPLY"                  tacl-eldoc-obarray) "#REPLY Built-In Function Adds text to reply if TACL IN file is $RECEIVE")
(set (intern "|#REPLYV"                 tacl-eldoc-obarray) "#REPLYV Built-In Function Adds copy of text from variable to reply if TACL IN file is $RECEIVE")
(set (intern "|#REQUESTER"              tacl-eldoc-obarray) "#REQUESTER Built-In Function Reads from and writes to files")
(set (intern "|#RESET"                  tacl-eldoc-obarray) "#RESET Built-In Function Sets argument pointer, frame pointer, reply value, and result text")
(set (intern "|#REST"                   tacl-eldoc-obarray) "#REST Built-In Function Obtains remaining argument string for current routine")
(set (intern "|#RESULT"                 tacl-eldoc-obarray) "#RESULT Built-In Function Supplies text that replaces original invocation of routine")
(set (intern "|#RETURN"                 tacl-eldoc-obarray) "#RETURN Built-In Function Exits from a routine immediately")
(set (intern "|#ROUTINENAME"            tacl-eldoc-obarray) "#ROUTINENAME Built-In Function Obtains name of variable in which containing routine resides")
(set (intern "|#SEGMENT"                tacl-eldoc-obarray) "#SEGMENT Built-In Function Obtains name of segment file that TACL is using for its variables")
(set (intern "|#SEGMENTCONVERT"         tacl-eldoc-obarray) "#SEGMENTCONVERT Built-In Function Converts segment file between C00/C10 format and newer format")
(set (intern "|#SEGMENTINFO"            tacl-eldoc-obarray) "#SEGMENTINFO Built-In Function Gets information about segments being used by TACL")
(set (intern "|#SEGMENTVERSION"         tacl-eldoc-obarray) "#SEGMENTVERSION Built-In Function Determines whether segment file is C00/C10 format or newer format")
(set (intern "|#SERVER"                 tacl-eldoc-obarray) "#SERVER Built-In Function Creates and deletes servers")
(set (intern "|#SET"                    tacl-eldoc-obarray) "#SET Built-In Function Puts data in a variable level")
(set (intern "|#SETBYTES"               tacl-eldoc-obarray) "#SETBYTES Built-In Function Copies as many bytes as can fit from one STRUCT or STRUCT item to another")
(set (intern "|#SETCONFIGURATION"       tacl-eldoc-obarray) "#SETCONFIGURATION Built-In Function Sets the configuration of the running TACL process")
(set (intern "|#SETMANY"                tacl-eldoc-obarray) "#SETMANY Built-In Function Sets more than one variable level")
(set (intern "|#SETPROCESSSTATE"        tacl-eldoc-obarray) "#SETPROCESSSTATE Built-In Function Sets a process state flag for the current TACL process")
(set (intern "|#SETSCAN"                tacl-eldoc-obarray) "#SETSCAN Built-In Function Indicates position at which next #ARGUMENT is to resume processing arguments")
(set (intern "|#SETSYSTEMCLOCK"         tacl-eldoc-obarray) "#SETSYSTEMCLOCK Built-In Function (Super-Group Only) Changes setting of system clock")
(set (intern "|#SETV"                   tacl-eldoc-obarray) "#SETV Built-In Function Use Copies one variable level to another")
(set (intern "|#SHIFTSTRING"            tacl-eldoc-obarray) "#SHIFTSTRING Built-In Function Changes text from uppercase to lowercase or from lowercase to uppercase")
(set (intern "|#SORT"                   tacl-eldoc-obarray) "#SORT Built-In Function Sorts a list of text")
(set (intern "|#SPIFORMATCLOSE"         tacl-eldoc-obarray) "#SPIFORMATCLOSE Built-In Function Closes an open EMS formatter template file")
(set (intern "|#SSGET"                  tacl-eldoc-obarray) "#SSGET Built-In Function Retrieves binary token values from an SPI buffer and returns an external representation of those values")
(set (intern "|#SSGETV"                 tacl-eldoc-obarray) "#SSGETV Built-In Function Copies binary token values from an SPI buffer to a STRUCT")
(set (intern "|#SSINIT"                 tacl-eldoc-obarray) "#SSINIT Built-In Function Prepares a STRUCT for use with other #SSxxx built-in functions")
(set (intern "|#SSMOVE"                 tacl-eldoc-obarray) "#SSMOVE Built-In Function Copies tokens from one SPI buffer to another")
(set (intern "|#SSNULL"                 tacl-eldoc-obarray) "#SSNULL Built-In Function Initializes extensible structured tokens")
(set (intern "|#SSPUT"                  tacl-eldoc-obarray) "#SSPUT Built-In Function Converts external representation of token values to binary form, puts them in SPI buffer")
(set (intern "|#SSPUTV"                 tacl-eldoc-obarray) "#SSPUTV Built-In Function Copies binary token values from a variable level into an SPI buffer")
(set (intern "|#STOP"                   tacl-eldoc-obarray) "#STOP Built-In Function Terminates a process")
(set (intern "|#SUSPENDPROCESS"         tacl-eldoc-obarray) "#SUSPENDPROCESS Built-In Function Suspends a process")
(set (intern "|#SWITCH"                 tacl-eldoc-obarray) "#SWITCH Built-In Function Switches TACL to its backup process")
(set (intern "|#SYSTEM"                 tacl-eldoc-obarray) "#SYSTEM Built-In Function Temporarily changes your default system")
(set (intern "|#SYSTEMNAME"             tacl-eldoc-obarray) "#SYSTEMNAME Built-In Function Requests a system by name")
(set (intern "|#SYSTEMNUMBER"           tacl-eldoc-obarray) "#SYSTEMNUMBER Built-In Function Requests a system by number")
(set (intern "|#TACLOPERATION"          tacl-eldoc-obarray) "#TACLOPERATION Built-In Function Determines whether TACL is reading commands from IN or $RECEIVE")
(set (intern "|#TACLVERSION"            tacl-eldoc-obarray) "#TACLVERSION Built-In Function Obtains TACL product number")
(set (intern "|#TIMESTAMP"              tacl-eldoc-obarray) "#TIMESTAMP Built-In Function Obtains internal form of CPU interval clock")
(set (intern "|#TOSVERSION"             tacl-eldoc-obarray) "#TOSVERSION Built-In Function Obtains current RVU of the operating system")
(set (intern "|#UNFRAME"                tacl-eldoc-obarray) "#UNFRAME Built-In Function Pops all variables pushed since #FRAME")
(set (intern "|#USERID"                 tacl-eldoc-obarray) "#USERID Built-In Function Specifies a user by user ID")
(set (intern "|#USERNAME"               tacl-eldoc-obarray) "#USERNAME Built-In Function Specifies a user by user name")
(set (intern "|#VARIABLEINFO"           tacl-eldoc-obarray) "#VARIABLEINFO Built-In Function Gets information about a variable")
(set (intern "|#VARIABLES"              tacl-eldoc-obarray) "#VARIABLES Built-In Function Obtains names of all variables in your home directory")
(set (intern "|#VARIABLESV"             tacl-eldoc-obarray) "#VARIABLESV Built-In Function Obtains names of all your variables, puts them on separate lines in an existing variable level")
(set (intern "|#WAIT"                   tacl-eldoc-obarray) "#WAIT Built-In Function Specifies variables for which a routine must wait")
(set (intern "|#XFILEINFO"              tacl-eldoc-obarray) "#XFILEINFO Built-In Function Implements FILEINFO command")
(set (intern "|#XFILENAMES"             tacl-eldoc-obarray) "#XFILENAMES Built-In Function Implements FILENAMES command")
(set (intern "|#XFILES"                 tacl-eldoc-obarray) "#XFILES Built-In Function Implements FILES command")
(set (intern "|#XLOGON"                 tacl-eldoc-obarray) "#XLOGON Built-In Function Implements LOGON command")
(set (intern "|#XPPD"                   tacl-eldoc-obarray) "#XPPD Built-In Function Implements PPD command")
(set (intern "|#XSTATUS"                tacl-eldoc-obarray) "#XSTATUS Built-In Function Implements STATUS command")

(set (intern "|#ASSIGN"                 tacl-eldoc-obarray) "#ASSIGN Built-In Variable Holds information about all currently defined unit names")
(set (intern "|#BREAKMODE"              tacl-eldoc-obarray) "#BREAKMODE Built-In Variable Affects BREAK key operation")
(set (intern "|#CHARACTERRULES"         tacl-eldoc-obarray) "#CHARACTERRULES Built-In Variable Holds name of current character-processing rules file")
(set (intern "|#DEFAULTS"               tacl-eldoc-obarray) "#DEFAULTS Built-In Variable Holds volume defaults you set")
(set (intern "|#DEFINEMODE"             tacl-eldoc-obarray) "#DEFINEMODE Built-In Variable Holds flag indicating whether DEFINEs can be used")
(set (intern "|#ERRORNUMBERS"           tacl-eldoc-obarray) "#ERRORNUMBERS Built-In Variable Holds information about the latest error detected by the current TACL process")
(set (intern "|#EXIT"                   tacl-eldoc-obarray) "#EXIT Built-In Variable Holds state of exit flag")
(set (intern "|#HELPKEY"                tacl-eldoc-obarray) "#HELPKEY Built-In Variable Holds name of current help key")
(set (intern "|#HIGHPIN"                tacl-eldoc-obarray) "#HIGHPIN Built-In Variable Specifies the default PIN range for new processes")
(set (intern "|#HOME"                   tacl-eldoc-obarray) "#HOME Built-In Variable Represents your home directory")
(set (intern "|#IN"                     tacl-eldoc-obarray) "#IN Built-In Variable Holds name of IN file used by TACL")
(set (intern "|#INFORMAT"               tacl-eldoc-obarray) "#INFORMAT Built-In Variable Represents formatting mode for #INPUT")
(set (intern "|#INPUTEOF"               tacl-eldoc-obarray) "#INPUTEOF Built-In Variable Holds state of INPUTEOF flag")
(set (intern "|#INLINEECHO"             tacl-eldoc-obarray) "#INLINEECHO Built-In Variable Controls whether TACL echoes to its OUT file lines passed as input to inline processes")
(set (intern "|#INLINEOUT"              tacl-eldoc-obarray) "#INLINEOUT Built-In Variable Controls whether TACL copies to its own OUT file lines written by inline processes to their OUT files")
(set (intern "|#INLINEPREFIX"           tacl-eldoc-obarray) "#INLINEPREFIX Built- In Variable Holds prefix used to identify lines to be passed to inline processes instead of being acted upon by TACL")
(set (intern "|#INLINEPROCESS"          tacl-eldoc-obarray) "#INLINEPROCESS Built-In Variable Holds process ID of current inline process, if such exist")
(set (intern "|#INLINETO"               tacl-eldoc-obarray) "#INLINETO Built-In Variable Holds name of variable, if any, to which TACL appends lines written by inline processes to their OUT files")
(set (intern "|#INSPECT"                tacl-eldoc-obarray) "#INSPECT Built-In Variable Holds state of INSPECT flag")
(set (intern "|#MYTERM"                 tacl-eldoc-obarray) "#MYTERM Built-In Variable Holds name of your home terminal")
(set (intern "|#OUT"                    tacl-eldoc-obarray) "#OUT Built-In Variable Holds name of OUT file used by TACL")
(set (intern "|#OUTFORMAT"              tacl-eldoc-obarray) "#OUTFORMAT Built-In Variable Represents formatting mode for #OUTPUT")
(set (intern "|#PARAM"                  tacl-eldoc-obarray) "#PARAM Built-In Variable Holds list of all your parameters, or a specified parameter")
(set (intern "|#PMSEARCHLIST"           tacl-eldoc-obarray) "#PMSEARCHLIST Built-In Variable Holds list of subvolumes to be searched for program and macro files")
(set (intern "|#PMSG"                   tacl-eldoc-obarray) "#PMSG Built-In Variable Holds state of PMSG flag")
(set (intern "|#PREFIX"                 tacl-eldoc-obarray) "#PREFIX Built-In Variable Holds contents of prefix string")
(set (intern "|#PROMPT"                 tacl-eldoc-obarray) "#PROMPT Built-In Variable Represents state of prompt flag")
(set (intern "|#REPLYPREFIX"            tacl-eldoc-obarray) "#REPLYPREFIX Built- In Variable Holds value of your reply prefix")
(set (intern "|#ROUTEPMSG"              tacl-eldoc-obarray) "#ROUTEPMSG Built-In Variable Suppresses the outputting of system and process messages")
(set (intern "|#SHIFTDEFAULT"           tacl-eldoc-obarray) "#SHIFTDEFAULT Built- In Variable Holds #SHIFTSTRING default")
(set (intern "|#TACLSECURITY"           tacl-eldoc-obarray) "#TACLSECURITY Built-In Variable Represents TACL security")
(set (intern "|#TRACE"                  tacl-eldoc-obarray) "#TRACE Built-In Variable Represents state of TRACE flag")
(set (intern "|#USELIST"                tacl-eldoc-obarray) "#USELIST Built-In Variable Holds your use list")
(set (intern "|#WAKEUP"                 tacl-eldoc-obarray) "#WAKEUP Built-In Variable Represents setting of WAKEUP flag")
(set (intern "|#WIDTH"                  tacl-eldoc-obarray) "#WIDTH Built-In Variable Holds value of width register")

(set (intern "?BLANK"                   tacl-eldoc-obarray) "?BLANK")
(set (intern "?FORMAT"                  tacl-eldoc-obarray) "?FORMAT {PLAIN|QUOTED|TACL}")
(set (intern "?SECTION"                 tacl-eldoc-obarray) "?SECTION <variable-name> <variable-type>")
(set (intern "?TACL"                    tacl-eldoc-obarray) "?TACL <variable-type>")
(set (intern "#ABEND"                   tacl-eldoc-obarray) "#ABEND [ / option [ , option ] ... / ] [ [\\node-name.]{$process-name | cpu,pin } [ text ] ]")
(set (intern "#ABEND/"                  tacl-eldoc-obarray) "#ABEND /COMPLETIONCODE num | ERROR | SUBSYS ssid | TERMINATIONINFO num/")
(set (intern "#ABORTTRANSACTION"        tacl-eldoc-obarray) "#ABORTTRANSACTION")
(set (intern "#ACTIVATEPROCESS"         tacl-eldoc-obarray) "#ACTIVATEPROCESS [ [\\ node-name.]{$ process-name | cpu,pin} ]")
(set (intern "#ADDDSTTRANSITION"        tacl-eldoc-obarray) "#ADDDSTTRANSITION low-gmt high-gmt offset")
(set (intern "#ALTERPRIORITY"           tacl-eldoc-obarray) "#ALTERPRIORITY [ [\\ node-name.]{$ process-name | cpu,pin } ] pri")
(set (intern "#APPEND"                  tacl-eldoc-obarray) "#APPEND to-variable-level [ text ]")
(set (intern "#APPENDV"                 tacl-eldoc-obarray) "#APPENDV to-variable-level { from-variable-level | string }")
(set (intern "#ARGUMENT"                tacl-eldoc-obarray) "#ARGUMENT [/option[,option ].../]ASSIGN[/SYNTAX/]|ATTRIBUTENAME|ATTRIBUTEVALUE|CHARACTERS/char-option/|CLOSEPAREN|COMMA|DEFINENAME|DEFINETEMPLATE|DEVICE[/SYNTAX/]|END|FILENAME[/file-option/]|GMOMJOBID|JOBID|KEYWORD/WORDLIST keyword .../|NUMBER[/range-option/]|OPENPAREN|OTHERWISE|PARAM[/SYNTAX/]|PARAMVALUE|PROCESSID[/SYNTAX/]|PROCESSNAME[/SYNTAX/]|SECURITY[/LENGTH <num>/]|SEMICOLON|SLASH|STRING|SUBSYSTEM|SUBVOL|SUBVOLTEMPLATE|SYSTEMNAME[/SYNTAX/]|TEMPLATE|TEXT|TOKEN/TOKEN token-text .../|TRANSID|USER[/{SYNTAX|USERNAME}/]|VARIABLE[/var-option/]|WORD[/SPACE/]")
(set (intern "#ARGUMENT/"               tacl-eldoc-obarray) "#ARGUMENT /PEEK | TEXT <var> | VALUE <var>/")
(set (intern "CHARACTERS/"              tacl-eldoc-obarray) "CHARACTERS/START num,WIDTH num/")
(set (intern "FILENAME/"                tacl-eldoc-obarray) "FILENAME/SEARCHLIST search-place,SYNTAX/")
(set (intern "NUMBER/"                  tacl-eldoc-obarray) "NUMBER/MINIMUM <num>,MAXIMUM <num>/")
(set (intern "VARIABLE/"                tacl-eldoc-obarray) "VARIABLE/ALLOW <type>,FORBID <type>,QUALIFIED,SYNTAX,UNQUALIFIED/")
(set (intern "#ASSIGN"                  tacl-eldoc-obarray) "#ASSIGN [ / option [ , option ] ... / logical-unit ]")
(set (intern "#ASSIGN/"                 tacl-eldoc-obarray) "#ASSIGN/ACCESS,BLOCK,CODE,EXCLUSION,EXISTENCE,FLENAME,PRIMARY,RECORD,SECONDARY/")
(set (intern "#BACKUPCPU"               tacl-eldoc-obarray) "#BACKUPCPU [ cpu ]")
(set (intern "#BEGINTRANSACTION"        tacl-eldoc-obarray) "#BEGINTRANSACTION")
(set (intern "#BREAKMODE"               tacl-eldoc-obarray) "#BREAKMODE")
(set (intern "#BREAKPOINT"              tacl-eldoc-obarray) "#BREAKPOINT variable-level state")
(set (intern "#BUILTINS"                tacl-eldoc-obarray) "#BUILTINS [ / { FUNCTIONS | VARIABLES } / ]")
(set (intern "#CASE"                    tacl-eldoc-obarray) "#CASE text | label-1 | [ option-text-1 ] | label-2 | [ option-text-2 ] ... | OTHERWISE | [ option-text-n ]")
(set (intern "#CHANGEUSER"              tacl-eldoc-obarray) "#CHANGEUSER [ / CHANGEDEFAULTS / ] { group-name.user-name | group-id,user-id | alias } password")
(set (intern "#CHARACTERRULES"          tacl-eldoc-obarray) "#CHARACTERRULES")
(set (intern "#CHARADDR"                tacl-eldoc-obarray) "#CHARADDR variable-level line-addr")
(set (intern "#CHARBREAK"               tacl-eldoc-obarray) "#CHARBREAK variable-level char-addr")
(set (intern "#CHARCOUNT"               tacl-eldoc-obarray) "#CHARCOUNT variable-level")
(set (intern "#CHARDEL"                 tacl-eldoc-obarray) "#CHARDEL variable-level char-addr-1 [ FOR char-count | TO char-addr-2 ]")
(set (intern "#CHARFIND"                tacl-eldoc-obarray) "#CHARFIND [ / EXACT / ] variable-level char-addr text")
(set (intern "#CHARFINDR"               tacl-eldoc-obarray) "#CHARFINDR [ / EXACT / ] variable-level char-addr text")
(set (intern "#CHARFINDRV"              tacl-eldoc-obarray) "#CHARFINDRV [ / EXACT / ] variable-level char-addr string")
(set (intern "#CHARFINDV"               tacl-eldoc-obarray) "#CHARFINDV [ / EXACT / ] string-1 char-addr string-2")
(set (intern "#CHARGET"                 tacl-eldoc-obarray) "#CHARGET variable-level char-addr-1 [ FOR char-count | TO char-addr-2 ]")
(set (intern "#CHARGETV"                tacl-eldoc-obarray) "#CHARGETV var-1 var-2 char-addr-1 [ FOR char-count | TO char-addr-2 ]")
(set (intern "#CHARINS"                 tacl-eldoc-obarray) "#CHARINS string char-addr text")
(set (intern "#CHARINSV"                tacl-eldoc-obarray) "#CHARINSV variable-level char-addr string")
(set (intern "#COLDLOADTACL"            tacl-eldoc-obarray) "#COLDLOADTACL")
(set (intern "#COMPAREV"                tacl-eldoc-obarray) "#COMPAREV string-1 string-2")
(set (intern "#COMPUTE"                 tacl-eldoc-obarray) "#COMPUTE expression")
(set (intern "#COMPUTEJULIANDAYNO"      tacl-eldoc-obarray) "#COMPUTEJULIANDAYNO year month day")
(set (intern "#COMPUTETIMESTAMP"        tacl-eldoc-obarray) "#COMPUTETIMESTAMP year month day hour min sec milli micro")
(set (intern "#COMPUTETRANSID"          tacl-eldoc-obarray) "#COMPUTETRANSID system cpu sequence crash-count")
(set (intern "#CONTIME"                 tacl-eldoc-obarray) "#CONTIME timestamp")
(set (intern "#CONVERTPHANDLE"          tacl-eldoc-obarray) "#CONVERTPHANDLE { / PROCESSID / integer-string } | { / INTEGERS / process-identifier }")
(set (intern "#CONVERTPROCESSTIME"      tacl-eldoc-obarray) "#CONVERTPROCESSTIME process-time")
(set (intern "#CONVERTTIMESTAMP"        tacl-eldoc-obarray) "#CONVERTTIMESTAMP gmt-timestamp direction [ \\ node-name ]")
(set (intern "#CREATEFILE"              tacl-eldoc-obarray) "#CREATEFILE [ / option [ , option ] / ] file-name")
(set (intern "#CREATEFILE/"             tacl-eldoc-obarray) "#CREATEFILE/EXTENT <num>,FILEFORMAT <num>,file-name,FILENAMEV <var>,PHYSICALVOLUME <phys-name>,/")
(set (intern "#CREATEPROCESSNAME"       tacl-eldoc-obarray) "#CREATEPROCESSNAME")
(set (intern "#CREATEREMOTENAME"        tacl-eldoc-obarray) "#CREATEREMOTENAME \\ node-name")
(set (intern "#DEBUGPROCESS"            tacl-eldoc-obarray) "#DEBUGPROCESS [ / NOW / ] [\\ node-name.]{$ process-name | cpu,pin } [ , TERM [\\ node-name.]$ terminal-name ]")
(set (intern "#DEF"                     tacl-eldoc-obarray) "#DEF variable { { ALIAS | DELTA | MACRO | ROUTINE |TEXT } enclosure } | { {DIRECTORY [ segment-spec ]} | {STRUCT structure-body} }")
(set (intern "#DEFAULTS"                tacl-eldoc-obarray) "#DEFAULTS [ / option [ , option ] / ]")
(set (intern "#DEFAULTS/"               tacl-eldoc-obarray) "#DEFAULTS/{CURRENT|SAVED}/")
(set (intern "#DEFINEADD"               tacl-eldoc-obarray) "#DEFINEADD define-name [ flag ]")
(set (intern "#DEFINEDELETE"            tacl-eldoc-obarray) "#DEFINEDELETE define-name")
(set (intern "#DEFINEDELETEALL"         tacl-eldoc-obarray) "#DEFINEDELETEALL")
(set (intern "#DEFINEINFO"              tacl-eldoc-obarray) "#DEFINEINFO define-name")
(set (intern "#DEFINEMODE"              tacl-eldoc-obarray) "#DEFINEMODE")
(set (intern "#DEFINENAMES"             tacl-eldoc-obarray) "#DEFINENAMES define-template")
(set (intern "#DEFINENEXTNAME"          tacl-eldoc-obarray) "#DEFINENEXTNAME [ define-name ]")
(set (intern "#DEFINEREADATTR"          tacl-eldoc-obarray) "#DEFINEREADATTR { define-name | _ } { attribute-name | cursor-mode }")
(set (intern "#DEFINERESTORE"           tacl-eldoc-obarray) "#DEFINERESTORE [ / option [ , option ] ... / ] buffer")
(set (intern "#DEFINERESTORE/"          tacl-eldoc-obarray) "#DEFINERESTORE/{REPLACE|WORK}/")
(set (intern "#DEFINERESTOREWORK"       tacl-eldoc-obarray) "#DEFINERESTOREWORK")
(set (intern "#DEFINESAVE"              tacl-eldoc-obarray) "#DEFINESAVE [ / WORK / ] define-name buffer")
(set (intern "#DEFINESAVEWORK"          tacl-eldoc-obarray) "#DEFINESAVEWORK")
(set (intern "#DEFINESETATTR"           tacl-eldoc-obarray) "#DEFINESETATTR attribute-name [ attribute-value ]")
(set (intern "#DEFINESETLIKE"           tacl-eldoc-obarray) "#DEFINESETLIKE define-name")
(set (intern "#DEFINEVALIDATEWORK"      tacl-eldoc-obarray) "#DEFINEVALIDATEWORK")
(set (intern "#DELAY"                   tacl-eldoc-obarray) "#DELAY csecs")
(set (intern "#DELTA"                   tacl-eldoc-obarray) "#DELTA [ / COMMANDS variable-level / ] [ text ]")
(set (intern "#DEVICEINFO"              tacl-eldoc-obarray) "#DEVICEINFO / option [ , option ] ... /{ $ device-name | file-name }")
(set (intern "#DEVICEINFO/"             tacl-eldoc-obarray) "#DEVICEINFO /AUDITED,DEVICETYPE,RECORDLENGTH,SUBTYPE/")
(set (intern "#EMPTY"                   tacl-eldoc-obarray) "#EMPTY [ text ]")
(set (intern "#EMPTYV"                  tacl-eldoc-obarray) "#EMPTYV [ / BLANK / ] string")
(set (intern "#EMSADDSUBJECT"           tacl-eldoc-obarray) "#EMSADDSUBJECT [ / SSID ssid / ] buffer-var token-id [ token-value ]")
(set (intern "#EMSADDSUBJECTV"          tacl-eldoc-obarray) "#EMSADDSUBJECTV [ / SSID ssid / ] buffer-var token-id source-var")
(set (intern "#EMSGET"                  tacl-eldoc-obarray) "#EMSGET [ / option [ , option ] ... / ] buffer-var get-op")
(set (intern "#EMSGET/"                 tacl-eldoc-obarray) "#EMSGET [ /COUNT <num>,INDEX <num>,SSID <ssid>/")
(set (intern "#EMSGETV"                 tacl-eldoc-obarray) "#EMSGETV [ / option [ , option ] ... / ] buffer-var get-op result-var")
(set (intern "#EMSGETV/"                tacl-eldoc-obarray) "#EMSGETV [ /COUNT <num>,INDEX <num>,SSID <ssid>/")
(set (intern "#EMSINIT"                 tacl-eldoc-obarray) "#EMSINIT [ / {SSID <ssid>|TIMESTAMP <juliantimestamp>} / ] buffer-var ssid event-number token-id [ token-value ] ... ]")
(set (intern "#EMSINITV"                tacl-eldoc-obarray) "#EMSINITV [ / {SSID <ssid>|TIMESTAMP <juliantimestamp>} / ] buffer-var ssid event-number token-id source-var")
(set (intern "#EMSTEXT"                 tacl-eldoc-obarray) "#EMSTEXT [ / option [ , option ] ... / ] buffer-var")
(set (intern "#EMSTEXT/"                tacl-eldoc-obarray) "#EMSTEXT [ / INDENT <num chars>, INITTEMPLATE <struct>, LINES <num lines>, OPRLOG <num>, WIDTH <num chars> /")
(set (intern "#EMSTEXTV"                tacl-eldoc-obarray) "#EMSTEXTV [ / option [ , option ] ... / ] buffer-var formatted-var [ lengths-var ]")
(set (intern "#EMSTEXTV/"               tacl-eldoc-obarray) "#EMSTEXTV [ / INDENT <num chars>, INITTEMPLATE <struct>, LINES <num lines>, OPRLOG <num>, WIDTH <num chars> /")
(set (intern "#ENDTRANSACTION"          tacl-eldoc-obarray) "#ENDTRANSACTION")
(set (intern "#EOF"                     tacl-eldoc-obarray) "#EOF variable-level")
(set (intern "#ERRORNUMBERS"            tacl-eldoc-obarray) "#ERRORNUMBERS")
(set (intern "#ERRORTEXT"               tacl-eldoc-obarray) "#ERRORTEXT / { CAPTURE <var> | CLEAR } /")
(set (intern "#EXCEPTION"               tacl-eldoc-obarray) "#EXCEPTION")
(set (intern "#EXIT"                    tacl-eldoc-obarray) "#EXIT")
(set (intern "#EXTRACT"                 tacl-eldoc-obarray) "#EXTRACT variable-level")
(set (intern "#EXTRACTV"                tacl-eldoc-obarray) "#EXTRACTV from-variable-level to-variable-level")
(set (intern "#FILEGETLOCKINFO"         tacl-eldoc-obarray) "#FILEGETLOCKINFO [ / {PROCESSID <processid> | TRANSID <transid>} / ] fvname control lockdesc participants")
(set (intern "#FILEINFO"                tacl-eldoc-obarray) "#FILEINFO / option [ , option ] ... / file-name")
(set (intern "#FILEINFO/"               tacl-eldoc-obarray) "#FILEINFO /AUDITED,BLOCKLENGTH,CODE,CORRUPT,CRASHOPEN,CREATION_GMT,DATACOMPRESSION,DEVICETYPE,EOF,EXISTENCE,EXTENTSALLOCATED,FILE,FORMAT,FILESTRUCTURE,FULLNAME,INCOMPLETESQLDDL,INDEXCOMPRESSION,LASTOPEN_GMT,LICENSED,MAXBYTES,MAXEXTENTS,MODIFICATION,MODIFICATION_LCT,ODDUNSTR,OPENNOW,OWNER,PHYSICALFILENAME,PHYSICALVOLUME,PRIMARY,PROGID,RECORDLENGTH,REFRESH,SECONDARY,SECURITY,SUBVOL,SYSTEM,UNRECLAIMEDFREESPACE,VOLUME/")
(set (intern "#FILENAMES"               tacl-eldoc-obarray) "#FILENAMES [ / maximum <num>, NEWSUBVOL <var>, PREVIOUS <fname> / ] [ file-name-template ]")
(set (intern "#FILTER"                  tacl-eldoc-obarray) "#FILTER [ exception [ exception ] ... ]")
(set (intern "#FRAME"                   tacl-eldoc-obarray) "#FRAME")
(set (intern "#GETCONFIGURATION"        tacl-eldoc-obarray) "#GETCONFIGURATION / option [ , option ] ... /")
(set (intern "#GETCONFIGURATION/"       tacl-eldoc-obarray) "#GETCONFIGURATION / AUTOLOGOFFDELAY, BLINDLOGON, CMONREQUIRED, CONFIGRUN, LOGOFFSCREENCLEAR, NAMELOGON, NOCHANGEUSER, REMOTECMONREQUIRED, REMOTECMONTIMEOUT, REMOTESUPERID, REQUESTCMONUSERCONFIG, STOPONFEMODEMERR /")
(set (intern "#GETPROCESSSTATE"         tacl-eldoc-obarray) "#GETPROCESSSTATE [ / option [ , option ] ... / ]")
(set (intern "#GETPROCESSSTATE/"        tacl-eldoc-obarray) "#GETPROCESSSTATE [ / LOGGEDON, TSNLOGON, TSNLOGOFF, INHERITEDLOGON, STOPONLOGOFF, PROPAGATELOGON, PROPAGATESTOPONLOGOFF /")
(set (intern "#GETSCAN"                 tacl-eldoc-obarray) "#GETSCAN")
(set (intern "#HELPKEY"                 tacl-eldoc-obarray) "#HELPKEY")
(set (intern "#HIGHPIN"                 tacl-eldoc-obarray) "#HIGHPIN")
(set (intern "#HISTORY"                 tacl-eldoc-obarray) "#HISTORY [ / CLEARLAST, RESET, SHOW <num> / ]")
(set (intern "#HOME"                    tacl-eldoc-obarray) "#HOME")
(set (intern "#IF"                      tacl-eldoc-obarray) "#IF [ NOT ] numeric-expression [|then| statements][|else| statements]")
(set (intern "#IN"                      tacl-eldoc-obarray) "#IN")
(set (intern "#INFORMAT"                tacl-eldoc-obarray) "#INFORMAT")
(set (intern "#INITTERM"                tacl-eldoc-obarray) "#INITTERM")
(set (intern "#INLINEECHO"              tacl-eldoc-obarray) "#INLINEECHO")
(set (intern "#INLINEEOF"               tacl-eldoc-obarray) "#INLINEEOF")
(set (intern "#INLINEOUT"               tacl-eldoc-obarray) "#INLINEOUT")
(set (intern "#INLINEPREFIX"            tacl-eldoc-obarray) "#INLINEPREFIX")
(set (intern "#INLINEPROCESS"           tacl-eldoc-obarray) "#INLINEPROCESS")
(set (intern "#INLINETO"                tacl-eldoc-obarray) "#INLINETO")
(set (intern "#INPUT"                   tacl-eldoc-obarray) "#INPUT [ / option [ , option ] ... / ] [ prompt ]")
(set (intern "#INPUT/"                  tacl-eldoc-obarray) "#INPUT [ / CURRENT, FUNCTIONKEY <var>, HISTORY <prompt>, HISTORYV <var>, NOECHO, UNTIL {TACL | EOF} /")
(set (intern "#INPUTEOF"                tacl-eldoc-obarray) "#INPUTEOF")
(set (intern "#INPUTV"                  tacl-eldoc-obarray) "#INPUTV [ / option [ , option ] ... / ] variable-level prompt-string")
(set (intern "#INPUTV/"                 tacl-eldoc-obarray) "#INPUTV [ / CURRENT, FUNCTIONKEY <var>, HISTORY <prompt>, HISTORYV <var>, NOECHO, UNTIL {TACL | EOF} /")
(set (intern "#INSPECT"                 tacl-eldoc-obarray) "#INSPECT")
(set (intern "#INTERACTIVE"             tacl-eldoc-obarray) "#INTERACTIVE [ / CURRENT / ]")
(set (intern "#INTERPRETJULIANDAYNO"    tacl-eldoc-obarray) "#INTERPRETJULIANDAYNO julian-day-num")
(set (intern "#INTERPRETTIMESTAMP"      tacl-eldoc-obarray) "#INTERPRETTIMESTAMP four-word-timestamp")
(set (intern "#INTERPRETTRANSID"        tacl-eldoc-obarray) "#INTERPRETTRANSID transid")
(set (intern "#JULIANTIMESTAMP"         tacl-eldoc-obarray) "#JULIANTIMESTAMP [ type [ tuid-request ] ]")
(set (intern "#KEEP"                    tacl-eldoc-obarray) "#KEEP num variable")
(set (intern "#KEYS"                    tacl-eldoc-obarray) "#KEYS")
(set (intern "#LINEADDR"                tacl-eldoc-obarray) "#LINEADDR variable-level char-addr")
(set (intern "#LINEBREAK"               tacl-eldoc-obarray) "#LINEBREAK variable-level line-addr char-offset")
(set (intern "#LINECOUNT"               tacl-eldoc-obarray) "#LINECOUNT variable-level")
(set (intern "#LINEDEL"                 tacl-eldoc-obarray) "#LINEDEL variable-level line-addr-1 [ FOR line-count | TO line-addr-2 ]")
(set (intern "#LINEFIND"                tacl-eldoc-obarray) "#LINEFIND [ / EXACT / ] variable-level line-addr text")
(set (intern "#LINEFINDR"               tacl-eldoc-obarray) "#LINEFINDR [ / EXACT / ] variable-level line-addr text")
(set (intern "#LINEFINDRV"              tacl-eldoc-obarray) "#LINEFINDRV [ / EXACT / ] variable-level line-addr string")
(set (intern "#LINEFINDV"               tacl-eldoc-obarray) "#LINEFINDV [ / EXACT / ] variable-level line-addr string")
(set (intern "#LINEGET"                 tacl-eldoc-obarray) "#LINEGET string line-addr-1 [ FOR line-count | TO line-addr-2 ]")
(set (intern "#LINEGETV"                tacl-eldoc-obarray) "#LINEGETV string variable-level line-addr-1 [ FOR line-count | TO line-addr-2 ]")
(set (intern "#LINEINS"                 tacl-eldoc-obarray) "#LINEINS variable-level line-addr text")
(set (intern "#LINEINSV"                tacl-eldoc-obarray) "#LINEINSV variable-level line-addr string")
(set (intern "#LINEJOIN"                tacl-eldoc-obarray) "#LINEJOIN variable-level line-addr")
(set (intern "#LOAD"                    tacl-eldoc-obarray) "#LOAD [ / KEEP <num>, LOADED <var> / ] file-name")
(set (intern "#LOCKINFO"                tacl-eldoc-obarray) "#LOCKINFO lock-spec tag buffer")
(set (intern "#LOGOFF"                  tacl-eldoc-obarray) "#LOGOFF [ / option [ , option ] ... / ]")
(set (intern "#LOGOFF/"                 tacl-eldoc-obarray) "#LOGOFF [ / CLEAR, NOCLEAR, PAUSE, SEGRELEASE /")
(set (intern "#LOOKUPPROCESS"           tacl-eldoc-obarray) "#LOOKUPPROCESS / option [ , option ] ... / specifier")
(set (intern "#LOOKUPPROCESS/"          tacl-eldoc-obarray) "#LOOKUPPROCESS / ANCESTOR, BACKUP, ENTRY, PRIMARY, PROCESSID, RESULT /")
(set (intern "#LOOP"                    tacl-eldoc-obarray) "#LOOP {|WHILE| <expression> |DO| <statements>}{|DO| <statements>} |UNTIL| <expression>")
(set (intern "#MATCH"                   tacl-eldoc-obarray) "#MATCH template [ text ]")
(set (intern "#MOM"                     tacl-eldoc-obarray) "#MOM")
(set (intern "#MORE"                    tacl-eldoc-obarray) "#MORE")
(set (intern "#MYGMOM"                  tacl-eldoc-obarray) "#MYGMOM")
(set (intern "#MYPID"                   tacl-eldoc-obarray) "#MYPID")
(set (intern "#MYSYSTEM"                tacl-eldoc-obarray) "#MYSYSTEM")
(set (intern "#MYTERM"                  tacl-eldoc-obarray) "#MYTERM")
(set (intern "#NEWPROCESS"              tacl-eldoc-obarray) "#NEWPROCESS program-file [/CPU cpu-number,DEBUG,DEFMODE { OFF | ON },EXTSWAP [ file-name ],HIGHPIN { ON | OFF },IN [ file-name ],INLINE,INSPECT { OFF | ON | SAVEABEND },INV variable-level [ DYNAMIC [PROMPT variable-level] ],JOBID num,LIB [ file-name ],MEM num-pages,NAME [ $ process-name ],NOWAIT,OUT [ list-file ],OUTV variable-level,PFS num-pages,PRI priority,STATUS variable-level,SWAP file-name,TERM $ terminal-name,WINDOW [ \" text\" ]/] [ param-set ]")
(set (intern "#NEXTFILENAME"            tacl-eldoc-obarray) "#NEXTFILENAME [ file-name ]")
(set (intern "#OPENINFO"                tacl-eldoc-obarray) "#OPENINFO / option [ , option ] / { file-name | device-name } tag")
(set (intern "#OPENINFO/"               tacl-eldoc-obarray) "#OPENINFO / ACCESSID, ACCESSMODE, BACKUP, EXCLUSION, FILENAME, PRIMARY, PROCESSID, SYNCDEPTH /")
(set (intern "#OUT"                     tacl-eldoc-obarray) "#OUT")
(set (intern "#OUTFORMAT"               tacl-eldoc-obarray) "#OUTFORMAT")
(set (intern "#OUTPUT"                  tacl-eldoc-obarray) "#OUTPUT [ / option [ , option ] ... / ] [ text ]")
(set (intern "#OUTPUT/"                 tacl-eldoc-obarray) "#OUTPUT [ / COLUMN <num>, FILL {SPACE|ZERO}, HOLD, JUSTIFY {LEFT|RIGHT|CENTER}, WIDTH <num>, WORDS /")
(set (intern "#OUTPUTV"                 tacl-eldoc-obarray) "#OUTPUTV [ / option [ , option ] ... / ] string")
(set (intern "#OUTPUTV/"                tacl-eldoc-obarray) "#OUTPUTV [ / COLUMN <num>, FILL {SPACE|ZERO}, HOLD, JUSTIFY {LEFT|RIGHT|CENTER}, WIDTH <num>, WORDS /")
(set (intern "#PARAM"                   tacl-eldoc-obarray) "#PARAM [ param-name ]")
(set (intern "#PAUSE"                   tacl-eldoc-obarray) "#PAUSE [ [\\ node-name.]{$ process-name | cpu,pin } ]")
(set (intern "#PMSEARCHLIST"            tacl-eldoc-obarray) "#PMSEARCHLIST")
(set (intern "#PMSG"                    tacl-eldoc-obarray) "#PMSG")
(set (intern "#POP"                     tacl-eldoc-obarray) "#POP variable [ [,] variable ] ...")
(set (intern "#PREFIX"                  tacl-eldoc-obarray) "#PREFIX")
(set (intern "#PROCESS"                 tacl-eldoc-obarray) "#PROCESS")
(set (intern "#PROCESSEXISTS"           tacl-eldoc-obarray) "#PROCESSEXISTS [\\ node-name.]{$ process-name | cpu,pin }")
(set (intern "#PROCESSFILESECURITY"     tacl-eldoc-obarray) "#PROCESSFILESECURITY")
(set (intern "#PROCESSINFO"             tacl-eldoc-obarray) "#PROCESSINFO / option [ , {option | search-option} ] ... / [ [\\ node-name.]{$ process-name | cpu,pin } ]")
(set (intern "#PROCESSINFO/"            tacl-eldoc-obarray) "#PROCESSINFO/[SEARCH/search-option/],CAID,CONTEXTCHANGES,CPU,CURRENTMAINSTACKSIZE,CURRENTNATIVEHEAPSIZE,DEFINEMODE,EXTSWAP,GMOMJOBID,GUARANTEEDSWAPSPACE,HOMETERM,INITPRI,LOGONNAME,LIBRARY,LICENSES,LOGONSTATE,MAXMAINSTACKSIZE,MAXNATIVEHEAPSIZE,MOM,NATIVE,OSSARGUMENTS,OSSPATHNAME,OSSPID,PAID,PFR,PIN,PRI,PRIMARY,PROCESSDESCRIPTOR,PROCESSFILESECURITY,PROCESSID,PROCESSSTATE,PROCESSTIME,PROCESSTYPE,PROGRAMFILE,QUALINFOAVAIL,REMOTECREATOR,RESULT,SRLFILES,SRLNAMES,SRLNUMFILES,SRLNUMNAMES,SUBDEVICE,SWAP,SYSTEM,UPB,WAITSTATE,WT/")
(set (intern "SEARCH/"                  tacl-eldoc-obarray) "SEARCH/CAID <user>,GMOMJOBID <jobid>,HOMETERM <term-name>,MINPRI <num>,PAID <user>,PRI <num>,PROCESSID [[\\node-name.]{$process-name|cpu,pin}],PROGRAMFILE [[\\node-name.]file-name-template],SUBDEVICE <subdevice-type>,SYSTEM <node-name>/")
(set (intern "#PROCESSLAUNCH"           tacl-eldoc-obarray) "#PROCESSLAUNCH program-file [/CPU cpu-number,DEBUG,DEFMODE { OFF | ON },EXTSWAP file-name,GUARANTEEDSWAPSPACE num,HIGHPIN ON | OFF,IN file-name,INLINE,INSPECT {OFF | ON | SAVEABEND},INV variable-level [ DYNAMIC [ PROMPT variable-level ] ],JOBID num,LIB file-name,MAXMAINSTACKSIZE num,MAXNATIVEHEAPSIZE num,MEM num-pages,NAME $process-name,NOWAIT,OUT list-file,OUTV variable-level,PFS num-pages,PRI priority,STATUS variable-level,SWAP file-name,TERM $terminal-name,WINDOW \" text\"/] [ param-set ]")
(set (intern "#PROCESSORSTATUS"         tacl-eldoc-obarray) "#PROCESSORSTATUS [ \\ node-name ]")
(set (intern "#PROCESSORTYPE"           tacl-eldoc-obarray) "#PROCESSORTYPE [ / BOTH | NAME / ] { { [\\ node-name.]{$ process-name | cpu, pin } } | cpu-num")
(set (intern "#PROMPT"                  tacl-eldoc-obarray) "#PROMPT")
(set (intern "#PURGE"                   tacl-eldoc-obarray) "#PURGE file-name")
(set (intern "#PUSH"                    tacl-eldoc-obarray) "#PUSH variable [ [,] variable ] ")
(set (intern "#RAISE"                   tacl-eldoc-obarray) "#RAISE exception")
(set (intern "#REPLYV"                  tacl-eldoc-obarray) "#REPLYV string")
(set (intern "#REQUESTER"               tacl-eldoc-obarray) "#REQUESTER [ / option [ , option ] / ] { CLOSE variable-level } { READ file-name error-var read-var prompt-var } | { WRITE file-name error-var write-var }")
(set (intern "#REQUESTER/"              tacl-eldoc-obarray) "#REQUESTER [ / EXCLUSION {SHARED|PROTECTED|EXCLUSIVE}, EXCLUSIVE, PROTECTED, SHARED, WAIT <num-bytes>/")
(set (intern "#RESET"                   tacl-eldoc-obarray) "#RESET [ARGUMENTS] [FRAMES] [REPLY] [RESULTS]")
(set (intern "#REST"                    tacl-eldoc-obarray) "#REST")
(set (intern "#RESULT"                  tacl-eldoc-obarray) "#RESULT [ text ]")
(set (intern "#RETURN"                  tacl-eldoc-obarray) "#RETURN")
(set (intern "#ROUTEPMSG"               tacl-eldoc-obarray) "#ROUTEPMSG { ALL | STANDARD | ( message-type [ message-type ] ... ) }")
(set (intern "#ROUTINENAME"             tacl-eldoc-obarray) "#ROUTINENAME")
(set (intern "#SEGMENT"                 tacl-eldoc-obarray) "#SEGMENT [ / USED / ]")
(set (intern "#SEGMENTCONVERT"          tacl-eldoc-obarray) "#SEGMENTCONVERT / FORMAT { a | b } / old-file-name new-file-name")
(set (intern "#SEGMENTINFO"             tacl-eldoc-obarray) "#SEGMENTINFO / option [ , option ] / [ segment-id ]")
(set (intern "#SEGMENTINFO/"            tacl-eldoc-obarray) "#SEGMENTINFO / ACCESS, DIRECTORY, FILENAME, ID, PRIMARY, RESULT, SECONDARY, USECOUNT, USED /")
(set (intern "#SEGMENTVERSION"          tacl-eldoc-obarray) "#SEGMENTVERSION file-name")
(set (intern "#SERVER"                  tacl-eldoc-obarray) "#SERVER / option [ , option ] ... / [ server-name ]")
(set (intern "#SERVER/"                 tacl-eldoc-obarray) "#SERVER / {KILL <var> | IN <var>, OUT <var> [,PROMPT <var>]} /")
(set (intern "#SET"                     tacl-eldoc-obarray) "#SET { [ / option [, option ]/] variable-level [ text ] } | { built-in-variable [ built-in-text ] }")
(set (intern "#SET/"                    tacl-eldoc-obarray) "#SET { [ / IN <fname>, TYPE {ALIAS|DELTA|DIRECTORY|MACRO|ROUTINE|TEXT} /")
(set (intern "#SETBYTES"                tacl-eldoc-obarray) "#SETBYTES destination source")
(set (intern "#SETCONFIGURATION"        tacl-eldoc-obarray) "#SETCONFIGURATION / option [, option ] .../[ tacl-image-name]")
(set (intern "#SETCONFIGURATION/"       tacl-eldoc-obarray) "#SETCONFIGURATION / AUTOLOGOFFDELAY <delay>, BLINDLOGON {ON|OFF},CMONREQUIRED {ON|OFF},CMONTIMEOUT <timeout-val>,CONFIGRUN [PROCESSCREATE|PROCESSLAUNCH],LOGOFFSCREENCLEAR {ON|OFF},NAMELOGON {ON|OFF},NOCHANGEUSER {ON|OFF},REMOTECMONREQUIRED {ON|OFF},REMOTECMONTIMEOUT <timeout-val>,REMOTESUPERID {ON|OFF},REQUESTCMONUSERCONFIG {ON|OFF},STOPONFEMODEMERR {ON|OFF} /")
(set (intern "#SETMANY"                 tacl-eldoc-obarray) "#SETMANY variable-name-list , [ text ]")
(set (intern "#SETPROCESSSTATE"         tacl-eldoc-obarray) "#SETPROCESSSTATE / LOGGEDON | TSNLOGON | STOPONLOGOFF | PROPAGATELOGON | PROPAGATESTOPONLOGOFF / { 0 | 1 }")
(set (intern "#SETSCAN"                 tacl-eldoc-obarray) "#SETSCAN num")
(set (intern "#SETSYSTEMCLOCK"          tacl-eldoc-obarray) "#SETSYSTEMCLOCK julian-gmt mode [ tuid ]")
(set (intern "#SETV"                    tacl-eldoc-obarray) "#SETV dest- variable-level source- string")
(set (intern "#SHIFTDEFAULT"            tacl-eldoc-obarray) "#SHIFTDEFAULT")
(set (intern "#SHIFTSTRING"             tacl-eldoc-obarray) "#SHIFTSTRING [ / {DOWN|NOOP|UP} / ] [ text ]")
(set (intern "#SORT"                    tacl-eldoc-obarray) "#SORT [ / {ASCENDING|DESCENDING} / ] [ text ]")
(set (intern "#SPIFORMATCLOSE"          tacl-eldoc-obarray) "#SPIFORMATCLOSE")
(set (intern "#SSGET"                   tacl-eldoc-obarray) "#SSGET [ / COUNT <count>, INDEX <index>, SSID <ssid> / ] buffer-var get-op")
(set (intern "#SSGETV"                  tacl-eldoc-obarray) "#SSGETV [ / COUNT <count>, INDEX <index>, SSID <ssid> / ] buffer-var get-op result-var")
(set (intern "#SSINIT"                  tacl-eldoc-obarray) "#SSINIT [ / TYPE 0 / ] buffer-var ssid command [ / type-0-option [ , type-0-option ] ... / ] token-id")
(set (intern "#SSMOVE"                  tacl-eldoc-obarray) "#SSMOVE [ / COUNT <num>, DINDEX <dest-index>, SINDEX <source-index>, SSID <ssid> / ] source-var dest-var token-id")
(set (intern "#SSNULL"                  tacl-eldoc-obarray) "#SSNULL token-map struct")
(set (intern "#SSPUT"                   tacl-eldoc-obarray) "#SSPUT [ / COUNT <count>, SSID <ssid> / ] buffer-var token-id [ token-value [ t oken-value ] ... ]")
(set (intern "#SSPUTV"                  tacl-eldoc-obarray) "#SSPUTV [ / COUNT <count>, SSID <ssid> / ] buffer-var token-id source-var")
(set (intern "#STOP"                    tacl-eldoc-obarray) "#STOP [ / COMPLETIONCODE <num>, ERROR, SUBSYS <ssid>, TERMINATIONINFO <num> / ] [ [\\ node-name.]{$ process-name | cpu,pin } [ text ] ]")
(set (intern "#SUSPENDPROCESS"          tacl-eldoc-obarray) "#SUSPENDPROCESS [ [\\ node-name.]{$ process-name | cpu,pin} ]")
(set (intern "#SWITCH"                  tacl-eldoc-obarray) "#SWITCH")
(set (intern "#SYSTEM"                  tacl-eldoc-obarray) "#SYSTEM [ \\ node-name ]")
(set (intern "#SYSTEMNAME"              tacl-eldoc-obarray) "#SYSTEMNAME system-number")
(set (intern "#SYSTEMNUMBER"            tacl-eldoc-obarray) "#SYSTEMNUMBER \\ node-name")
(set (intern "#TACLOPERATION"           tacl-eldoc-obarray) "#TACLOPERATION")
(set (intern "#TACLSECURITY"            tacl-eldoc-obarray) "#TACLSECURITY")
(set (intern "#TACLVERSION"             tacl-eldoc-obarray) "#TACLVERSION / REVISION /")
(set (intern "#TIMESTAMP"               tacl-eldoc-obarray) "#TIMESTAMP")
(set (intern "#TOSVERSION"              tacl-eldoc-obarray) "#TOSVERSION [ \\ node-name ]")
(set (intern "#TRACE"                   tacl-eldoc-obarray) "#TRACE")
(set (intern "#UNFRAME"                 tacl-eldoc-obarray) "#UNFRAME")
(set (intern "#USELIST"                 tacl-eldoc-obarray) "#USELIST")
(set (intern "#USERID"                  tacl-eldoc-obarray) "#USERID user")
(set (intern "#USERNAME"                tacl-eldoc-obarray) "#USERNAME user")
(set (intern "#VARIABLEINFO"            tacl-eldoc-obarray) "#VARIABLEINFO / option [ , option ] ... / variable-level")
(set (intern "#VARIABLEINFO/"           tacl-eldoc-obarray) "#VARIABLEINFO / DEPTH, DIRECTORY, EXISTENCE, FRAME, LEN, LEVEL, LINES, MODE, OCCURS, OFFSET, PROCESS, REQUESTER, SEGMENT, SERVER, TYPE, VARIABLE /")
(set (intern "#VARIABLES"               tacl-eldoc-obarray) "#VARIABLES [ / { BREAKPOINT | IO } / ]")
(set (intern "#VARIABLESV"              tacl-eldoc-obarray) "#VARIABLESV [ / { BREAKPOINT | IO } / ] variable-level")
(set (intern "#WAIT"                    tacl-eldoc-obarray) "#WAIT variable-level [ variable-level ] ...")
(set (intern "#WAKEUP"                  tacl-eldoc-obarray) "#WAKEUP")
(set (intern "#WIDTH"                   tacl-eldoc-obarray) "#WIDTH")

(set (intern "#SET#ASSIGN"              tacl-eldoc-obarray) "#SET #ASSIGN [ [ / option [ , option ] ... / ] logical-unit ]")
(set (intern "#SET#BREAKMODE"           tacl-eldoc-obarray) "#SET #BREAKMODE { DISABLE | ENABLE | POSTPONE }")
(set (intern "#SET#CHARACTERRULES"      tacl-eldoc-obarray) "#SET #CHARACTERRULES file-name")
(set (intern "#SET#DEFAULTS"            tacl-eldoc-obarray) "#SET #DEFAULTS subvolume-name")
(set (intern "#SET#DEFINEMODE"          tacl-eldoc-obarray) "#SET #DEFINEMODE { OFF | ON }")
(set (intern "#SET#ERRORNUMBERS"        tacl-eldoc-obarray) "#SET #ERRORNUMBERS n n n n")
(set (intern "#SET#EXIT"                tacl-eldoc-obarray) "#SET #EXIT num")
(set (intern "#SET#HELPKEY"             tacl-eldoc-obarray) "#SET #HELPKEY [ key-name ]")
(set (intern "#SET#HIGHPIN"             tacl-eldoc-obarray) "#SET #HIGHPIN { OFF | ON }")
(set (intern "#SET#HOME"                tacl-eldoc-obarray) "#SET #HOME directory")
(set (intern "#SET#IN"                  tacl-eldoc-obarray) "#SET #IN file-name")
(set (intern "#SET#INFORMAT"            tacl-eldoc-obarray) "#SET #INFORMAT { PLAIN | QUOTED | TACL }")
(set (intern "#SET#INLINEECHO"          tacl-eldoc-obarray) "#SET #INLINEECHO num")
(set (intern "#SET#INLINEOUT"           tacl-eldoc-obarray) "#SET #INLINEOUT num")
(set (intern "#SET#INLINEPREFIX"        tacl-eldoc-obarray) "#SET #INLINEPREFIX [ prefix ]")
(set (intern "#SET#INLINETO"            tacl-eldoc-obarray) "#SET #INLINETO [ variable-level ]")
(set (intern "#SET#INPUTEOF"            tacl-eldoc-obarray) "#SET #INPUTEOF num")
(set (intern "#SET#INSPECT"             tacl-eldoc-obarray) "#SET #INSPECT { OFF | ON | SAVEABEND }")
(set (intern "#SET#MYTERM"              tacl-eldoc-obarray) "#SET #MYTERM home-term")
(set (intern "#SET#OUT"                 tacl-eldoc-obarray) "#SET #OUT file-name")
(set (intern "#SET#OUTFORMAT"           tacl-eldoc-obarray) "#SET #OUTFORMAT { PLAIN | PRETTY | TACL }")
(set (intern "#SET#PARAM"               tacl-eldoc-obarray) "#SET #PARAM [ param-name [ param-value ] ]")
(set (intern "#SET#PMSEARCHLIST"        tacl-eldoc-obarray) "#SET #PMSEARCHLIST searchlist")
(set (intern "#SET#PMSG"                tacl-eldoc-obarray) "#SET #PMSG num")
(set (intern "#SET#PREFIX"              tacl-eldoc-obarray) "#SET #PREFIX [ text ]")
(set (intern "#SET#PROCESSFILESECURITY" tacl-eldoc-obarray) "#SET #PROCESSFILESECURITY \" security\"")
(set (intern "#SET#PROMPT"              tacl-eldoc-obarray) "#SET #PROMPT num")
(set (intern "#SET#REPLYPREFIX"         tacl-eldoc-obarray) "#SET #REPLYPREFIX [ num ]")
(set (intern "#SET#SHIFTDEFAULT"        tacl-eldoc-obarray) "#SET #SHIFTDEFAULT { DOWN | NOOP | UP }")
(set (intern "#SET#TACLSECURITY"        tacl-eldoc-obarray) "#SET #TACLSECURITY \" security\"")
(set (intern "#SET#TRACE"               tacl-eldoc-obarray) "#SET #TRACE num")
(set (intern "#SET#USELIST"             tacl-eldoc-obarray) "#SET #USELIST [ directory-name [ directory-name ] ... ]")
(set (intern "#SET#WAKEUP"              tacl-eldoc-obarray) "#SET #WAKEUP num")
(set (intern "#SET#WIDTH"               tacl-eldoc-obarray) "#SET #WIDTH <num characters before wrapping occurs>")

(set (intern "ACTIVATE"                 tacl-eldoc-obarray) "ACTIVATE [ [\ node-name.]{$ process-name | cpu,pin } ]")
(set (intern "ADD"                      tacl-eldoc-obarray) "ADD DEFINE { define-name} { define-name [, define-name ] ... )} [ , LIKE define-name ] [ , attribute-spec ] ...")
(set (intern "ADDDSTTRANSITION"         tacl-eldoc-obarray) "ADDDSTTRANSITION start-date-time , stop-date-time , offset")
(set (intern "ADDUSER"                  tacl-eldoc-obarray) "ADDUSER [ / run-option [ , run-option ] ... / ] group-name. user-name , group-id, user-id")
(set (intern "ALARMOFF"                 tacl-eldoc-obarray) "ALARMOFF")
(set (intern "ALTER"                    tacl-eldoc-obarray) "ALTER DEFINE define-name-list { attribute-spec} { RESET reset-list}")
(set (intern "ALTPRI"                   tacl-eldoc-obarray) "ALTPRI [\ node-name.]{$ process-name | cpu, pin } , pri")
(set (intern "ASSIGN"                   tacl-eldoc-obarray) "ASSIGN [ logical-unit [ , [ actual-file-name ] [ , create-open-spec ] ... ] ]")
(set (intern "ATTACHSEG"                tacl-eldoc-obarray) "ATTACHSEG {PRIVATE | SHARED} file-name directory-name")
(set (intern "BACKUPCPU"                tacl-eldoc-obarray) "BACKUPCPU [ cpu ]")
(set (intern "BREAK"                    tacl-eldoc-obarray) "BREAK [ variable-level ]")
(set (intern "BUILTINS"                 tacl-eldoc-obarray) "BUILTINS [ / { FUNCTIONS | VARIABLES } / ]")
(set (intern "BUSCMD"                   tacl-eldoc-obarray) "BUSCMD [ / run-option [ , run-option ] ... / ] { X | Y } , { DOWN | UP } , from-cpu , to-cpu")
(set (intern "CLEAR"                    tacl-eldoc-obarray) "CLEAR { ALL } | { ALL ASSIGN | ALL PARAM | ASSIGN logical-unit | PARAM param-name }")
(set (intern "COLUMNIZE"                tacl-eldoc-obarray) "COLUMNIZE list")
(set (intern "COMMENT"                  tacl-eldoc-obarray) "COMMENT [ comment-text ]")
(set (intern "_COMPAREV"                tacl-eldoc-obarray) "_COMPAREV string-1 string-2")
(set (intern "COMPUTE"                  tacl-eldoc-obarray) "COMPUTE expression")
(set (intern "_CONTIME_TO_TEXT"         tacl-eldoc-obarray) "_CONTIME_TO_TEXT contime-list")
(set (intern "_CONTIME_TO_TEXT_DATE"    tacl-eldoc-obarray) "_CONTIME_TO_TEXT_DATE contime-list")
(set (intern "_CONTIME_TO_TEXT_TIME"    tacl-eldoc-obarray) "_CONTIME_TO_TEXT_TIME contime-list")
(set (intern "COPYDUMP"                 tacl-eldoc-obarray) "COPYDUMP [ / run-option [ , run-option ] ... / ] source-file , dest-file")
(set (intern "CREATE"                   tacl-eldoc-obarray) "CREATE file-name [ , parameter [ , parameter ] ]")
(set (intern "CREATESEG"                tacl-eldoc-obarray) "CREATESEG file-name")
(set (intern "DEBUG"                    tacl-eldoc-obarray) "DEBUG [ [\ node-name.]{$ process-name | cpu,pin } ] [ , TERM [\ node-name.]$ terminal-name ]")
(set (intern "_DEBUGGER"                tacl-eldoc-obarray) "_DEBUGGER current-trace-value reason-for-entry")
(set (intern "DEFAULT"                  tacl-eldoc-obarray) "DEFAULT [ / run-option [ , run-option ] ... / ] default-names [\" default-security\"] \" default-security\"")
(set (intern "DELETE"                   tacl-eldoc-obarray) "DELETE DEFINE define-name-list")
(set (intern "DELUSER"                  tacl-eldoc-obarray) "DELUSER [ / run-option [ , run-option ] ... / ] group-name.user-name")
(set (intern "ENV"                      tacl-eldoc-obarray) "ENV [ environment-parameter ]")
(set (intern "EXIT"                     tacl-eldoc-obarray) "EXIT")
(set (intern "FC"                       tacl-eldoc-obarray) "FC [ num | -num | text ]")
(set (intern "FILEINFO"                 tacl-eldoc-obarray) "FILEINFO [ / OUT list-file / ] [ file-name-template [ [,] file-name-template ] ... ]")
(set (intern "FILENAMES"                tacl-eldoc-obarray) "FILENAMES [ / OUT list-file / ] [ file-name-template [ [,] file-name-template ] ... ]")
(set (intern "FILES"                    tacl-eldoc-obarray) "FILES [ / OUT list-file / ] [ subvol-template [ [,] subvol-template ] ... ]")
(set (intern "FILETOVAR"                tacl-eldoc-obarray) "FILETOVAR file-name variable-level")
(set (intern "HELP"                     tacl-eldoc-obarray) "HELP")
(set (intern "HISTORY"                  tacl-eldoc-obarray) "HISTORY [ num ]")
(set (intern "HOME"                     tacl-eldoc-obarray) "HOME [ directory-name ]")
(set (intern "INFO"                     tacl-eldoc-obarray) "INFO [ / OUT list-file / ] DEFINE define-name-list [ , DETAIL ]")
(set (intern "INITTERM"                 tacl-eldoc-obarray) "INITTERM")
(set (intern "INLECHO"                  tacl-eldoc-obarray) "INLECHO { OFF | ON }")
(set (intern "INLEOF"                   tacl-eldoc-obarray) "INLEOF")
(set (intern "INLOUT"                   tacl-eldoc-obarray) "INLOUT { OFF | ON }")
(set (intern "INLPREFIX"                tacl-eldoc-obarray) "INLPREFIX [ prefix ]")
(set (intern "INLTO"                    tacl-eldoc-obarray) "INLTO [ variable-level ]")
(set (intern "JOIN"                     tacl-eldoc-obarray) "JOIN variable-level")
(set (intern "KEEP"                     tacl-eldoc-obarray) "KEEP [ / LIST / ] num variable [ variable ] ...")
(set (intern "KEYS"                     tacl-eldoc-obarray) "KEYS")
(set (intern "LIGHTS"                   tacl-eldoc-obarray) "LIGHTS [ ON | OFF | SMOOTH { num }] [ [ sys-option ] | [ ALL ] ] [ , BEAT ]")
(set (intern "LOAD"                     tacl-eldoc-obarray) "LOAD [ / KEEP num / ] file-name [ file-name ] ...")
(set (intern "LOADEDFILES"              tacl-eldoc-obarray) "LOADEDFILES [ / OUT list-file / ][ \ node-name ] { $Process-name | CPU, PIN|}")
(set (intern "LOGOFF"                   tacl-eldoc-obarray) "LOGOFF [ / option [, option ] ... / ]")
(set (intern "_LONGEST"                 tacl-eldoc-obarray) "_LONGEST list")
(set (intern "_MONTH3"                  tacl-eldoc-obarray) "_MONTH3 num")
(set (intern "OBEY"                     tacl-eldoc-obarray) "OBEY command-file")
(set (intern "OUTVAR"                   tacl-eldoc-obarray) "OUTVAR [ / option [ , option ] ... / ] string")
(set (intern "PARAM"                    tacl-eldoc-obarray) "PARAM [ param-name param-value [ , param-name param-value ] ... ]")
(set (intern "PASSWORD"                 tacl-eldoc-obarray) "PASSWORD [ / run-option [ , run-option ] ... / ][ password ]")
(set (intern "PAUSE"                    tacl-eldoc-obarray) "PAUSE [ [\ node-name.]{$ process-name | cpu,pin } ]")
(set (intern "PMSEARCH"                 tacl-eldoc-obarray) "PMSEARCH subvol-spec [ [,] subvol-spec ] ...")
(set (intern "PMSG"                     tacl-eldoc-obarray) "PMSG { ON | OFF }")
(set (intern "POP"                      tacl-eldoc-obarray) "POP variable [ [,] variable ] ...")
(set (intern "PPD"                      tacl-eldoc-obarray) "PPD [ / OUT list-file / ] [ [ \ node-name] [.{ $ process-name | cpu,pin | * } ] ...]")
(set (intern "PURGE"                    tacl-eldoc-obarray) "PURGE [ / option / ] file-name-template [ , file-name-template ... ]")
(set (intern "PUSH"                     tacl-eldoc-obarray) "PUSH variable [ [,] variable ] ...")
(set (intern "RCVDUMP"                  tacl-eldoc-obarray) "RCVDUMP [ / run-option [ , run-option ] ... / ] dump-file , cpu , [ fabric, param [ , param ] ]")
(set (intern "RECEIVEDUMP"              tacl-eldoc-obarray) "RECEIVEDUMP / OUT dump-file / cpu , fabric [ , param [ , param ] ]")
(set (intern "RELOAD"                   tacl-eldoc-obarray) "RELOAD [ / run-option [ , run-option ] ... / ] cpu-set [; cpu-set ] ... [ HELP ]")
(set (intern "REMOTEPASSWORD"           tacl-eldoc-obarray) "REMOTEPASSWORD [ \ node-name [ , password ] ]")
(set (intern "RENAME"                   tacl-eldoc-obarray) "RENAME old-file-name [,] new-file-name")
(set (intern "RESET"                    tacl-eldoc-obarray) "RESET DEFINE { attribute-name [ attribute-name ] ... } { * }")
(set (intern "SEGINFO"                  tacl-eldoc-obarray) "SEGINFO")
(set (intern "SET"                      tacl-eldoc-obarray) "SET DEFINE { { attribute-spec } | { LIKE define-name } } [ , attribute-spec ] ...\n SET DEFMODE { ON | OFF })\n SET HIGHPIN { ON | OFF })\n SET INSPECT { OFF | ON | SAVEABEND }")
(set (intern "SETPROMPT"                tacl-eldoc-obarray) "SETPROMPT { SUBVOL | VOLUME | BOTH | NONE }")
(set (intern "SET"                      tacl-eldoc-obarray) "SET SWAP [ $ volume-name ]")
(set (intern "SETTIME"                  tacl-eldoc-obarray) "SETTIME { month day | day month } year , hour: min[: sec] { GMT | LST | LCT }")
(set (intern "SET"                      tacl-eldoc-obarray) "SET VARIABLE [ / option [ , option ] / ] variable-level [ text ]")
(set (intern "SHOW"                     tacl-eldoc-obarray) "SHOW [ / OUT list-file / ] [ attribute [ , attribute ] ... ]")
(set (intern "SHOW"                     tacl-eldoc-obarray) "SHOW [ / OUT list-file / ] DEFINE [ attribute-name | * ]")
(set (intern "SINK"                     tacl-eldoc-obarray) "SINK [ text ]")
(set (intern "STATUS"                   tacl-eldoc-obarray) "STATUS [ / OUT list-file / ] [ range ] [ , condition ] ... [ , DETAIL ] [ , STOP ]")
(set (intern "STOP"                     tacl-eldoc-obarray) "STOP [ [\ node-name.]{$ process-name | cpu,pin} ]")
(set (intern "SUSPEND"                  tacl-eldoc-obarray) "SUSPEND [ [\ node-name.]{$ process-name | cpu,pin } ]")
(set (intern "SWITCH"                   tacl-eldoc-obarray) "SWITCH")
(set (intern "SYSTEM"                   tacl-eldoc-obarray) "SYSTEM [ \ node-name ]")
(set (intern "SYSTIMES"                 tacl-eldoc-obarray) "SYSTIMES")
(set (intern "TIME"                     tacl-eldoc-obarray) "TIME")
(set (intern "USE"                      tacl-eldoc-obarray) "USE [ directory-name [ [,] directory-name ] ... ]")
(set (intern "USERS"                    tacl-eldoc-obarray) "USERS [ / run-option [ , run-option ] ... / ] [ range ]")
(set (intern "VARIABLES"                tacl-eldoc-obarray) "VARIABLES [ directory-name ]")
(set (intern "VARINFO"                  tacl-eldoc-obarray) "VARINFO [ variable [ [,] variable ] ... ]")
(set (intern "VARTOFILE"                tacl-eldoc-obarray) "VARTOFILE variable-level file-name")
(set (intern "VCHANGE"                  tacl-eldoc-obarray) "VCHANGE [ / option [ , option ] ... / ] variable-level string-1 string-2 [ range ]")
(set (intern "VCOPY"                    tacl-eldoc-obarray) "VCOPY [ / option [ , option ] ... / ] source-var range dest-var dest-line")
(set (intern "VDELETE"                  tacl-eldoc-obarray) "VDELETE [ / option [ , option ] / ... ] variable-level range")
(set (intern "VFIND"                    tacl-eldoc-obarray) "VFIND [ / option [ , option ] / ... ] variable-level string [ range ]")
(set (intern "VINSERT"                  tacl-eldoc-obarray) "VINSERT variable-level line-num")
(set (intern "VLIST"                    tacl-eldoc-obarray) "VLIST [ / option [ , option ] / ... ] variable-level [ range ]")
(set (intern "VMOVE"                    tacl-eldoc-obarray) "VMOVE [ / option [ , option ] / ... ] source-var range dest-var dest-line")
(set (intern "VOLUME"                   tacl-eldoc-obarray) "VOLUME [ [\ node-name.] volume ] [ , \" security\" ]")
(set (intern "VTREE"                    tacl-eldoc-obarray) "VTREE [ directory-name ]")
(set (intern "WAKEUP"                   tacl-eldoc-obarray) "WAKEUP { ON | OFF }")
(set (intern "WHO"                      tacl-eldoc-obarray) "WHO")
(set (intern "XBUSDOWN"                 tacl-eldoc-obarray) "XBUSDOWN from-cpu , to-cpu")
(set (intern "YBUSDOWN"                 tacl-eldoc-obarray) "YBUSDOWN from-cpu , to-cpu")
(set (intern "XBUSUP"                   tacl-eldoc-obarray) "XBUSUP from-cpu , to-cpu")
(set (intern "YBUSUP"                   tacl-eldoc-obarray) "YBUSUP from-cpu , to-cpu")
;;; tacl-syntax.el ends here
